docs/#860kerberos authentication
redpanda-data/documentation pull request #1005
Opened 2023-01-10 01:15 UTC by micheleRP

resolves #860 

This adds support for Kerberos authentication.

Preview doc:

2023-01-19 03:20 UTC, micheleRP commented
Hi @dcoded! Would you please review this, see what's missing?

2023-01-23 15:57 UTC, BenPope reviewed
Just a quick review for now.

There's also a new configuraton option `rpk cluster config set sasl_kerberos_principal redpanda` (`redpanda` is the default), which should be set to the primary of the service principal name (SPN).

I'll add more details soon.

2023-01-23 15:57 UTC, BenPope commented on docs/platform/security/authentication.mdx
> +  $ sudo apt install krb5-workstation krb5-libs
These libraries don't exist on ubuntu. I'm trying to figure out what's going to be needed.

2023-01-23 15:57 UTC, BenPope commented on docs/platform/security/authentication.mdx
> +1. For each node, create two principals: `host/<FQDN>@<REALM>.COM` and `redpanda/<FQDN>@<REALM>.COM`, ensuring that the expiration date is long enough and that the tickets are renewable.
The host principal isn't required.

2023-01-23 15:57 UTC, BenPope commented on docs/platform/security/authentication.mdx
> +  $ rpk security generate-keytabs --regenerate
None of `rpk security` exists yet. I'm not sure what the plan is, I'll figure it out soon.

2023-01-23 15:57 UTC, BenPope commented on docs/platform/security/authentication.mdx
> +  $ rpk cluster config set enable_sasl true
This might be inconsistent with the with the rest of the docs, which may suggest `enable_kafka_authorization` instead.

2023-01-25 19:49 UTC, micheleRP commented on docs/platform/security/authentication.mdx
> +1. For each node, create two principals: `host/<FQDN>@<REALM>.COM` and `redpanda/<FQDN>@<REALM>.COM`, ensuring that the expiration date is long enough and that the tickets are renewable.
thanks, @BenPope. I've updated.

2023-01-26 16:59 UTC, dcoded commented
The `rpk security` stuff isn't going to be ready for this release. Can we cut steps 1 and 2 under the "Enable Kerberos" section and expand Step 3 into more detail? Maybe something like closer to the following:




1. Define the location of the Redpanda keytab file. This must be located at an identical file path on all Redpanda nodes, and by default is set to `/var/lib/redpanda/redpanda.keytab`:
```
$ rpk cluster config set sasl_kerberos_keytab <path>
```

2. Define the service principal to be used by Redpanda with the given keytab. By default this is set to `redpanda`:
```
$ rpk cluster config set sasl_kerberos_principal <name>
```

3. Append the list of allowed SASL mechanisms that clients can use to authenticate against the Kafka API. For example, if Redpanda currently supports only SCRAM then the configuration may return the following:
```
$ rpk cluster config get sasl_mechanisms
- SCRAM
```

To add support for Kerberos append `sasl_mechanisms` property with either the value `GSSAPI` :
```
$ rpk cluster config set sasl_mechanisms SCRAM,GSSAPI
```

or its synonym `KERBEROS`:
```
$ rpk cluster config set sasl_mechanisms SCRAM,KERBEROS
```

4. Enable SASL if not already enabled:
```
$ rpk cluster config set enable_sasl true
```

5. If authentication is being configured for the first time you may need to configure authorization ACLs before users can access Redpanda resources.

2023-01-26 19:23 UTC, micheleRP commented on docs/platform/security/authentication.mdx
> +  $ rpk security generate-keytabs --regenerate
This step was removed with Denis' feedback below.

2023-01-26 19:25 UTC, micheleRP commented on docs/platform/security/authentication.mdx
> +  $ sudo apt install krb5-workstation krb5-libs
Updated with: 
Install the `krb5-workstation` library on all Redpanda nodes. For example, on RHEL/CentOS:
   
  ```bash
  $ sudo yum install krb5-workstation krb5-libs
  ```

2023-01-26 19:35 UTC, micheleRP commented
Thank you, @dcoded and @BenPope! The updated draft has your feedback incorporated. Please let me know if you want to document current limitations.

2023-01-27 16:23 UTC, BenPope commented on docs/manage/security/authentication.mdx
>  ### Configure Schema Registry and HTTP Proxy to connect to Redpanda with SASL
We should probably make a note that the Schema Registry and HTTP Proxy do not support SASL/GSSAPI, only SASL/SCRAM.

2023-01-27 16:23 UTC, BenPope commented on docs/manage/security/authorization.mdx
> +This command creates a single SASL user with the given password, and optionally with a custom "mechanism". The mechanism determines which authentication flow the client uses for this user/password. R
This change isn't correct. There is no need for a user when using SASL/GSSAPI; the users are managed externally. 

The `sasl_kerberos_principal_mapping` is for mapping the external users onto redpanda principals used in the ACLs.

So I guess in general we're not creating SASL users, we're creating SASL/SCRAM users.

2023-01-27 16:34 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +  ```
Nothing on this page requires those libraries. Redpanda packages the libraries it needs.

2023-01-27 16:34 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +3. Install required libraries for Kerberos on Redpanda nodes. Configure the `/etc/krb5.conf` file to use Active Directory or another corporate key distribution center (KDC).
```suggestion
3. Configure the `/etc/krb5.conf` file to use Active Directory or another corporate key distribution center (KDC).`
```

2023-01-27 16:54 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +#### Enable Kerberos
I think we're missing a section for `sasl_kerberos_principal_mapping` - the rules are described here: https://kafka.apache.org/documentation/#security_authz_sasl

2023-01-27 16:59 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +#### Enable Kerberos
We can get and set them like this:

```
rpk cluster config get sasl_kerberos_principal_mapping
```
```
rpk cluster config set sasl_kerberos_principal_mapping '["RULE:[1:$1@$0](.*@MYDOMAIN.COM)s/@.*//","DEFAULT"]'

2023-01-27 17:36 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +  or with its synonym value `KERBEROS`:
Let's drop this for now, and have only GSSAPI as the way for configuring GSSAPI.

2023-01-27 19:41 UTC, micheleRP commented on docs/manage/security/authorization.mdx
> +<td>The authentication mechanism to use. Supported values: GSSAPI, SCRAM-SHA-256, SCRAM-SHA-512.</td>
Thanks @BenPope. I updated & added a link to the authN page for GSSAPI info. Is that OK? See https://deploy-preview-1005--redpanda-documentation.netlify.app/docs/manage/security/authorization/#user-create

2023-01-27 19:42 UTC, micheleRP commented on docs/manage/security/authentication.mdx
> +#### Enable Kerberos
Thanks @BenPope. Please confirm if these prereq steps look OK now: https://deploy-preview-1005--redpanda-documentation.netlify.app/docs/manage/security/authentication/#enable-kerberos

2023-01-27 19:46 UTC, michael-redpanda commented on docs/manage/security/authentication.mdx
> +4. For each node, create the principal `redpanda/<FQDN>@<REALM>`, ensuring that the expiration date is long enough and that the ticket is renewable.
I believe we want "key tab" instead of "ticket".  @BenPope ?  Expiration of what?  The key tab?

2023-01-28 17:39 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +  For information about the rules, see the [Kafka documentation](https://kafka.apache.org/documentation/#security_authz_sasl).
suggestion:
```
3. Set `sasl_kerberos_principal_mapping`. This maps external users onto Redpanda principals used in the ACLs.

  By default Redpanda matches the primary of the Kerberos user principal (UPN) of the user.

  Each rule has the following format:
  
    * `RULE:[n:string](regexp)s/pattern/replacement/g/c`. Where:
    
      * `n` is an integer that indicates how many components the target principal should have.
      * If this matches, then a string will be formed from `string`, substituting the realm of the principal for `$0` and the `n`’th component of the principal for `$n` (e.g., if the principal was `johndoe/admin` then `[2:$2$1foo]` would result in the string `adminjohndoefoo`).
      * If this string matches `regexp`, then the `s//[g]` substitution command will be run over the string. The optional `g` will cause the substitution to be global over the string, instead of replacing only the first match in the string.
      * `/c` is optional and can be either `/L` or `/U` to make the match lowercase or uppercase.

    * `DEFAULT` The principal name will be used as the local user name. If the principal has more than one component or is not in the default realm, this rule is not applicable and the conversion will fail.

  Some examples for a Kerberos UPN without a host (`jdoe`) and with a host (`jdoe/host`):

  | Translation | jdoe | jdoe/host |
  | -- | -- | -- |
  | `[1:$1@$0]` | `jdoe@EXAMPLE.COM` | Rule does not match¹ |
  | `[1:$1]` | `jdoe` | Rule does not match¹ |
  | `[1:$1.foo]` | `jdoe.foo` | Rule does not match¹ |
  | `[1:$1](.*)s/(.*)/$1/U` | `JDOE` | Rule does not match¹ |
  | `[2:$1/$2@$0]` | Rule does not match² | `jdoe/host@EXAMPLE.COM` |
  | `[2:$1/$2]` | Rule does not match² | `jdoe/host` |
  | `[2:$1@$0]` | Rule does not match² | `jdoe@EXAMPLE.COM` |
  | `[2:$1]` | Rule does not match² | `jdoe` |
  | `[2:$1](.*)s//U` | Rule does not match² | `JDOE` |
  | `[2:$1/$2](.*)s/(^[/]*)\/^[/]*/$1\/$2//U` | Rule does not match² | `JDOE/host` |
  | `[2:$1/$2](.*)s/(^[/]*)\/^[/]*/$1\/$2/g/U` | Rule does not match² | `JDOE/HOST` |
  | `DEFAULT` | `jdoe` | `jdoe` |

  ¹ Rule does not match because there are two components in principal name `jdoe/host@YOUR-REALM.COM`

  ² Rule does not match because there is one component in principal name `jdoe@YOUR-REALM.COM`

  The first rule that matches is used to extract a principal.

  To get the `sasl_kerberos_principal_mapping` property, run:

  ```bash
  rpk cluster config get sasl_kerberos_principal_mapping
  ```

  To set the `sasl_kerberos_principal_mapping` property, run:

  ```bash
  rpk cluster config set sasl_kerberos_principal_mapping '["RULE:[1:$1@$0](.*@MYDOMAIN.COM)s/@.*//","DEFAULT"]'
  ```
@michael-redpanda I took these from the PRD, but are they correct?

2023-01-28 18:16 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +4. For each node, create the principal `redpanda/<FQDN>@<REALM>`, ensuring that the expiration date is long enough and that the ticket is renewable.
I don't think we should specify too much here, it's up to the administrator of Kerberos.

Setting up the `krb5.conf`, and keytabs are up to the Kerberos administrator. 

```suggestion
4. Ensure each node has a valid kerberos service principal (SPN) `redpanda/<FQDN>@<REALM>`.
```

Perhaps the order is tweaked a bit:

### Prerequisites:

1. Ensure hostnames are fully qualified (we should add some more details here).
2. Ensure there is an `/etc/krb5.conf`on the node (I don't know if this is strictly necessary).
3. Ensure the KDC has a Kerberos service principal (SPN ) for each node of the form `primary/<FQDN>@<REALM>`.
4. Ensure each node has a keytab containing the SPN for that node. This must be located at an identical file path on all Redpanda nodes. Default is `/var/lib/redpanda/redpanda.keytab`.

### Enable Kerberos

1. If the keytab isn't in the default location, set the location.
2. Define the primary of the Kerberos service principal (SPN) to be used by Redpanda with the given keytab. Default is `redpanda`.
3. Set `sasl_kerberos_principal_mapping`. This maps Kerberos user principals (UPNs) onto Redpanda principals used in the ACLs.

2023-01-29 19:31 UTC, micheleRP commented on docs/manage/security/authentication.mdx
> +  For information about the rules, see the [Kafka documentation](https://kafka.apache.org/documentation/#security_authz_sasl).
Thank you, @michael-redpanda, @BenPope, and @dcoded! I've incorporated your feedback. Please give this another review!

2023-01-30 13:32 UTC, BenPope commented on docs/manage/security/authentication.mdx
>  When you run a command with SASL authentication, you must include the mechanism with the following flag:
```suggestion
:::note
rpk supports SASL/SCRAM, but not SASL/GSSAPI.
:::

When you run an rpk command with SASL/SCRAM, you must include the mechanism with the following flag:
```

2023-01-30 13:36 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +SASL provides authentication, but not encryption. You can, however, configure TLS to only handle encryption, and use SASL for authentication. This is useful if you require flexibility in your authori
```suggestion
SASL provides authentication, but not encryption. You can additionally configure TLS to handle encryption.
```

2023-01-30 13:37 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +You configure Kerberos authentication using a keytab, which contains the user credentials.
```suggestion
You configure Kerberos authentication using a keytab, which contains credentials for the service.
```

2023-01-30 13:50 UTC, michael-redpanda requested changes

2023-01-30 13:50 UTC, michael-redpanda commented on docs/manage/security/authentication.mdx
> +  ```
Do we want to call out what part of the `SPN` this is?  Or are we assuming the administrator knows what this is?

2023-01-30 13:50 UTC, michael-redpanda commented on docs/manage/security/authentication.mdx
> +  Examples of a Kerberos UPN without a host (`jdoe`) and with a host (`jdoe/host`):
```suggestion
  Examples of a Kerberos UPN without a host (`jdoe@EXAMPLE.COM`) and with a host (`jdoe/host@EXAMPLE.COM`):
```

2023-01-30 13:50 UTC, michael-redpanda commented on docs/manage/security/authentication.mdx
> +  | Translation | jdoe | jdoe/host |
```suggestion
  | Translation | jdoe@EXAMPLE.COM | jdoe/host@EXAMPLE.COM |
```

2023-01-30 14:39 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +  ```
From Prerequisites:

> Ensure that the KDC has a valid Kerberos service principal name (SPN) for each node in the form primary/<FQDN>@<REALM>.

Improvements welcome.

2023-01-30 16:53 UTC, michael-redpanda commented on docs/manage/security/authentication.mdx
> +  ```
I think that's fine.

2023-01-30 16:55 UTC, michael-redpanda commented on docs/manage/security/authentication.mdx
> +  ² Rule does not match because there is one component in principal name `jdoe@YOUR-REALM.COM`.
My apologies, I missed these two.

```suggestion
  ¹ Rule does not match because there are two components in principal name `jdoe/host@EXAMPLE.COM`.

  ² Rule does not match because there is one component in principal name `jdoe@EXAMPLE.COM`.
```

2023-01-30 16:55 UTC, michael-redpanda commented on docs/manage/security/authentication.mdx
> +      * If this matches, then a string is formed from `string`, substituting the realm of the principal for `$0` and the `n`’th component of the principal for `$n`. (For example, if the principal is
```suggestion
      * If this matches, then a string is formed from `string`, substituting the realm of the principal for `$0` and the `n`’th component of the principal for `$n`. (For example, if the principal is `johndoe/admin@realm.com`, then `[2:$2$1foo]` results in the string `adminjohndoefoo`.)
```

2023-01-30 18:49 UTC, micheleRP commented on docs/manage/security/authentication.mdx
> +      * If this matches, then a string is formed from `string`, substituting the realm of the principal for `$0` and the `n`’th component of the principal for `$n`. (For example, if the principal is
fixed, thanks @michael-redpanda!

2023-01-30 18:49 UTC, micheleRP commented on docs/manage/security/authentication.mdx
> +  ² Rule does not match because there is one component in principal name `jdoe@YOUR-REALM.COM`.
fixed

2023-01-30 19:08 UTC, michael-redpanda approved these changes

2023-02-01 02:42 UTC, Deflaimun commented
Branch updated with the latest from dev and label for 23.1

2023-02-01 13:55 UTC, JakeSCahill reviewed
Some comments and suggestions for your consideration.

2023-02-01 13:55 UTC, JakeSCahill commented on docs/manage/security/authentication.mdx
> +Simple Authentication Security Layer (SASL) is a framework that lets the user choose the authentication mechanism. The mechanism determines which authentication flow the client uses for that user/pas
```suggestion
Simple Authentication Security Layer (SASL) is a framework that lets you choose the authentication mechanism. The mechanism determines which authentication flow the client uses for that user/password. Redpanda supports the following authentication mechanisms:

- GSSAPI (Kerberos)
- SCRAM (Salted Challenge Response Authentication Mechanism)
```

2023-02-01 13:55 UTC, JakeSCahill commented on docs/manage/security/authentication.mdx
>  To configure SASL authentication for the Kafka API, set `authentication_method` of the listener to `sasl`.
```suggestion
To configure SASL authentication for the Kafka API, set the `authentication_method` property of the listener to `sasl`. 
```

2023-02-01 13:55 UTC, JakeSCahill commented on docs/manage/security/authentication.mdx
> +SASL provides authentication, but not encryption. You can additionally configure TLS to handle encryption.
```suggestion
SASL provides authentication, but not encryption. To provide encryption, you can enable TLS in addition to SASL.
```

2023-02-01 13:55 UTC, JakeSCahill commented on docs/manage/security/authentication.mdx
> +   $ rpk cluster config get sasl_mechanisms
```suggestion
```

2023-02-01 13:55 UTC, JakeSCahill commented on docs/manage/security/authentication.mdx
> +   $ rpk cluster config get sasl_mechanisms
This is the command to run, not the output.

Consider:

1. Append the list of allowed SASL mechanisms that clients can use to authenticate against the Kafka API.

    To get the list of all allowed SASL mechanisms, run the following:
  
    ```bash
    rpk cluster config get sasl_mechanisms
    ```

   <details>
   <summary>
   Example output
   </summary>

    In this case, Redpanda currently supports only SCRAM:
  
    ```
     SCRAM
     ```

     </details>

2023-02-01 13:55 UTC, JakeSCahill commented on docs/manage/security/authorization.mdx
> +This command creates a single SASL/SCRAM user with the given password, and optionally with a custom mechanism. The mechanism determines which authentication flow the client uses for this user/passwor
```suggestion
This command creates a single SASL/SCRAM user with the given password, and optionally with a custom mechanism. The mechanism determines which authentication flow the client uses for this user/password. Redpanda rpk supports the following mechanisms: `SCRAM-SHA-256` (default) and `SCRAM-SHA-512`, which is the same flow but uses sha512. To use GSSAPI, see [Enable Kerberos](../../security/authentication/#enable-kerberos).
```

2023-02-01 13:55 UTC, JakeSCahill commented on docs/manage/security/authorization.mdx
> +This command creates a single SASL/SCRAM user with the given password, and optionally with a custom mechanism. The mechanism determines which authentication flow the client uses for this user/passwor
We already describe which mechanisms are supported at the start of the doc:

'SCRAM provides strong encryption for user names and passwords by default and does not require an external data store for user information. Redpanda supports  `SCRAM-SHA-256` and `SCRAM-SHA-512`.'

Do we need to provide them again? Or can we single-source the list?

2023-02-01 20:41 UTC, micheleRP commented on docs/manage/security/authentication.mdx
> +   $ rpk cluster config get sasl_mechanisms
thanks Jake!

2023-02-02 19:58 UTC, micheleRP commented
@BenPope, @michael-redpanda, @dcoded: I just noticed this comment in the 23.1 slide deck: https://docs.google.com/presentation/d/1RwJy-cYFj8kT4NubYmqyl-ggVj8n3aOiRz8_NhI2R_w/edit#slide=id.g1d94adbc755_0_0. Is that page up to date? Please let me know of any limitations we should document!

2023-02-02 20:38 UTC, micheleRP commented
> @BenPope, @michael-redpanda, @dcoded: I just noticed this comment in the 23.1 slide deck: https://docs.google.com/presentation/d/1RwJy-cYFj8kT4NubYmqyl-ggVj8n3aOiRz8_NhI2R_w/edit#slide=id.g1d94adbc755_0_0. Is that page up to date? Please let me know of any limitations we should document!

Thanks @BenPope and @dcoded for the feedback on slack! I made some updates to the Authentication and Authorization pages. Please let me know if it needs anything more!

2023-02-06 14:34 UTC, BenPope commented on docs/manage/security/authentication.mdx
> +3. Set `sasl_kerberos_principal_mapping`. This maps Kerberos user principal names (UPNs) onto Redpanda principals used in the ACLs. For example:
Added a new configuration parameter in https://github.com/redpanda-data/redpanda/pull/8609
~~~suggestion
1. If the keytab is not in the default location, then set its location:

  ```bash   
  rpk cluster config set sasl_kerberos_keytab <path>
  ```

2. If the krb5.conf file is not in the default location, then set its location:

  ```bash   
  rpk cluster config set sasl_kerberos_config <path>
  ```

3. Define the primary of the Kerberos SPN to be used by Redpanda with the given keytab. Default is `redpanda`.

  ```bash
  rpk cluster config set sasl_kerberos_principal <name>
  ```

4. Set `sasl_kerberos_principal_mapping`. This maps Kerberos user principal names (UPNs) onto Redpanda principals used in the ACLs. For example:
~~~

2023-02-06 23:23 UTC, Feediver1 commented on docs/manage/security/authentication.mdx
> +1. Ensure that host names are fully qualified domain names (FQDN).
Must users satisfy the prereqs here in order? If nit, use bullets instead of numbered steps.

2023-02-06 23:30 UTC, Feediver1 commented on docs/manage/security/authentication.mdx
> +      * If this matches, then a string is formed from `string`, substituting the realm of the principal for `$0` and the `n`’th component of the principal for `$n`. (For example, if the principal is
What is "this" here? Name it.

2023-02-06 23:33 UTC, Feediver1 commented on docs/manage/security/authentication.mdx
> +      * If this matches, then a string is formed from `string`, substituting the realm of the principal for `$0` and the `n`’th component of the principal for `$n`. (For example, if the principal is
Also, ..."a string is formed from `string`, ... I had to reread this a few times. Can it be worded more clearly? A string forms a string?

2023-02-06 23:36 UTC, Feediver1 commented on docs/manage/security/authentication.mdx
> +   * `RULE:[n:string](regexp)s/pattern/replacement/g/c` where:
I don't see a description/definition of `g` and `c` here anywhere...they are mentioned below, but I have no idea what they represent in the rule.

2023-02-06 23:37 UTC, Feediver1 commented on docs/manage/security/authentication.mdx
> +   * `RULE:[n:string](regexp)s/pattern/replacement/g/c` where:
Is `g` an indicator that the update is global then?

2023-02-06 23:38 UTC, Feediver1 commented on docs/manage/security/authentication.mdx
> +   * `RULE:[n:string](regexp)s/pattern/replacement/g/c` where:
Think I see now, but had to read the following bullets first.

2023-02-06 23:39 UTC, Feediver1 commented on docs/manage/security/authentication.mdx
> +  The first rule that matches is used to extract a principal.
Kind gets lost in the footnotes--seems like an important point.

2023-02-06 23:40 UTC, Feediver1 commented on docs/manage/security/authentication.mdx
> +  In this case, Redpanda currently supports only SCRAM:
```suggestion
  In this case, Redpanda supports only SCRAM:
```
The content should be accurate for the current release, so that adverb is not necessary here.

2023-02-06 23:42 UTC, Feediver1 commented on docs/manage/security/authentication.mdx
> +If you're configuring authentication for the first time, you may need to configure [ACLs](../../security/authorization#acls) before users can access Redpanda resources.
Hmmm...you may need, so you may not need to as well? If they absolutely need to configure ACLs first, then say that. If not, under what circumstances would the user not need to configure ACLs upon the first configuration of AuthN?

2023-02-06 23:47 UTC, Feediver1 commented on docs/manage/security/authorization.mdx
>  Here are the local flags:
Note that the heading rows in the tables in these sections do not use bold text - they should:
https://deploy-preview-1005--redpanda-documentation.netlify.app/docs/manage/security/authorization/#list-and-delete-acls
https://deploy-preview-1005--redpanda-documentation.netlify.app/docs/manage/security/authorization/#user

2023-02-06 23:48 UTC, Feediver1 commented on docs/manage/security/authorization.mdx
>  Here are the local flags:
There appear to be others as well. The heading row text should be in boldface font.

2023-02-06 23:50 UTC, Feediver1 approved these changes
There are a couple of confusing sentences/wording here, which I've marked. Please review suggestions and implement as you see fit. Anything you need technical/further guidance on can be added in a separate PR before GA.

2023-02-07 00:07 UTC, micheleRP commented on docs/manage/security/authorization.mdx
>  Here are the local flags:
gah! Tables in this page are all in the old format: 
<table>
<tbody>
<tr>
<td>Flag</td>
<td>Description</td>
<td>Supported Value</td>

2023-02-07 00:49 UTC, micheleRP commented on docs/manage/security/authentication.mdx
> +   * `RULE:[n:string](regexp)s/pattern/replacement/g/c` where:
I clarified this.

2023-02-07 01:02 UTC, micheleRP commented
merging to get this into the Beta branch for beta customers: https://docs.redpanda.com/docs/next/home/. We'll address open comments and new new feedback in a separate PR.

2023-02-07 01:03 UTC, merged

2023-02-07 02:03 UTC, Deflaimun commented
The content of this PR will be published by https://github.com/redpanda-data/documentation/pull/1171