Document cluster wide rate limits for 23.1
redpanda-data/documentation pull request #1140
Opened 2023-02-01 23:17 UTC by shorgi

Fixes:
- #807

2023-02-02 22:22 UTC, Deflaimun commented on docs/manage/cluster-maintenance/index.mdx
> +- [Manage Throughput](../cluster-maintenance/manage-throughput.mdx)
Avoid using file extensions in links

2023-02-02 23:31 UTC, dlex commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +- By default, all of the listed properties are disabled and no throughput limits or quota balancing are applied. You must manually set them to enable throughput limits and quota balancing.
> By default, all of the listed properties are disabled

This is not quite true. By default, only `kafka_throughput_limit_node_in_bps` and `kafka_throughput_limit_node_out_bps` are disabled (and therefore no throughput limits or quota balancing are applied). The default values of the rest are set in a way so that if `kafka_throughput_limit_node_*_bps` is enabled, the TP limiting will start to work immediately, although some fine tuning of other properties may still be required.

2023-02-02 23:31 UTC, dlex commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +- [kafka_quota_balancer_min_shard_throughput_ratio](../../../reference/cluster-properties#kafka_quota_balancer_min_shard_throughput_ratio):	the lowest value of the throughput quota a shard can get in
> while one means

nit: it's easy to confuse numeral 'one' to pronoun 'one' in this context

2023-02-02 23:31 UTC, dlex commented on docs/reference/cluster-properties.mdx
> +The period at which the intra-node throughput quota balancer runs. If `0`, the balancer is disabled and all throughput quotas are immutable.
If it takes longer for the balancer to complete a single balancing step than the period this property specifies, then the actual period will be more than configured here.

2023-02-02 23:31 UTC, dlex commented on docs/reference/cluster-properties.mdx
> +
This paragraph can be repeated for both `kafka_quota_balancer_min_shard_throughput_ratio` and 'kafka_quota_balancer_min_shard_throughput_bps`:

Both `kafka_quota_balancer_min_shard_throughput_ratio` and 'kafka_quota_balancer_min_shard_throughput_bps` can be specified at the same time. In this case, balancer will not decrease effective shard quota below the largest bps value of each of these two properties.

2023-02-02 23:31 UTC, dlex commented on docs/reference/cluster-properties.mdx
> +If `0`, the minimum is disabled. If `1`, no quota can be taken away by the balancer.
In fact, balancer won't be able to balance anything if the value of this property is `1 / number of shards (cores)` or more.

2023-02-02 23:31 UTC, dlex commented on docs/reference/cluster-properties.mdx
> +**Range**: [number of available CPU cores, ...]
Great catch, the technical minimum should be 1 actually. Please put '1' here, I will change that in the code soon.

2023-02-03 01:21 UTC, Feediver1 commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +- [kafka_quota_balancer_min_shard_throughput_ratio](../../../reference/cluster-properties#kafka_quota_balancer_min_shard_throughput_ratio):	the lowest value of the throughput quota a shard can get in
@dlex Our style is that for 1 - 9, we spell out the numbers. For numbers greater than 9, we use the numeral. This is pretty standard: https://vectorizedio.atlassian.net/wiki/spaces/DOC/pages/92635182/Redpanda+Documentation+Style+Guide#Numbers

2023-02-04 00:16 UTC, Feediver1 commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +<ManageThroughputIntro/>
Perhaps:
This topic describes how to manage the throughput of Kafka traffic at the cluster level using configurable properties that limit and protect the use of disk and network resources for individual nodes and for an entire cluster. It also explains how to set node-wide throughput limits and quotas for intra-node (inter-shard) traffic.

2023-02-04 00:17 UTC, Feediver1 commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +The network bandwidth and disk utilization of cluster nodes may be overloaded by clients that consume throughput without limits. To prevent resource overloading caused by unconstrained throughput, Re
```suggestion
The network bandwidth and disk utilization of cluster nodes may be overloaded by clients that consume throughput without limits. To prevent resource overloading caused by unconstrained throughput, Redpanda provides runtime-configurable properties that limit and balance throughput of Kafka API traffic. 
```

2023-02-04 00:21 UTC, Feediver1 commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +To manage the volume of traffic going through a node, Redpanda implements a throughput quota balancer to enforce node-wide throughput rate limits. The throughput quota accounts for all Kafka API traf
```suggestion
To manage the volume of traffic going through a node, Redpanda implements a throughput quota balancer to enforce node-wide throughput rate limits. The throughput quota accounts for all Kafka API traffic going in and out of a node. The balancer has configurable rate limits for total ingress and egress traffic. To distribute the throughput quota, the balancer periodically monitors the throughput rate of a node's shards, and it distributes quota to the shards that can accept it. The balancer determines a dynamically changing default quota per shard. Each shard has a minimum throughput quota value, which is configurable both as a percentage of the default quota and as an absolute rate limit. 
```

2023-02-04 00:22 UTC, Feediver1 commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +To manage the volume of traffic going through a node, Redpanda implements a throughput quota balancer to enforce node-wide throughput rate limits. The throughput quota accounts for all Kafka API traf
Not sure if this changes the meaning but it makes more sense to me worded this way. Of course, your call.

2023-02-04 00:26 UTC, Feediver1 commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +- [kafka_throughput_limit_node_in_bps](../../../reference/cluster-properties#kafka_throughput_limit_node_in_bps): a node's total throughput limit for ingress traffic.
Wondering if these might be easier to view/consume in table format? Thoughts?

2023-02-04 00:29 UTC, Feediver1 commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +- By default, both kafka_throughput_limit_node_in_bps and kafka_throughput_limit_node_out_bps are disabled, so no throughput limits or quota balancing are applied. You must manually set them to turn
```suggestion
- By default, both `kafka_throughput_limit_node_in_bps` and `kafka_throughput_limit_node_out_bps` are disabled, so no throughput limits or quota balancing are applied. You must manually set them to turn on quota balancing.
```

2023-02-04 00:29 UTC, Feediver1 commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +- kafka_quota_balancer_min_shard_throughput_bps doesn't override the kafka_throughput_limit_node_in_bps and kafka_throughput_limit_node_out_bps limit settings. Consequently, the value of
```suggestion
- `kafka_quota_balancer_min_shard_throughput_bps` doesn't override the `kafka_throughput_limit_node_in_bps` and `kafka_throughput_limit_node_out_bps` limit settings. Consequently, the value of 
```

2023-02-04 00:30 UTC, Feediver1 commented on docs/reference/cluster-properties.mdx
> +Both kafka_quota_balancer_min_shard_throughput_ratio and [kafka_quota_balancer_min_shard_throughput_bps](#kafka_quota_balancer_min_shard_throughput_bps) can be specified at the same time. In this cas
```suggestion
Both `kafka_quota_balancer_min_shard_throughput_ratio` and [kafka_quota_balancer_min_shard_throughput_bps](#kafka_quota_balancer_min_shard_throughput_bps) can be specified at the same time. In this case, the balancer will not decrease the effective shard quota below the largest bps value of each of these two properties.
```

2023-02-04 00:31 UTC, Feediver1 commented on docs/reference/cluster-properties.mdx
> +kafka_quota_balancer_min_shard_throughput_bps doesn't override the limit settings, [kafka_throughput_limit_node_in_bps](#kafka_throughput_limit_node_in_bps) and [kafka_throughput_limit_node_out_bps](
Rather than mark each time, I'm just wondering why some properties are not formatted with backticks?

2023-02-04 00:33 UTC, Feediver1 approved these changes
Take a look at the suggestions.

2023-02-06 21:17 UTC, dlex commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +Redpanda's [thread-per-core model](../../../get-started/architecture#thread-per-core-model) necessitates inter-shard (intra-node) communication channels. A proper balancing of throughput for all intr
> inter-shard (intra-node) communication channels. A proper balancing of throughput for all intra-node channels 

This still keeps confusing me if I put myself in the shoes of a customer reading this. If "intra-node channels" are actually "inter-shard channels", assuming that this is an abstraction of a communication that happens between different shards inside a redpanda node, then this has nothing to do with kafka API thoughput limiting. Then, if the sentence goes on about throttling, is that the throttling of inter-shard communications assumingly? But there is no throttling of that kind in redpanda.

It may be easier to replace this paragraph?

2023-02-06 21:50 UTC, dlex requested changes
Great work overall. I think we need to work a little bit on certain definitions to avoid confusing the readers... please see my comments.

2023-02-06 21:50 UTC, dlex commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +- [max_kafka_throttle_delay_ms](../../../reference/tunable-properties#max_kafka_throttle_delay_ms): when throttling down throughput for a shard, this is the maximum duration that the balancer withhol
> this is the maximum duration that the balancer withholds allocating quota to it

I'm sorry but I could not understand what that means.

Throttling (down) is implemented as a delay introduced in the data path of API requests. If the current thoughput exceeds the current quota on a shard, processing of further requests will be delayed so that the throughput is kept within quota limits. This parameter sets the maximum duration for such delays. It exists because cleints may decide that a request has timed out if it has been delayed for too long; so for example if the request timeout period is 30s from client's perspective, it makes sense to set this parameter to e.g. 20s, so that the timeout is never hit.

2023-02-06 21:50 UTC, dlex commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +- By default, both kafka_throughput_limit_node_in_bps and kafka_throughput_limit_node_out_bps are disabled, so no throughput limits or quota balancing are applied. You must manually set them to turn
> so no throughput limits or quota balancing are applied

It's safer to say only "no throughput limits are applied". Technically, the balancer still runs, although that does not matter if the limits are not applied.

2023-02-06 21:50 UTC, dlex commented on docs/manage/cluster-maintenance/shared/_intro-manage-throughput.mdx
> +Manage the throughput of Kafka traffic at the cluster level, with configurable properties that limit and protect the use of disk and network resources for individual nodes and for an entire cluster.
> (inter-shard) traffic

Limits/quotas for inter-shard traffic (a traffic going from one shard to another) do not exist in redpanda. Consider:

"Set node-wide throughput limits for Kafka APIs traffic."

2023-02-06 21:50 UTC, dlex commented on docs/reference/cluster-properties.mdx
> +If set to `0.0`, the minimum is disabled. If set to greater than `1.0 / <number-of-shards>`, the balancer won't need to balance anything, as each shard is assigned an equal minimum and together they
> If set to greater than `1.0 / <number-of-shards>`, the balancer won't need to balance anything, as each shard is assigned an equal minimum and together they sum up to at least `1.0`.

I think what we should emphasize here is that in this case, the balancer will not be able to give more quotas to shards that actually need it (because it can't borrow any bit of quota from any shard to give it to others), and that this setting is effectively equal to disabling the balanacer. The "won't need to balance" gives a sense that this is the right way of configuring it, while it's actually the opposite.

2023-02-06 21:50 UTC, dlex commented on docs/reference/tunable-properties.mdx
> +The maximum throttle delay for Kafka responses. Used as a fail-safe when throttle values for request-responses are not set. Also used by the [throughput quota balancer](../../manage/cluster-maintenan
> Used as a fail-safe when throttle values for request-responses are not set.

I'm not sure what this sentence talks about... what are the "values for request-responses"?

Please see my other comment about this property.

2023-02-07 01:19 UTC, shorgi commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +Redpanda's [thread-per-core model](../../../get-started/architecture#thread-per-core-model) necessitates inter-shard (intra-node) communication channels. A proper balancing of throughput for all intr
It was my (mis)understanding that intra-core == inter-shard channels. I think it's still useful to bridge the high-level thread-per-core model to the per-core quota limits, so I'll rewrite this accurately, without "inter-shard channels."

2023-02-07 01:19 UTC, shorgi commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +- [kafka_throughput_limit_node_in_bps](../../../reference/cluster-properties#kafka_throughput_limit_node_in_bps): a node's total throughput limit for ingress traffic.
Will create tables

2023-02-07 01:52 UTC, shorgi commented on docs/reference/tunable-properties.mdx
> +The maximum throttle delay for Kafka responses. Used as a fail-safe when throttle values for request-responses are not set. Also used by the [throughput quota balancer](../../manage/cluster-maintenan
The "values for request-responses" was from interpreting the commit msg for the property (b98d5d97ef31d00391bf58b3e2536b8748c6b375). I'll definitely rewrite "request-responses" since it doesn't make sense to you, an SME.

2023-02-07 05:39 UTC, dlex requested changes

2023-02-07 05:39 UTC, dlex commented on docs/reference/tunable-properties.mdx
> +The maximum delay inserted in the data path of Kafka API requests to throttle them down. Enables a configurable request timeout so that it can be less than (fit within) the request timeout(s) of your
```suggestion
The maximum delay inserted in the data path of Kafka API requests to throttle them down. Ensures that responses to Kafka API calls will not be delayed beyond the timeout set by your Kafka client because of throttling.
```

2023-02-07 05:44 UTC, shorgi commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +  <meta name="title" content="Manage Throughput | Redpanda Docs" />
Will fix

2023-02-07 18:55 UTC, dlex reviewed
It's much better now technically, however I strongly advise you to check out my suggestion for the manage-thoughput paragraphs; I have tried to remove remaining confusion points and connect some unconnected lines in those paragraphs there.

2023-02-07 18:55 UTC, dlex commented on docs/manage/cluster-maintenance/manage-throughput.mdx
> +To manage the volume of traffic going through a node, Redpanda implements a throughput quota balancer to enforce node-wide throughput rate limits. The throughput quota accounts for all Kafka API traf
```suggestion
The network bandwidth and disk utilization of cluster nodes may be overloaded by clients that produce or consume throughput without limits. To prevent resource overloading caused by unconstrained throughput, Redpanda provides runtime-configurable properties that limit and balance throughput of Kafka API traffic.

To manage the volume of traffic going through a node, Redpanda implements throughput quotas on ingress and egress side of every node. The throughput quota accounts for all Kafka API traffic going in or out of a node, with the value of quota representing the allowed rate of data passing through in one direction. When a connection is in breach of the quota, the throttler advises the client about the delay that would bring the rate back to the allowed level, and implements that delay before handling Kafka API requests. There are configurable rate limits for node total ingress and egress traffic to control the quotas.

With Redpanda's [thread-per-core model](../../../get-started/architecture#thread-per-core-model), the Kafka API traffic to and from a client connection is processed by a single core (shard). In order to manage thoughput quotas efficiently, node quotas are distributed between shards, and each per-shard quota is in turn shared by all connections served by the shard. The job of splitting node quota between shards in an optimal way is done behind the scenes by the component called quota balancer.

To distribute the node throughput quota, the balancer periodically monitors the throughput rate of a node's shards, and it distributes more quota to the shards that can make better use of it than the others. Each shard has a minimum throughput quota value, which is configurable both as a percentage of the default quota and as an absolute rate limit. 
```

2023-02-07 18:55 UTC, dlex commented on docs/reference/cluster-properties.mdx
> +`kafka_throughput_limit_node_in_bps / kafka_throughput_limit_node_out_bps` can result in lesser throughput than kafka_quota_balancer_min_shard_throughput_bps.
Same concern about the division sign, and also one unquoted property name appearence.

2023-02-07 18:55 UTC, dlex commented on docs/reference/tunable-properties.mdx
> +The maximum delay inserted in the data path of Kafka API requests to throttle them down. Ensures that responses to Kafka API calls will not be delayed beyond the timeout set by your Kafka client beca
I've read this sencence again and realized that it's unclear whether the responses won't be delayed because of throttling, or the timeout is set because of throttling. The correct is the former; could you please try to restructure it to make that clear?

2023-02-08 23:04 UTC, dlex approved these changes
Great work!

2023-02-08 23:12 UTC, merged