docs:#1218 update ABS feedback from Beta
redpanda-data/documentation pull request #1223
Opened 2023-02-14 02:19 UTC by micheleRP

resolves #1218 

preview:

2023-02-14 17:34 UTC, shorgi approved these changes

2023-02-16 22:16 UTC, mattschumpert requested changes

2023-02-16 22:16 UTC, mattschumpert commented on docs/manage/tiered-storage.mdx
> +- See the Microsoft documentation for information about Azure network security and how to [grant access from an internet IP range](https://learn.microsoft.com/en-us/azure/storage/common/storage-netwo
@micheleRP  let's add

'If it is necessary to open additional routes/ports between your broker nodes and Azure Blob Storage  (for example, in a hybrid cloud deployment), see the Microsoft documentation ...'

2023-02-17 01:40 UTC, micheleRP commented
replacing with #1257, so this update only goes in beta version

2023-02-17 01:40 UTC, closed without merging