docs: Document the new LoadBalancer deployment option
redpanda-data/documentation pull request #1350
Opened 2023-03-08 10:30 UTC by JakeSCahill

2023-03-13 16:14 UTC, shorgi reviewed
Minor comments before SME review

2023-03-13 16:14 UTC, shorgi commented on sidebars.js
> +                        label: "Use a Custom Service",
Parallelism with `Use LoadBalancer Services`?

```suggestion
                        label: "Use Custom Services",
```

2023-03-13 16:14 UTC, shorgi commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +When the `external.type` field is set to `LoadBalancer`, the Helm chart creates one LoadBalancer Service for each replica in the StatefulSet. Each LoadBalancer routes external traffic to the listener
The updated content doesn't have a descriptive summary about the purpose of this topic that the removed sentence did.

```suggestion
Expose your Redpanda cluster to clients outside of your Kubernetes cluster by using LoadBalancer Services.

When the `external.type` field is set to `LoadBalancer`, the Helm chart creates one LoadBalancer Service for each replica in the StatefulSet. Each LoadBalancer routes external traffic to the listener ports on a single Redpanda broker.
```

2023-03-13 16:14 UTC, shorgi commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +- One worker node for each Redpanda broker that you want to deploy.
`Run`, `create`, `use` one worker node?

```suggestion
- Run one worker node for each Redpanda broker that you want to deploy.
```

2023-03-16 16:10 UTC, shorgi reviewed
Pre SME review comments

2023-03-16 16:10 UTC, shorgi commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +![A client connects to a Pod directly through a load balancer](./loadbalancer.png)
Skimming `A client connects to a Pod directly` could be misunderstood as there being nothing between the external client and Pod. Removing `directly` prevents that misunderstanding and preserves the intended meaning:

  ```suggestion
![A client connects to a Pod through a load balancer](./loadbalancer.png)
```

2023-03-21 23:43 UTC, vuldin requested changes
I've requested a few changes, please let me know if you have any questions. I still haven't completed reviewing the changes to `configure-external-access-nodeport.mdx`, but I will finish that in the near future. I just wanted to get this out ASAP.

2023-03-21 23:43 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +You can configure each Redpanda broker to advertise the DNS name or IP address of its corresonding load balancer instance.
```suggestion
You may not know your LoadBalancer services' addresses prior to deployment. In this case, you can configure each Redpanda broker to advertise the DNS name or IP address of its corresponding load balancer resource. This requires an initial deployment step followed by a deployment upgrade that updates the advertised listener.
```

2023-03-21 23:43 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +If your cluster has TLS enabled, you must [advertise custom domains](#advertise-custom-domains) because the Helm charts adds only custom domains to the SAN list of TLS certificates, not IP addresses.
```suggestion
If your cluster has TLS enabled, you must [advertise custom domains](#advertise-custom-domains) because the helm chart only adds custom domains to the SAN list of TLS certificates (not IP addresses).

If your LoadBalancer services have IP addresses assigned rather than DNS names, then you must make those IP addresses resolvable by DNS names for secure TLS access. For development purposes, adding `/etc/hosts` entries will work. But for production you will need to update your organization's DNS service.
```

2023-03-21 23:43 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +    enabled: true
```suggestion
```

2023-03-21 23:43 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +
```suggestion
```

2023-03-21 23:43 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +1. Make sure that your managed Kubernetes platform assigned external addresses to your LoadBalancer Services:
```suggestion
1. Make sure that Kubernetes assigned external addresses to your LoadBalancer services:
```

2023-03-21 23:43 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +    --set tls.enabled=false
```suggestion
  helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
    --set external.enabled=true \
    --set external.type=LoadBalancer \
    --set tls.enabled=false \
    --wait
```

2023-03-21 23:43 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +    --values loadbalancer-tls-disabled.yaml --reuse-values
```suggestion
  helm upgrade --install redpanda redpanda/redpanda -n redpanda --create-namespace \
    --values loadbalancer-tls-disabled.yaml --reuse-values --wait
```

2023-03-21 23:43 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +
Lines 348 to 434 (this line) can be removed, as LoadBalancer services don't require any knowledge or configuration regarding the k8s nodes (so the bare metal and managed k8s sections can be a single section).

2023-03-21 23:43 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +  helm upgrade redpanda redpanda/redpanda -n redpanda --set $(kubectl get svc -n redpanda -o jsonpath='{"external.addresses={"}{ range .items[*]}{.status.loadBalancer.ingress[0].ip }{.status.loadBala
```suggestion
  helm upgrade redpanda redpanda/redpanda -n redpanda --set $(kubectl get svc -n redpanda -o jsonpath='{"external.addresses={"}{ range .items[*]}{.status.loadBalancer.ingress[0].ip }{.status.loadBalancer.ingress[0].hostname}{","}{ end }{"}\n"}') --reuse-values --wait
```

2023-03-21 23:45 UTC, vuldin commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +If your cluster has TLS enabled, you must [advertise custom domains](#advertise-custom-domains) because the Helm charts adds only custom domains to the SAN list of TLS certificates, not IP addresses.
This makes it more clear that you can still use TLS if your LoadBalancer services have an IP (rather than a DNS name) assigned... you just need to make that IP address resolvable by the DNS address that works with your cert.

2023-03-27 10:17 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +      type: LoadBalancer
If a user is running on a deployment that has external access disabled, they need to know to enable it for this doc to work. I think it's best to be explicit about what settings are required even if they are currently the defaults.

2023-03-27 12:07 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +
@vuldin , I found that if you're not using Managed K8s, such as EC2, you must do these manual steps.

2023-03-28 18:17 UTC, shorgi commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +For clusters with TLS enabled, advertising the DNS names or IP addresses of load balancer instances is not supported. Instead, use [custom domains](#advertise-a-custom-domain).
Redpanda has TLS enabled by default? If so, clarify here to expect to use custom domains.

2023-03-28 18:17 UTC, shorgi commented on docs/manage/kubernetes/networking/loadbalancer.png
Nit: Should the `3xxx` port numbers be `3xxxx`, to be in the thirty-thousand range of the LoadBalancer ports?

2023-03-28 18:17 UTC, shorgi commented on docs/manage/kubernetes/networking/custom-services.mdx
> +If you use a custom domain (`external.domain`), provide subdomains for each replica in `external.addresses`. This domain is appended to each subdomain (`<subdomain-for-replica-0>.<custom-domain>`).
```suggestion
If you use a custom domain (`external.domain`), provide subdomains for each replica in `external.addresses`. This custom domain is appended to each subdomain (`<subdomain-for-replica-0>.<custom-domain>`).
```

2023-03-28 18:17 UTC, shorgi commented on docs/manage/kubernetes/networking/custom-services.mdx
> +description: Stop the Helm chart from deploying default Services that provide external access. Then, either create your own Services to provide external access or leave the deployment without externa
```suggestion
description: How to configure the Helm chart to enable creating your own custom Services to provide external access to a Redpanda cluster.
```

2023-03-28 18:17 UTC, shorgi commented on docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
> +If your cluster has TLS enabled, you must [advertise custom domains](#advertise-custom-domains) because the Helm charts adds only custom domains to the SAN list of TLS certificates, not IP addresses.
This should be the same content as https://github.com/redpanda-data/documentation/pull/1350/files#:~:text=docs/manage/kubernetes/networking/configure%2Dexternal%2Daccess%2Dloadbalancer.mdx?  `For clusters with TLS enabled, advertising the DNS names or IP addresses of load balancer instances is not supported. Instead, use [custom domains](#advertise-a-custom-domain).`

2023-03-28 18:17 UTC, shorgi commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +The Helm chart adds the `spec.selector.statefulset.kubernetes.io/pod-name` setting to each LoadBalancer Service so that each one targets only one Redpanda broker. Each Pod in a StatefulSet is automat
```suggestion
The Helm chart adds the `spec.selector.statefulset.kubernetes.io/pod-name` setting to each LoadBalancer Service so that each targets only one Redpanda broker. Each Pod in a StatefulSet is automatically given the `statefulset.kubernetes.io/pod-name` label, which contains the name of the Pod. By setting the `spec.selector.statefulset.kubernetes.io/pod-name` field of the LoadBalancer Service to the name of a Pod, it makes the LoadBalancer Service target only the individual Redpanda broker and not the whole cluster.
```

2023-03-29 09:25 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
> +If your cluster has TLS enabled, you must [advertise custom domains](#advertise-custom-domains) because the Helm charts adds only custom domains to the SAN list of TLS certificates, not IP addresses.
```suggestion
If your cluster has TLS enabled (default), you must [advertise custom domains](#advertise-custom-domains) because the Helm chart adds custom domains to the SAN list of TLS certificates and not IP addresses. Therefore, IP addresses assigned to LoadBalancer Services must be made resolvable by DNS names to ensure secure TLS access.

While adding entries to the `/etc/hosts` file may work for development purposes, it's not a suitable approach for production environments. In production, you'll need to update your organization's DNS service to make the IP addresses resolvable by DNS names. Updating your organization's DNS service ensures that users can access your services securely without encountering any SSL/TLS warnings or errors.
```

2023-03-29 09:28 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +
LoadBalancer Services don't get an IP/DNS name in self-managed (bare-metal) environments.

2023-03-30 17:16 UTC, shorgi commented on docs/manage/kubernetes/networking/loadbalancer.png
To clarify, the `3xxx` ports are in this loadbalancer.png, on the right side of the`Node`block.

2023-03-30 17:17 UTC, shorgi approved these changes

2023-03-31 14:54 UTC, alejandroEsc commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +
I think @vuldin is saying that these steps belong in another place? That maybe these lines are not supposed to be here since they apply to another topic which would be baremetal envs?

2023-03-31 16:15 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +
These instructions are already within a bare-metal tab. @vuldin do you agree that we should keep these instructions?

2023-04-04 13:03 UTC, vuldin approved these changes
Thanks for making the requested changes/improvements, LGTM.

2023-04-04 15:34 UTC, merged