Audit logging samples
redpanda-data/documentation pull request #141
Opened 2023-12-01 05:14 UTC by greg-szrama

Added audit log message samples.

2023-12-01 18:50 UTC, michael-redpanda reviewed
Looks great!  I added a new field since the last time I gave you these examples so made some updates.

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +    },
FYI: New field added from when I originally gave you the schema

```suggestion
    "product": {
      "name": "Redpanda",
      // This is the Node ID of the broker that produced this audit event
      "uid": "2",
      "vendor_name": "Redpanda Data, Inc.",
      "version": "v23.3.0-dev-2457-g76dc896f8c"
    },
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +  },
```suggestion
  // This is the IP address of the Kafka broker that received the authorization request
  "dst_endpoint": {
    "ip": "127.0.0.1",
    "port": 19092,
    // Name of the Redpanda kafka server
    "svc_name": "kafka rpc protocol"
  },
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +  },
```suggestion
  // This is the IP address of the client that generated the authorization request
  "src_endpoint": {
    "ip": "127.0.0.1",
    // This is the client ID of the kafka client
    "name": "rpk",
    "port": 42906
  },
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +Redpanda's audit logs comply with the Open Cybersecurity Schema Framework (OCSF). This provides a predictable and extensible solution that works seamlessly with industry standard tools. This page agg
```suggestion
Redpanda's audit logs comply with version 1.0.0 of the Open Cybersecurity Schema Framework (OCSF) schema. This provides a predictable and extensible solution that works seamlessly with industry standard tools. This page aggregates several sample log files covering a range of scenarios.
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +    },
```suggestion
    "product": {
      "name": "Redpanda",
      "uid": "1",
      "vendor_name": "Redpanda Data, Inc.",
      "version": "v23.3.0-dev-2457-g76dc896f8c"
    },
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +    },
```suggestion
    "product": {
      "name": "Redpanda",
      "uid": "0",
      "vendor_name": "Redpanda Data, Inc.",
      "version": "v23.3.0-dev-2457-g76dc896f8c"
    },
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +          "name": "aclAuthorization"
```suggestion
        "policy": {
          "desc": "acl: {principal {type user name user} host {{any_host}} op all perm allow}, resource: type {topic} name {*} pattern {literal}",
          "name": "aclAuthorization"
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +      "version": "v23.3.0-dev-2457-g76dc896f8c"
```suggestion
    "product": {
      "name": "Redpanda",
      "uid": "0",
      "vendor_name": "Redpanda Data, Inc.",
      "version": "v23.3.0-dev-2457-g76dc896f8c"
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +    },
```suggestion
    "product": {
      "name": "Redpanda",
      "uid": "2",
      "vendor_name": "Redpanda Data, Inc.",
      "version": "v23.3.0-dev-2457-g76dc896f8c"
    },
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +    },
```suggestion
    "product": {
      "name": "Redpanda",
      "uid": "0",
      "vendor_name": "Redpanda Data, Inc.",
      "version": "v23.3.0-dev-2457-g76dc896f8c"
    },
```

2023-12-01 18:50 UTC, michael-redpanda commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +
```suggestion
Redpanda produces the following OCSF class messages:

* Authentication (3002) for all authentication events
* Application Lifecycle (6002) for when the audit system is enabled or disabled or when Redpanda starts or stops (if auditing is enabled when Redpanda starts or stops)
* API Activity (6003) for any access to the Kafka API, Admin API or Schema Registry

Please refer to the [OCSF Schema Definition](https://schema.ocsf.io/) for more information about what the fields mean for each event class.
```

2023-12-01 18:52 UTC, michael-redpanda commented
I should generate some SR events as well, but it's not a blocker imo

2023-12-04 16:29 UTC, Feediver1 commented
@greg-szrama For left navtree entries, we use init cap.
Once in a file, all headings are sentence style caps. 
Circle back to make sure your headings reflect this style. Thanks!

2023-12-05 21:38 UTC, greg-szrama commented
Incorporated feedback into the updated page, ready for review!

2023-12-06 14:39 UTC, graphcareful approved these changes

2023-12-08 01:56 UTC, Feediver1 commented
Not sure why this PR is pulling in data transforms, install beta, and other PRs. May want to check with @Deflaimun

2023-12-08 02:03 UTC, Feediver1 commented on modules/manage/pages/audit-logging.adoc
> +Many scenarios for streaming data include the need for fine-grained auditing of user activity related to the system. This is especially true for regulated industries such as finance, healthcare, and
Already reviewed this content in https://github.com/redpanda-data/docs/pull/151

2023-12-08 02:06 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> += Sample Audit Log Messages
Please revise either the navtree entry or the heading such that they match. Right now, the navtree has "Audit Log Message Examples", which is not the same as this heading.

2023-12-08 02:07 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +* API Activity (6003) for any access to the Kafka API, Admin API or Schema Registry
```suggestion
* API Activity (6003) for any access to the Kafka API, Admin API, or Schema Registry
```

2023-12-08 02:09 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +Please refer to the [OCSF Schema Definition](https://schema.ocsf.io/) for more information about what the fields mean for each event class.
```suggestion
Refer to the https://schema.ocsf.io/[OCSF Schema Definition] for the field definitions for each event class.
```

2023-12-08 02:11 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +This shows a basic scenario where an admin using rpk successfully authenticates with Redpanda. This event is an authentication type event.
```suggestion
This scenario shows how an admin using rpk successfully authenticates with Redpanda. This is an authentication type event.
```

2023-12-08 02:12 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +This illustrates a common failure scenario where an rpk user entered the wrong credentials. This is an authentication type event.
```suggestion
This scenario illustrates a common failure where a user entered the wrong credentials. This is an authentication type event.
```

2023-12-08 02:12 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +The Redpanda Kafka API offers a wide array of options for interacting with your Redpanda clusters. Here we have some messages from a few common interactions with the API.
```suggestion
The Redpanda Kafka API offers a wide array of options for interacting with your Redpanda clusters. Following are examples of messages from common interactions with the API.
```

2023-12-08 02:13 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +This illustrates an access control list update which also requires a superuser authentication. It lists the ACL edited and the updated permissions. This is a management type event.
```suggestion
This example illustrates an ACL update that also requires a superuser authentication. It lists the edited ACL and the updated permissions. This is a management type event.
```

2023-12-08 02:15 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +These illustrate some examples of audit messages related to use of the Redpanda Admin API.
```suggestion
The following examples show audit messages related to use of the Redpanda Admin API.
```

2023-12-08 02:16 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +This illustrates the log message from using the Admin API to retrieve the cluster configurations in a zipped archive. Of special note is that a user must authenticate with the superuser role to perfo
```suggestion
This example shows the log message when you use the Admin API to retrieve the cluster configurations in a zipped archive. Note that a user must authenticate with the superuser role to perform this action.
```

2023-12-08 02:16 UTC, Feediver1 commented on modules/manage/pages/audit-logging/audit-log-samples.adoc
> +Similar to the earlier example, this illustrates a user requesting cluster configurations as a zip archive. Unlike the previous example, however, the user in this case is not authorized to retrieve t
```suggestion
Similar to the previous example, this example illustrates a user requesting cluster configurations as a zip archive. Unlike the previous example, however, the user in this case is not authorized to retrieve this information.
```

2023-12-08 02:16 UTC, Feediver1 requested changes
See suggested updats

2023-12-14 20:47 UTC, Feediver1 approved these changes
lgtm!

2023-12-19 16:06 UTC, graphcareful approved these changes

2023-12-19 21:15 UTC, deniscoady approved these changes

2023-12-19 21:41 UTC, merged