add deprecation notice for data transforms
redpanda-data/documentation pull request #145
Opened 2023-12-01 20:29 UTC by Deflaimun

2023-12-01 20:39 UTC, Feediver1 commented on modules/shared/partials/data-transform-deprecation-notice.adoc
> +IMPORTANT: This feature is deprecated. For details on the new version, see https://docs.redpanda.com/beta/develop/data-transforms/[Data Transform in Beta]. To learn more about the new commands for tr
```suggestion
IMPORTANT: This feature is deprecated. For details about the latest supported version, see https://docs.redpanda.com/beta/develop/data-transforms/[Data Transform in Beta]. To learn more about the latest commands for data transform, see https://docs.redpanda.com/beta/reference/rpk/rpk-transform/rpk-transform/[rpk transform in Beta].
```

2023-12-01 20:39 UTC, Feediver1 approved these changes
Please update the note.

2023-12-01 21:57 UTC, mattschumpert requested changes
Let's not add anything to the RPK or API pages.  Let's just add a note to the Sandbox overview page pointing people to the beta, just saying we recommend they use the 23.3 beta release instead of the sandbox.

Also we can't say 'supported version' anywhere. the beta is still not supported for production.

Let's remove all of this since it gives a false impression the RPK commands and API are gone, when in fact they're all available in the beta.

All we should say is "Data Transforms has graduated from technical preview to Beta, and is available in 23.3 release of Redpanda as a beta feature. Click here for more information (link to Data Transforms 23.3 beta doc topic)"

2023-12-01 22:00 UTC, Deflaimun commented
Changed the wording to 

Data Transforms has graduated from technical preview to Beta, and is available in 23.3 release of Redpanda as a beta feature. For details , see https://docs.redpanda.com/beta/develop/data-transforms/[Data Transform in Beta]. To learn more about the latest commands for data transform, see https://docs.redpanda.com/beta/reference/rpk/rpk-transform/rpk-transform/[rpk transform in Beta].

2023-12-01 22:02 UTC, mattschumpert commented
@Deflaimun not sure about the capitalization for 'Technical Preview' and 'Beta'.  I defer to @Feediver1 . Besides that looks good

2023-12-01 22:03 UTC, mattschumpert approved these changes

2023-12-04 19:26 UTC, Feediver1 approved these changes

2023-12-04 20:34 UTC, micheleRP commented on modules/shared/partials/data-transform-graduation-notice.adoc
> +IMPORTANT: Data Transforms has graduated from technical preview to Beta, and is available in 23.3 release of Redpanda as a beta feature. For details , see https://docs.redpanda.com/beta/develop/data-
```suggestion
IMPORTANT: Data Transforms has graduated from technical preview to Beta, and is available in the 23.3 release. For details, see https://docs.redpanda.com/beta/develop/data-transforms/[Data Transform in Beta] and https://docs.redpanda.com/beta/reference/rpk/rpk-transform/rpk-transform/[`rpk transform` in Beta].
```

2023-12-04 21:02 UTC, Feediver1 approved these changes
lgtm

2023-12-04 21:05 UTC, merged