docs:#1358 TS refers to properties that don't seem to exist
redpanda-data/documentation pull request #1535
Opened 2023-04-21 21:01 UTC by micheleRP

resolves #1358 

preview:

2023-04-26 15:26 UTC, micheleRP commented on docs/manage/shared/tiered-storage/_adjacent-segment-merging.mdx
>  By default, and as part of housekeeping, Redpanda runs adjacent segment merging on all segments in object storage that are smaller than the threshold. Two properties control the behavior of <ClusterP
@shorgi can you please add `cloud_storage_enable_segment_merging` to the property reference file, so we can link on this page?

2023-04-26 15:34 UTC, micheleRP commented on docs/manage/shared/tiered-storage/_adjacent-segment-merging.mdx
>  By default, and as part of housekeeping, Redpanda runs adjacent segment merging on all segments in object storage that are smaller than the threshold. Two properties control the behavior of <ClusterP
@shorgi also please add `cloud_storage_idle_threshold_rps`!

2023-04-26 16:20 UTC, shorgi commented on docs/manage/shared/tiered-storage/_adjacent-segment-merging.mdx
>  By default, and as part of housekeeping, Redpanda runs adjacent segment merging on all segments in object storage that are smaller than the threshold. Two properties control the behavior of <ClusterP
@micheleRP Added props in [854c429](https://github.com/redpanda-data/documentation/pull/1535/commits/854c429e1c7f2df58750773bdae8ba412a8f1a7e)

2023-04-27 04:02 UTC, mattschumpert approved these changes
Approved with 1 minor comment on the TIP

2023-04-27 04:02 UTC, mattschumpert commented on docs/manage/shared/tiered-storage/_remote-write.mdx
> +A constant stream of data is necessary to build up the log segments and roll them into object storage. To see new log segments faster, you can edit the <TunableClusterProperty name="cloud_storage_seg
@micheleRP 'exceeded the segment.bytes size or the segment.ms age'.

With 23.1 we now support segment.bytes so this is another way segments get automatically rolled.

2023-04-27 15:32 UTC, hcoyote requested changes

2023-04-27 15:32 UTC, hcoyote commented on docs/manage/shared/tiered-storage/_enable.mdx
> +Topic-level properties override cluster-level properties. For example, for new topics, if `cloud_storage_enable_remote_write` is set to `true`, you can set `redpanda.remote.write` to `false` to turn
This is a little confusing.

I think this means that you must have cloud_storage_enabled=true _and_ either 

- cloud_storage_enabled_remote_write=true to affect all topics globally
- redpanda.remote.write=true set within each topic that needs it specifically enabled.

So something like(?):

> To enable Tiered Storage support, cloud_storage_enabled must be set to true. Once this is done, you can either configure all topics globally to write to Tiered Storage or configure only specific topics. To configure this globally, set cloud_storage_enable_remote_write to true. To configure only specific topics, set redpanda.remote.write=true within each topic's configuration. 

I think cloud_storage_enabled is the feature flag that tells Redpanda it is now capable of using tiered storage, whereas the other two are the topic settings that instruct it to actually offload (whether that's globally for all topics or for individual topics)

2023-04-27 15:32 UTC, hcoyote commented on docs/manage/shared/tiered-storage/_set-retention-limits.mdx
> +For compacted topics, Redpanda compacts segments after they have been uploaded to object storage. Redpanda initially uploads all (non-compacted) segments. It then reuploads the segments with compacti
does this clean up uncompacted segments from Tiered Storage, too? As written, a reader could walk away with the idea that they may have both uncompacted and compacted segments in tiered storage.

2023-04-27 18:48 UTC, micheleRP commented on docs/manage/shared/tiered-storage/_enable.mdx
> +Topic-level properties override cluster-level properties. For example, for new topics, if `cloud_storage_enable_remote_write` is set to `true`, you can set `redpanda.remote.write` to `false` to turn
Thanks @hcoyote! I simplified the steps altogether. Please review: https://deploy-preview-1535--redpanda-documentation.netlify.app/docs/manage/tiered-storage/#enable-tiered-storage

2023-04-28 08:54 UTC, VladLazar commented on docs/manage/shared/tiered-storage/_enable.mdx
> +rpk topic alter-config <topic_name> --set redpanda.remote.write=true
nit: Pretty sure this can be just one command:
```
rpk topic alter-config <topic_name> --set redpanda.remote.read=true --set redpanda.remote.write=true
```

2023-04-28 08:54 UTC, VladLazar commented on docs/manage/shared/tiered-storage/_enable.mdx
> -#### Enable Tiered Storage for topics
I feel like this section would benefit from specifying that `cloud_storage_enable_remote_write` and `cloud_storage_enable_remote_read` are essentially creation-time defaults for the `redpanda.remote.write` and `redpanda.remote.read` topic props.

2023-04-28 08:54 UTC, VladLazar commented on docs/manage/shared/tiered-storage/_remote-write.mdx
> +A constant stream of data is necessary to build up the log segments and roll them into object storage. To see new log segments faster, you can edit the <TunableClusterProperty name="cloud_storage_seg
> does this imply that we're uploading the active segment before it's been closed and rolled? Or that TS is force rolling the segment when cloud_storage_segment_max_upload_interval_sec is also reached?

The tiered storage write path can upload active segments. A segment roll is not forced to achieve this. This will happen if `cloud_storage_segment_max_upload_interval_sec` is set, the specified interval has elapsed and all other closed segments have been uploaded.

2023-04-28 08:54 UTC, VladLazar commented on docs/manage/shared/tiered-storage/_set-retention-limits.mdx
> +You can use properties to control retention of topic data in local storage. With Tiered Storage enabled, data in local storage expires after the topic-level properties `retention.local.target.ms` or
nit: I don't know if `expires` is the right word here. I'd say `becomes eligible for deletion` instead.

2023-04-28 08:54 UTC, VladLazar commented on docs/manage/shared/tiered-storage/_set-retention-limits.mdx
>  - If `retention.local.target.ms` or `retention.local.target.bytes` is set, it is normalized and used to initialize the retention fields in `topic_properties`.
I think it refers to the fact that when local retention is performed, we will use `min(retention.bytes, retention.local.target.bytes)` and `max(retention.ms, retention.local.target.ms)`

2023-04-28 08:54 UTC, VladLazar commented on docs/manage/shared/tiered-storage/_set-retention-limits.mdx
> +For compacted topics, Redpanda compacts segments after they have been uploaded to object storage. Redpanda initially uploads all (non-compacted) segments. It then reuploads the segments with compacti
> does this clean up uncompacted segments from Tiered Storage, too?

Yes. After Redpanda performs a compacted segment re-upload, the replaced segments will eventually be deleted. This happens when cloud retention is applied, so it's not immediate.

> As written, a reader could walk away with the idea that they may have both uncompacted and compacted segments in tiered storage.

That's pretty much always the case. Compacted re-upload is done opportunistically (when there's no non-compacted uploads to perform; i.e. the entire local log has been uploaded). Hence, it's rare for all segments in the cloud to be compacted. This is perfectly fine though. The tiered storage read path knows how to handle this.

2023-04-28 15:58 UTC, micheleRP commented on docs/manage/shared/tiered-storage/_remote-write.mdx
> +A constant stream of data is necessary to build up the log segments and roll them into object storage. To see new log segments faster, you can edit the <TunableClusterProperty name="cloud_storage_seg
I've updated the [tip](https://deploy-preview-1535--redpanda-documentation.netlify.app/docs/manage/tiered-storage/#remote-write). Is this correct?
_A constant stream of data is necessary to build up the log segments and roll them into object storage. To see new log segments faster, you can edit the `segment.bytes` topic-level property. Or, you can edit the `cloud_storage_segment_max_upload_interval_sec` cluster-level property, which sets the frequency with which new segments are generated in Tiered Storage, even if the local segment has not exceeded the `segment.bytes` size or the `segment.ms` age._

2023-04-28 16:07 UTC, micheleRP commented on docs/manage/shared/tiered-storage/_set-retention-limits.mdx
>  - If `retention.local.target.ms` or `retention.local.target.bytes` is set, it is normalized and used to initialize the retention fields in `topic_properties`.
Please review this edit: 
_- If `retention.ms` or `retention.bytes` is set, Redpanda initializes the `retention.local.target.*` properties. 
- If `retention.local.target.ms` or `retention.local.target.bytes` is set, Redpanda initializes the `min(retention.bytes, retention.local.target.bytes)` and `max(retention.ms, retention.local.target.ms)` properties._

2023-04-28 21:53 UTC, hcoyote commented on docs/manage/shared/tiered-storage/_set-retention-limits.mdx
> +For compacted topics, Redpanda compacts segments after they have been uploaded to object storage. Redpanda initially uploads all (non-compacted) segments. It then reuploads the segments with compacti
> Yes. After Redpanda performs a compacted segment re-upload, the replaced segments will eventually be deleted. This happens when cloud retention is applied, so it's not immediate.

I'd call this out. This means we'd have a higher storage cost for long retention periods where compaction is also used.

2023-04-28 21:54 UTC, hcoyote approved these changes

2023-04-28 22:22 UTC, micheleRP commented on docs/manage/shared/tiered-storage/_set-retention-limits.mdx
> +For compacted topics, Redpanda compacts segments after they have been uploaded to object storage. Redpanda initially uploads all (non-compacted) segments. It then reuploads the segments with compacti
Revised to: 
_For compacted topics, Redpanda compacts segments after they have been uploaded to object storage. Redpanda initially uploads all uncompacted segments. It then reuploads the segments with compaction applied. It's likely that some segments in object storage are not compacted, but the Tiered Storage read path can manage this._

2023-05-02 14:47 UTC, VladLazar approved these changes

2023-05-02 14:47 UTC, VladLazar commented on docs/manage/shared/tiered-storage/_set-retention-limits.mdx
> +Data becomes eligible for deletion from object storage following `retention.ms` or `retention.bytes`. For example, if `retention.bytes` is set to 10 GiB, then every partition in the topic has a limit
nit: If `cleanup.policy == compact` for the topic, then we won't actually delete anything. Maybe this wording can still be improved somehow.

2023-05-02 19:28 UTC, Feediver1 commented on docs/manage/kubernetes/tiered-storage.mdx
> +:::note
This seems important...(rather than a note).

2023-05-02 21:41 UTC, micheleRP commented on docs/manage/kubernetes/tiered-storage.mdx
> +:::note
yes, good idea. I made it an important admonition.

2023-05-03 00:55 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_adjacent-segment-merging.mdx
> +By default, and as part of housekeeping, Redpanda runs adjacent segment merging on all segments in object storage that are smaller than the threshold. Two properties control the behavior of <TunableC
What is the value-add for readers when you say "as part of housekeeping"? This is run regularly? If so, at what interval?

2023-05-03 00:56 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_adjacent-segment-merging.mdx
> +- <TunableClusterProperty name="cloud_storage_segment_size_target" frontmatter={props.frontmatter}/>: This is the desired segment size in object storage. The default segment size is the local segment
```suggestion
- <TunableClusterProperty name="cloud_storage_segment_size_target" frontmatter={props.frontmatter}/>: The desired segment size in object storage. The default segment size is the local segment size for the topic, which is controlled by the <TunableClusterProperty name="log_segment_size" frontmatter={props.frontmatter}/> configuration property and the <code>segment.bytes</code> topic property. You can set the <code>cloud_storage_segment_size_target</code> property to a value larger than this default segment size, but because this triggers a lot of segment re-uploads, it's not recommended. 
```

2023-05-03 00:57 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_adjacent-segment-merging.mdx
> +- <TunableClusterProperty name="cloud_storage_segment_size_min" frontmatter={props.frontmatter}/>: This is the smallest segment size that Redpanda keeps in object storage. The default size is 50% of
```suggestion
- <TunableClusterProperty name="cloud_storage_segment_size_min" frontmatter={props.frontmatter}/>: The smallest segment size that Redpanda keeps in object storage. The default is 50% of <TunableClusterProperty name="log_segment_size" frontmatter={props.frontmatter}/>.
```

2023-05-03 00:58 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_adjacent-segment-merging.mdx
> +- Merge and reupload a segment with a size less than `cloud_storage_segment_size_min` if there are no other options (the run of small segments is followed by the large segment).
```suggestion
- Merge and re-upload a segment with a size up to `cloud_storage_segment_size_target`.
- Merge and re-upload a segment with a size less than `cloud_storage_segment_size_min` if there are no other options (the run of small segments is followed by the large segment).
```

2023-05-03 01:00 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_adjacent-segment-merging.mdx
> +Suppose the <TunableClusterProperty name="cloud_storage_segment_max_upload_interval_sec" frontmatter={props.frontmatter}/> property is set and the partition contains a large number of small segments.
```suggestion
Suppose the <TunableClusterProperty name="cloud_storage_segment_max_upload_interval_sec" frontmatter={props.frontmatter}/> property is set and the partition contains a large number of small segments. For example, if `cloud_storage_segment_max_upload_interval_ms` is set to 10 minutes and the produce rate is 1 MiB per minute, then Redpanda uploads a new 10 MiB segment every 10 minutes. If adjacent segment merging is enabled and `cloud_storage_segment_size_target` is set to 500 MiB, then every 50 segments are re-uploaded as one large 500 MiB segment. This doubles the amount of data that Redpanda uploads to object storage, but it also reduces the memory footprint of the partition, which results in better scalability because 98% less memory is needed to keep information about the uploaded segment.
```

2023-05-03 01:03 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_configuration-properties.mdx
> +| <ClusterProperty name="cloud_storage_disable_tls" frontmatter={props.frontmatter}/> | Disables TLS encryption. You can set this to true if TLS termination is done by the proxy, such as HAProxy. Def
```suggestion
| <ClusterProperty name="cloud_storage_disable_tls" frontmatter={props.frontmatter}/> | Disables TLS encryption. Set to true if TLS termination is done by the proxy, such as HAProxy. Default is false.  |
```

2023-05-03 01:04 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_enable.mdx
> +2. Then, configure topics for Tiered Storage. You can configure either all topics in a cluster or just specific topics.
```suggestion
2. Configure topics for Tiered Storage. You can configure either all topics in a cluster or just specific topics. 
```

2023-05-03 01:10 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_enable.mdx
> +**Table 1: Remote write configuration options**
I've not seen tables numbered in this way before...what is the value-add for readers? Are the only numbered tables those with config options? Do you think this will be apparent to readers?

2023-05-03 01:12 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_intro.mdx
> +Tiered Storage helps to lower storage costs by offloading log segments to object storage. You can specify the amount of storage you want to retain in local storage. You don't need to specify which lo
```suggestion
Tiered Storage helps to lower storage costs by offloading log segments to object storage. You can specify the amount of storage you want to retain in local storage. You don't need to specify which log segments you want to move, because Redpanda moves them automatically based on cluster-level configuration properties. Tiered Storage indexes where data is offloaded, so it can look up the data when you need it.
```

2023-05-03 01:18 UTC, Feediver1 commented on docs/manage/shared/tiered-storage/_set-retention-limits.mdx
> +For compacted topics, Redpanda compacts segments after they have been uploaded to object storage. Redpanda initially uploads all uncompacted segments. It then reuploads the segments with compaction a
```suggestion
For compacted topics, Redpanda compacts segments after they have been uploaded to object storage. Redpanda initially uploads all uncompacted segments. It then re-uploads the segments with compaction applied. It's likely that some segments in object storage are not compacted, but the Tiered Storage read path can manage this. 
```

2023-05-03 01:24 UTC, Feediver1 approved these changes
See suggestions--your call

2023-05-03 17:57 UTC, micheleRP commented on docs/manage/shared/tiered-storage/_enable.mdx
> +**Table 1: Remote write configuration options**
Good point. I removed the table titles and updated column headings.

2023-05-03 17:59 UTC, micheleRP commented on docs/manage/shared/tiered-storage/_adjacent-segment-merging.mdx
> +By default, and as part of housekeeping, Redpanda runs adjacent segment merging on all segments in object storage that are smaller than the threshold. Two properties control the behavior of <TunableC
clarified this

2023-05-03 18:08 UTC, merged