RP Cloud Managed Connectors
redpanda-data/documentation pull request #1577
Opened 2023-05-07 14:38 UTC by Feediver1

Fixes #1209

2023-05-09 09:35 UTC, vladoschreiner requested changes

2023-05-09 09:35 UTC, vladoschreiner commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +   - [Create a new dataset](https://cloud.google.com/bigquery/docs/datasets) for the project (enter `user_actions` as the Dataset ID).
`user_actions` is just an example. Users can choose the dataset name of their choice.

2023-05-09 09:35 UTC, vladoschreiner commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +     Specify a structure for the table using schema values that align with your Redpanda Cloud topic data.
This step is optional. It is mandatory only if the data in Redpanda don't contain schema. If the data in Redpanda are typed (have schema attached to it) the connector auto-creates the tables in BigQuery automatically.

2023-05-09 09:35 UTC, vladoschreiner commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +- When the connector is configured with `Upsert enabled` or `Delete enabled`, it
We don't support SMTs (single message transforms) as of now. Please remove this limitation from the list.

2023-05-09 09:35 UTC, vladoschreiner commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +[External BigQuery sink connector](https://github.com/wepay/kafka-connect-bigquery/wiki/Connector-Configuration) documentation
@bochenekmartin do we use this repo or the Confluent fork, please?

2023-05-09 15:25 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +[External BigQuery sink connector](https://github.com/wepay/kafka-connect-bigquery/wiki/Connector-Configuration) documentation
Awaiting guidance...

2023-05-10 02:11 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +[External BigQuery sink connector](https://github.com/wepay/kafka-connect-bigquery/wiki/Connector-Configuration) documentation
We do not want to link to Confluent...

2023-05-15 14:12 UTC, vladoschreiner commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcs-connector.mdx
> +   | `GCS file format`              | Format of the key coming from the Kafka topic: `CSV` (the default), `JSON`, `JSONL AVRO`, or `PARQUET`. The default is `CSV`. You can use the  `CSV` format outpu
Format of the files that are created in GCS. Not related to the key.

2023-05-16 12:39 UTC, tomasz-sadura commented on docs/deploy/deployment-option/cloud/managed-connectors/create-snowflake-connector.mdx
> +- Plain text formatted records should use `"org.apache.kafka.connect.storage.StringConverter"`.
I think we should replace the Java classes (that are not visible on the UI) with the labels we present in the wizard:
- `SNOWFLAKE_JSON`
- `SNOWFLAKE_AVRO`
- `SNOWFLAKE_AVRO_WITHOUT_SCHEMA_REGISTRY`
- `STRING`

2023-05-17 12:34 UTC, bochenekmartin commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +[External BigQuery sink connector](https://github.com/wepay/kafka-connect-bigquery/wiki/Connector-Configuration) documentation
we use Confuent fork

2023-05-19 02:52 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +[External BigQuery sink connector](https://github.com/wepay/kafka-connect-bigquery/wiki/Connector-Configuration) documentation
Removed

2023-05-19 08:54 UTC, bochenekmartin commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-source-connector.mdx
> +## Create a MirrorMaker2 Source Sink connector
I guess it should be
> Create a MirrorMaker2 Source connector

not
> Source Sink

2023-05-19 14:39 UTC, bochenekmartin commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mysql-source-connector.mdx
> +| **org.apache.kafka.connect.errors.ConnectException: Error configuring an instance of KafkaSchemaHistory; check the logs for details** | Set the database schema history properties `schema.history.in
Good catch, let's remove it.

2023-05-19 14:41 UTC, bochenekmartin commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mysql-source-connector.mdx
> +| **No resolvable bootstrap urls given in bootstrap.servers** | Set valid broker URLs using `schema.history.internal.kafka.bootstrap.servers`. |
Good catch, let's remove this one:
> **No resolvable bootstrap urls given in bootstrap.servers**

2023-05-19 14:41 UTC, bochenekmartin commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mysql-source-connector.mdx
> +| **ConnectException: Error configuring an instance of KafkaSchemaHistory; check the logs for details** | Verify that the schema history configuration properties `schema.history.internal.kafka.topic`
Yup, this one can be removed:
> **ConnectException: Error configuring an instance of KafkaSchemaHistory; check the logs for details**

2023-05-19 14:44 UTC, bochenekmartin commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mysql-source-connector.mdx
> +| **java.lang.IllegalArgumentException: Only a single connector task may be started** | Remove `tasks.max` or set it to `1`. |
Yes, this can be removed:
> **java.lang.IllegalArgumentException: Only a single connector task may be started**

2023-05-19 14:46 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-source-connector.mdx
> +To create the MirrorMaker2 Source Sink connector:
copy/paste error--thanks

2023-05-19 14:48 UTC, bochenekmartin commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mysql-source-connector.mdx
> +- **Topics not created by the connector**
Yup, this sentence can be removed:
`Schema history configuration errors are reported as failed tasks.`

2023-05-22 18:27 UTC, bochenekmartin approved these changes
LGTM

2023-05-23 09:37 UTC, bochenekmartin approved these changes
Added only one comment in S3 sink documentation.
Besides, it's all good and can be merged 👍

2023-05-23 09:37 UTC, bochenekmartin commented on docs/deploy/deployment-option/cloud/managed-connectors/create-s3-sink-connector.mdx
> +* [S3 Sink Connector for Apache Kafka](https://github.com/redpanda-data/connectors/blob/main/s3-sink-connector/README.md)
It can be removed, it refers to a private GitHub repository, so external users cannot access it

2023-05-23 09:48 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/index.mdx
> +Console. Each connector form is consistent across all connectors.
```suggestion
Redpanda Connectors link your Redpanda cluster with different data systems. As pre-built, managed solutions, connectors offer a simpler way to integrate your data than manually creating a solution with the Kafka API. Each connector fetches messages from Kafka topics and transfers them to locations such as S3 or GCS buckets. You can set up and manage these connectors in Redpanda Console. All connectors are managed by Redpanda.
```

2023-05-23 09:49 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/index.mdx
> +Console. Each connector form is consistent across all connectors.
> provide a managed alternative to using the Kafka API

Connectors must use the Kafka API as well, so I revised the paragraph to convey the idea that we've built a managed solution that saves you the effort of using the Kafka API to do it yourself.

2023-05-23 10:04 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/index.mdx
> +Console. Each connector form is consistent across all connectors.
I also added an explanation of source vs sink as I couldn't find one and this seemed like a good place.

2023-05-23 10:14 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +   3. (_Optional_) After creating the dataset, [create a new table](https://cloud.google.com/bigquery/docs/tables) to hold the data you intend to stream from Redpanda Cloud topics.
```suggestion
   3. (_Optional if your data has a schema_) After creating the dataset, [create a new table](https://cloud.google.com/bigquery/docs/tables) to hold the data you intend to stream from Redpanda Cloud topics.
```

2023-05-23 10:15 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +   3. (_Optional_) After creating the dataset, [create a new table](https://cloud.google.com/bigquery/docs/tables) to hold the data you intend to stream from Redpanda Cloud topics.
On the index page, we use _Kafka topics_. Here, we use _Redpanda Cloud topics_. We should use one and be consistent. Maybe _Redpanda topics_?

2023-05-23 10:18 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +   | `Topics to export`             | A comma-separated list of the cluster topics you want to replicate to GCP BigQuery. |
> cluster topics

See https://github.com/redpanda-data/documentation/pull/1577/files#r1202000774

2023-05-23 10:23 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +title: Create a GCP BigQuery Sink Connector
The Cloud UI uses _Google BigQuery_.

2023-05-23 10:24 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +    <meta name="title" content="Create a BigQuery Sink Connector | Redpanda Docs"/>
Make this consistent with the title.

2023-05-23 10:27 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +1. In Redpanda Console, click **Connectors** in the navigation menu, and then
For Cloud users, should we refer to Redpanda Console at all? Redpanda Cloud is the product and Console is built into it. However, apart from the footer, Redpanda Console isn't mentioned anywhere.

If I were a new user reading this sentence, I'd be looking for a menu item called **Redpanda Console**.

2023-05-23 10:27 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +However, if you require any additional property settings (for example, automatically
```suggestion
If you require any additional property settings (for example, automatically
```

2023-05-23 10:30 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-s3-sink-connector.mdx
> +Before you can create an AWS S3 sink connector in the Redpanda Cloud, you must complete these tasks:
```suggestion
Before you can create an AWS S3 Sink connector in Redpanda Cloud, you must complete these tasks:
```

2023-05-23 10:31 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-s3-sink-connector.mdx
> +2. Select the (Export to) S3 Sink managed connector.
```suggestion
2. Select (Export to) S3.
```

2023-05-23 10:33 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +2. Select the BigQuery Sink connector, and click **Next**.
```suggestion
2. Select **Export to Google BigQuery**.
```

2023-05-23 10:34 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +    <link rel="canonical" href="https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-s3-sink-connector/" />
```suggestion
    <link rel="canonical" href="https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector/" />
```

2023-05-23 10:34 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcp-bigquery-connector.mdx
> +1. In Redpanda Console, click **Connectors** in the navigation menu, and then
The meta description of this page is `Use the Redpanda Cloud UI to create a BigQuery Sink Connector.`

2023-05-23 10:36 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-gcs-connector.mdx
> +2. Select the (Export to) Google Cloud Storage managed connector.
```suggestion
2. Select **Export to Google Cloud Storage**.
```

2023-05-23 10:38 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-http-source-connector.mdx
> +- Only `JSON` or `AVRO` formats can be used as a value converter.
```suggestion
Only `JSON` or `AVRO` formats can be used as a value converter.
```

2023-05-23 10:39 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-http-source-connector.mdx
> +2. Select the (Import from) HTTP managed connector.
```suggestion
2. Select **Import from HTTP**.
```

2023-05-23 10:40 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-sink-connector.mdx
> +You can use a JDBC Sink connector to transfer structured data from Redpanda into
```suggestion
You can use a JDBC Sink connector to export structured data from Redpanda to
```

2023-05-23 10:41 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-sink-connector.mdx
> +However, if you require any additional property settings, then specify any of the following
```suggestion
If you require additional property settings, then specify any of the following
```

2023-05-23 10:42 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-sink-connector.mdx
> +         // fields
```suggestion
```

2023-05-23 10:42 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-sink-connector.mdx
> +         // payload
```suggestion
```

2023-05-23 10:42 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-sink-connector.mdx
> +After the connector is created, check to ensure that:
```suggestion
After the connector is created, ensure that:
```

2023-05-23 10:43 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-source-connector.mdx
> +2. Select the (Import from) JDBC managed connector.
```suggestion
2. Select **Import from JDBC**.
```

2023-05-23 10:43 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-source-connector.mdx
> +However, if you require any additional property settings, then specify any of the following
```suggestion
if you require additional property settings, then specify any of the following
```

2023-05-23 10:44 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-checkpoint-connector.mdx
> +- The external Kafka cluster is accessible
```suggestion
- The external Kafka cluster is accessible.
```

2023-05-23 10:44 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-checkpoint-connector.mdx
> +- The Kafka cluster topics connector is running for the same source cluster, with a matching configuration
```suggestion
- The external Kafka cluster is accessible.
- A service account with read-only access to the external cluster is available.
- The Kafka cluster topics connector is running for the same source cluster, with a matching configuration.
```

2023-05-23 10:45 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-checkpoint-connector.mdx
> +2. Select the (Import from) Kafka cluster offsets managed connector.
```suggestion
2. Select the **Import from Kafka cluster offsets**.
```

2023-05-23 10:45 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-checkpoint-connector.mdx
> +However, if you require any additional property settings, then specify any of the following
```suggestion
If you require additional property settings, then specify any of the following
```

2023-05-23 10:46 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-checkpoint-connector.mdx
> +After the connector is created, check to ensure that:
```suggestion
After the connector is created:
```

2023-05-23 10:47 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-heartbeat-connector.mdx
> +2. Select the (Import from) Heartbeat managed connector.
```suggestion
2. Select the **Import from Heartbeat**.
```

2023-05-23 10:47 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-heartbeat-connector.mdx
> +However, if you require any additional property settings, then specify any of the following
```suggestion
If you require additional property settings, then specify any of the following
```

2023-05-23 10:49 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-source-connector.mdx
> +- Replicate topic ACLs.
```suggestion
- Replicate topic access-control lists (ACLs).
```

2023-05-23 10:49 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mmaker-source-connector.mdx
> +2. Select the (Import from) Kafka cluster topics managed connector.
```suggestion
2. Select **Import from Kafka cluster topics**.
```

2023-05-23 10:50 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mongodb-sink-connector.mdx
> +2. Select the (Export to) MongoDB Sink managed connector.
```suggestion
2. Select **Export to MongoDB**.
```

2023-05-23 10:51 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mongodb-sink-connector.mdx
> +_optional_ advanced connector configuration properties by selecting **Show advanced options**
```suggestion
If you require additional property settings, then specify any of the following
_optional_ advanced connector configuration properties by selecting **Show advanced options**
```

2023-05-23 10:51 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mongodb-source-connector.mdx
> +2. Select the (Import from) MongoDB Source managed connector.
```suggestion
2. Select **Import from MongoDB**.
```

2023-05-23 10:52 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mongodb-source-connector.mdx
> +However, if you require any additional property settings, then specify any of the following
```suggestion
If you require additional property settings, then specify any of the following
```

2023-05-23 10:58 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-mysql-source-connector.mdx
> +- There must be a [binlog enabled](https://debezium.io/documentation/reference/stable/connectors/mysql.html#enable-mysql-binlog) for the source MySQL cluster.
```suggestion
- A [binlog must be enabled](https://debezium.io/documentation/reference/stable/connectors/mysql.html#enable-mysql-binlog) for the source MySQL cluster.
```

2023-05-23 11:00 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-s3-sink-connector.mdx
> +However, if you require any additional property settings, then specify any of the following
```suggestion
If you require additional property settings, then specify any of the following
```

2023-05-23 11:01 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-snowflake-connector.mdx
> +
Missing an intro. What is the Snowflake Sink connector?

2023-05-23 11:02 UTC, JakeSCahill commented on docs/deploy/deployment-option/cloud/managed-connectors/create-snowflake-connector.mdx
> +2. Select the (Export to) Snowflake Sink managed connector.
```suggestion
2. Select **Export to Snowflake**.
```

2023-05-23 11:04 UTC, JakeSCahill approved these changes
Looks awesome!

Approving, but please see my comments for fixes and suggestions. Most importantly, we need to fix the canonical links for some pages. I've added the fixes as suggestions 😄

2023-05-23 21:56 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/managed-connectors/index.mdx
> +Console. Each connector form is consistent across all connectors.
Much improved--Thanks @JakeSCahill

2023-05-23 23:16 UTC, merged