docs: #1562 doc support for DeleteRecords
redpanda-data/documentation pull request #1657
Opened 2023-06-01 20:05 UTC by micheleRP

resolves #1562 

This adds a small section: Delete records from a topic. It also renames the page from Configure Topics to Manage Topics

This was originally in #1632 (already approved by Matt), but since Beta docs already published, I've closed that PR and moving this changes into dev under versioned_docs/version-23.2.

Preview:

2023-06-06 19:04 UTC, micheleRP commented
@graphcareful: Reminder about this! Could you please provide an example we can include in docs?

2023-06-09 15:10 UTC, graphcareful requested changes

2023-06-09 15:10 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +To free up disk space, you can use `kafka-delete-records.sh` to delete data from the beginning of a partition up to a requested offset. This DeleteRecords API lets you delete data with precise contro
Theres many ways to do this, i like `kcl` (@twmb 's command line tool), maybe we should give a `kcl` example instead ?

2023-06-09 15:10 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +To free up disk space, you can use `kafka-delete-records.sh` to delete data from the beginning of a partition up to a requested offset. This DeleteRecords API lets you delete data with precise contro
I wouldn't say up until a point in time, just mention up until a specific business event (offset). The API doesn't include a time point

2023-06-09 15:10 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +To free up disk space, you can use `kafka-delete-records.sh` to delete data from the beginning of a partition up to a requested offset. This DeleteRecords API lets you delete data with precise contro
Didn't we say we wanted to let people know this isn't really a great compliance tool? The TL;DR is that after the request is processed some data you requested to be deleted may still be on disk for an indeterminate amount of time, even though no kafka clients would be able to access them.

2023-06-09 15:10 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +To free up disk space, you can use `kafka-delete-records.sh` to delete data from the beginning of a partition up to a requested offset. This DeleteRecords API lets you delete data with precise contro
"The DeleteRecords API is also useful if time-based message retention is storing more data than anticipated" What does this mean?

2023-06-09 15:10 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +To delete records, run `kafka-delete-records.sh`:
Here's an example with KCL:
```
kcl admin delete-records foo:p0,o120 foo:p1,o3888
```

2023-06-09 15:10 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- To delete records, `cleanup.policy` cannot be set to `compact`.
it can be set to `compact` you need to set `delete`, you can also have `delete+compact`

2023-06-09 15:10 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- Local storage is deleted synchronously, but if a broker is offline during the request, it may retain data until it comes back online.
Technically its deleted asynchronously. A background thread that runs on a hard coded timer processes these requests. I wouldn't mention data from an offline node will not be deleted that is obvious

2023-06-09 15:10 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- Object storage is deleted asynchronously. When DeleteRecords returns, the partition's start offset will have advanced, but the work required to garbage collect delete segments may not be complete.
+1

2023-06-09 15:10 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- After calling DeleteRecords, the Tiered Storage cache may contain data from before the offset. This data is not visible to clients but could be read by someone with access to the local disk of a Re
Also the same is true for local storage. The reason is because we do not truncate segments in half. So we just delete as many segments as possible then for that last segment, just bump the start offset. Cloud storage works the same way too

2023-06-09 15:18 UTC, twmb commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +To free up disk space, you can use `kafka-delete-records.sh` to delete data from the beginning of a partition up to a requested offset. This DeleteRecords API lets you delete data with precise contro
We plan to add this to rpk, with something like `rpk topic trim`

2023-06-09 16:47 UTC, twmb commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +To free up disk space, you can use `kafka-delete-records.sh` to delete data from the beginning of a partition up to a requested offset. This DeleteRecords API lets you delete data with precise contro
We will be releasing the rpk change in the same release that DeleteRecords is added -- I think that's 23.2, so no reason to have a kcl example here. It's a pretty quick turnaround for rpk.

2023-06-09 19:38 UTC, graphcareful reviewed
Great just some nits

2023-06-09 19:38 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- Object storage is deleted asynchronously. When DeleteRecords returns, the partition's start offset will have advanced, but the work required to garbage collect delete segments may not be complete.
nit: garbage collect "deleted" segments

2023-06-09 19:38 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- After calling DeleteRecords, local storage and object storage may contain data from before the offset. (Redpanda does not truncate segments in half. It deletes as many segments as possible for the
Remove `for the last segment`

2023-06-09 19:38 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- After calling DeleteRecords, local storage and object storage may contain data from before the offset. (Redpanda does not truncate segments in half. It deletes as many segments as possible for the
Change `This data` to `Data before the new start offset`

2023-06-09 19:38 UTC, micheleRP commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +To free up disk space, you can use `kafka-delete-records.sh` to delete data from the beginning of a partition up to a requested offset. This DeleteRecords API lets you delete data with precise contro
Thanks @graphcareful and @twmb. Please review the latest draft with `rpk topic trim` and approve if it's good, or let me know if this doc PR should hold off for final rpk implementation! cc @mattschumpert

2023-06-15 20:43 UTC, shorgi commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +Delete records from a topic with the `rpk topic trim` command. Use this when you know that all consumers have read up to that given offset, and the data is no longer needed.
`rpk topic trim` is new for 23.2? Todo: link to its rpk command reference page

2023-06-15 20:43 UTC, shorgi commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- To delete records, `cleanup.policy` must be set to `delete` or `delete+compact`.
```suggestion
- To delete records, `cleanup.policy` must be set to `delete` or `compact,delete`.
```

2023-06-15 20:43 UTC, shorgi commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- Object storage is deleted asynchronously. When DeleteRecords returns, the partition's start offset will have advanced, but the work required to garbage collect deleted segments may not be complete.
```suggestion
- Object storage is deleted asynchronously. When DeleteRecords returns, the partition's start offset will have advanced, but garbage collection of deleted segments may not be complete.
```

2023-06-15 20:43 UTC, shorgi commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- After calling DeleteRecords, local storage and object storage may contain data from before the offset. (Redpanda does not truncate segments in half. It deletes as many segments as possible, then bu
```suggestion
- After calling DeleteRecords, local storage and object storage may still contain data for deleted offsets. (Redpanda does not truncate segments, instead it deletes as many whole segments as possible, then bumps the start offset.) Data before the new start offset is not visible to clients but could be read by someone with access to the local disk of a Redpanda node. 
```

2023-06-16 02:31 UTC, mattschumpert commented
@micheleRP 
Looks good except I think we should clarify right up front that there are two ways to delete records from a topic.   Redpanda supports the using DeleteRecords Kafka API via Kafka clients and also provides a CLI to accomplish the same.  

Instead of making that clear, right now we refer to the API name 'DeleteRecords' here and there and then show how to use the CLI for trim, which might be confusing and doesn't point out that clients and Kafka tooling that relies on the DeleteRecords API are now supported

2023-06-16 13:22 UTC, graphcareful requested changes

2023-06-16 13:22 UTC, graphcareful commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- After calling DeleteRecords, local storage and object storage may still contain data for deleted offsets. (Redpanda does not truncate segments, instead it deletes as many whole segments as possible
```
 (Redpanda does not truncate segments, instead it deletes as many whole segments as possible, then bumps the start offset.)
 ```
 This is backwards, redpanda first bumps the start offset then attempts to delete as many whole segments in the background.

2023-06-16 13:57 UTC, micheleRP commented
Note to docs team: Wait to merge this until GA. It's not included Beta.

2023-06-16 15:40 UTC, twmb commented
Also please ping me before merging to confirm that `rpk topic trim` exists / hasn't been reworded

2023-07-05 19:03 UTC, Feediver1 commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +Redpanda lets you delete data from the beginning of a partition up to a specific offset (event). The offset represents the true creation time of the event, not the time when it was stored by Redpanda
```suggestion
Redpanda lets you delete data from the beginning of a partition up to a specific offset (event). The offset represents the true creation time of the event, not the time when it was stored by Redpanda. Deleting records frees up disk space, which is especially helpful if your producers are pushing more data than you anticipated in your retention plan. Do this when you know that all consumers have read up to that given offset, and the data is no longer needed.
```

2023-07-05 19:09 UTC, Feediver1 approved these changes
lgtm

2023-07-06 22:47 UTC, micheleRP commented
@graphcareful, @twmb, @mattschumpert: We won't merge this PR until GA, but please give it a final review, confirm if this will use `rpk topic trim`, and approve for 23.2.

2023-07-06 23:28 UTC, mattschumpert approved these changes

2023-07-06 23:28 UTC, mattschumpert commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +- After deleting records, local storage and object storage may still contain data for deleted offsets. (Redpanda does not truncate segments, instead it bumps the start offset then attempts to delete
@micheleRP I think we should add 'similar to Kafka' or something to explain this is the same behavior in Kafka.

2023-07-06 23:28 UTC, mattschumpert commented on versioned_docs/version-23.2/develop/config-topics.mdx
> +There are different ways to delete records from a topic, including using the `rpk topic trim` command or using the DeleteRecords Kafka API with Kafka clients.
@micheleRP current plan is to use an alias so you can use either 'rpk topic trim-prefix, or rpk topic trim for short'

cc @r-vasquez

2023-07-07 14:59 UTC, twmb commented
We just merged `rpk topic trim-prefix`: https://github.com/redpanda-data/redpanda/pull/11825/
The long help text here: https://github.com/redpanda-data/redpanda/pull/11825/files#diff-8b8948fa591e8f102227cb9fac7259c16ba8d93f66d07c2cd4b37ac822cecff9R40-R70
contains a fuller description
let us know if you'd like more information / a walkthrough

2023-07-07 15:42 UTC, mattschumpert commented
And to be clear 'rpk topic trim' also works.

2023-07-10 23:02 UTC, graphcareful approved these changes

2023-07-21 00:59 UTC, merged