docs: Using ExternalDNS with the Helm chart
redpanda-data/documentation pull request #1663
Opened 2023-06-06 11:57 UTC by JakeSCahill

Review deadline: May 9

Fixes #1638

2023-06-06 23:25 UTC, joejulian commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +- If you want brokers to advertise a custom domain, you must have a domain from a domain registrar.
I don't know if you care, but this isn't entirely true. I can use `redpanda.joe` as long as I point my client at the nameservers that serve it. `joe` isn't a valid TLD but neither external-dns nor route53 care if it's valid.

2023-06-06 23:28 UTC, joejulian commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +By default, the Helm chart gives each broker a subdomain that consists of the chart name and the Pod ordinal. For example, `redpanda-0`, where `redpanda` is the chart name and `0` is the Pod ordinal.
```suggestion
By default, the Helm chart gives each broker a hostname that consists of the helm release name and the Pod ordinal. For example, `redpanda-0`, where `redpanda` is the helm release name and `0` is the Pod ordinal. To configure brokers to advertise these hosts on a subdomain, you must configure an external domain.
```

2023-06-06 23:30 UTC, joejulian commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +You can give each Redpanda broker a custom subdomain to advertise instead of the default subdomains. Custom subdomains can either be suffixed with the Pod ordinal or they can be fully custom.
```suggestion
You can give each Redpanda broker a custom fqdn to advertise instead of the default hostnames. Custom hostnames can either be suffixed with the Pod ordinal or they can be fully custom.
```

I'm not sure if this is true. Can you really give each pod its own custom fqdn? This statement is a little confusing.

2023-06-06 23:30 UTC, joejulian commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +1. Add your subdomains to the `external.addresses` setting.
```suggestion
1. Add your FQDNs to the `external.addresses` setting.
```

2023-06-06 23:31 UTC, joejulian commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +1. Add your subdomains to the `external.addresses` setting.
Shouldn't we start with the easy way and have they set the `external.domain` instead of the error-prone "name each pod" method?

2023-06-06 23:35 UTC, joejulian commented
This whole document change uses "subdomain" incorrectly.

- `redpanda-0` is a hostname.
- `mydomain.dom` is a domain name.
- In `redpanda-0.redpanda.mydomain.dom`, `redpanda` is a subdomain of `mydomain.dom`
- `redpanda-0.redpanda.mydomain.dom` is a fully qualified domain name (FQDN) within the `redpanda` subdomain of the `mydomain.dom` domain.

2023-06-06 23:36 UTC, joejulian requested changes
This whole document change uses "subdomain" incorrectly.

- `redpanda-0` is a hostname.
- `mydomain.dom` is a domain name.
- In `redpanda-0.redpanda.mydomain.dom`, `redpanda` is a subdomain of `mydomain.dom`
- `redpanda-0.redpanda.mydomain.dom` is a fully qualified domain name (FQDN) within the `redpanda` subdomain of the `mydomain.dom` domain.

2023-06-07 17:06 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +- If you want brokers to advertise a custom domain, you must have a domain from a domain registrar.
Clarified in https://github.com/redpanda-data/documentation/pull/1663/commits/ebce97623eb4c564e6e64bf2e8a949990c41bd69

2023-06-07 17:18 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +1. Add your subdomains to the `external.addresses` setting.
Fixed in https://github.com/redpanda-data/documentation/commit/ebce97623eb4c564e6e64bf2e8a949990c41bd69

2023-06-07 17:27 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +- If you want brokers to advertise a custom domain, you must have a domain from a domain registrar.
```
- If you want brokers to advertise a custom domain, you must have control over the DNS settings for that domain.

  :::tip
  For internal testing, you can use any domain without owning that domain, as long as:

  - Your local DNS server is configured to resolve that domain to the correct IP address.
  - Your client systems are configured to use your DNS server for resolution.

  For production, it's best to buy a domain from a domain registrar. This way, your domain is resolvable without any additional client-side configuration.
  :::
```

2023-06-13 22:19 UTC, joejulian commented on docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
> +  external-dns.alpha.kubernetes.io/hostname=<hostname>.<custom-domain> \
external-dns will add the hostname. The label name is misleading.
```suggestion
  external-dns.alpha.kubernetes.io/hostname=<custom-domain> \
```

2023-06-13 22:19 UTC, joejulian commented on docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
> +  external-dns.alpha.kubernetes.io/endpoints-type=<HOSTIP or NodeExternalIP>
```suggestion
  external-dns.alpha.kubernetes.io/endpoints-type=<HostIP or NodeExternalIP>
```

2023-06-13 22:22 UTC, joejulian approved these changes
Two corrections but other than that it lgtm.

2023-06-15 15:51 UTC, shorgi commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +When the `external.type` field is set to `LoadBalancer`, the Helm chart creates one LoadBalancer Service for each replica in the StatefulSet. Each LoadBalancer Service routes external traffic to the
What/which is `this NodePort Service`, should it be `this LoadBalancer Service`?

2023-06-15 15:51 UTC, shorgi commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +To configure your Redpanda brokers to advertise a custom domain, each broker must also have a hostname that points to the address of the broker's corresonding load balancer instance.
```suggestion
To configure your Redpanda brokers to advertise a custom domain, each broker must also have a hostname that points to the address of the broker's corresponding load balancer instance.
```

2023-06-15 15:56 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +When the `external.type` field is set to `LoadBalancer`, the Helm chart creates one LoadBalancer Service for each replica in the StatefulSet. Each LoadBalancer Service routes external traffic to the
```suggestion
When the `external.type` field is set to `LoadBalancer`, the Helm chart creates one LoadBalancer Service for each replica in the StatefulSet. Each LoadBalancer Service routes external traffic to the listener ports on a single Redpanda broker. To set up external access using LoadBalancer Services, you must configure the brokers to advertise addresses that resolve to the load balancer instances.
```

2023-06-15 15:57 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
> +When the `external.type` field is set to `LoadBalancer`, the Helm chart creates one LoadBalancer Service for each replica in the StatefulSet. Each LoadBalancer Service routes external traffic to the
Thanks, this should be LoadBalancer Services. Updated.

2023-06-15 16:08 UTC, shorgi approved these changes
A few comments, the rest LGTM

2023-06-15 16:08 UTC, shorgi commented on docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
> +- **Security**: IP addresses assigned to worker nodes must be made resolvable by DNS names to ensure secure TLS access.
Nit: edit to emphasize the advantage of domain vs IP. IIUC, something like `Using domain names ensures more secure TLS access, where IP addresses assigned to worker nodes must be made resolvable by DNS names.`

2023-06-16 09:44 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
> +- **High Availability**: If a server fails, you can quickly point the domain name to another IP address, which would not be possible if clients connect directly via IP addresses.
```suggestion
- **High Availability**: If a server fails, you can quickly point the domain name to another IP address, which would not be possible if clients connect directly using IP addresses.
```

2023-06-16 09:45 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
> +- **Flexibility**: IP addresses can change, especially in cloud environments where services can be moved around or scaled up and down. If you use domain names, you can simply update the DNS record wh
```suggestion
- **Flexibility**: IP addresses can change, especially in cloud environments where services can be moved around or scaled up and down. If you use domain names, you can update the DNS record when the IP address changes and the clients won't need any configuration changes.
```

2023-06-16 09:47 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
> +- **Security**: IP addresses assigned to worker nodes must be made resolvable by DNS names to ensure secure TLS access.
```suggestion
```

2023-06-16 09:49 UTC, JakeSCahill commented on docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
> +- **Security**: IP addresses assigned to worker nodes must be made resolvable by DNS names to ensure secure TLS access.
```suggestion
- **Security**: If the IP address of a server changes, you won't need to reissue TLS certificates if it's bound to a domain name.
```

2023-06-16 09:56 UTC, merged