docs:#1574 update Ansible docs
redpanda-data/documentation pull request #1694
Opened 2023-06-14 04:40 UTC by micheleRP

resolves #1574 

preview:

2023-06-14 04:58 UTC, micheleRP commented
Hi @gene-redpanda and @deniscoady! This adds some conceptual info about automated deployment. Please review and let me know what else it needs; e.g., Gene, I think you said there's a requirement to download the appropriate role if you customize the playbook? Should we add links into this page from other parts of our doc; e.g., the [quickstart ](https://deploy-preview-1694--redpanda-documentation.netlify.app/docs/get-started/quick-start/#next-steps) points users as a next step to the manual Deploy for Production page, but should we encourage them to look here first? Also, separately wondering if you'd like a copyedit on the readme?

2023-06-15 21:16 UTC, shorgi commented
Is the https://github.com/redpanda-data/deployment-automation repo the single source of truth for this topic? If it is, we should avoid duplicating any of its content here, and instead copyedit its README and point readers there.

2023-06-22 15:53 UTC, micheleRP commented
@deniscoady, @gene-redpanda: Please try to review this by Friday, June 23!

2023-06-22 16:25 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> -### Clone the GitHub repository
It might be sensible to include some of the information from the Basic Usage section here: 

https://github.com/redpanda-data/deployment-automation#basic-usage

2023-06-23 17:42 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +If you use automation tools like Terraform and Ansible in your environment, you can use them to easily provision a Redpanda cluster for production. Terraform can set up the infrastructure and output
It might make sense to show what our hosts file looks like here. Example: https://github.com/redpanda-data/deployment-automation#populating-a-hosts-file

2023-06-23 18:00 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
>      `terraform apply`
you will need a vpc id and subnet id for this to work if you don't have a default vpc defined. the public key will also need to be set if it isn't the default ~/.ssh/id_rsa.pub

```shell
terraform apply -var='public_key_path=~/.ssh/id_rsa.pub' -var='subnet_id=<<<SUBNET_ID>>>' -var='vpc_id=<<<VPC_ID>>>'
```

2023-06-28 21:09 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
>      `terraform apply`
This is a duplicate of 52-65 now

2023-06-28 21:10 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    ```
This is now a duplicate of 52-65

2023-06-28 21:10 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +export AWS_SECRET_ACCESS_KEY=<your-secret-access-key>
GCP as well

2023-06-28 21:11 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +export AWS_SECRET_ACCESS_KEY=<your-secret-access-key>
It'd make sense to just call it "Terraform code" or "Terraform scripts" rather than "Non-AWS Terraform Code"

2023-06-28 21:11 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +1. Clone the [`deployment-automation` GitHub repository](https://github.com/redpanda-data/deployment-automation/):
This was already done at line 20

2023-06-28 21:12 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +  ```
Same as above, already accomplished ~line 20

2023-06-28 21:13 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `redpanda_use_staging_repo` | `false` | Enables access to unstable builds. |
this is now "is_using_unstable"

2023-06-28 21:14 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Configure TLS with externally-provided and signed certificates (possibly through a corporate-provided Certmonger). Then run the `provision-tls-cluster` playbook, specifying the certificate locations
cert manager not Certmonger

2023-06-28 21:16 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Because any changes made to properties outside of the playbook may be overwritten by this procedure, these settings should be incorporated as part of the provided `--extra-vars`. For example, `--extr
might want to also reference the information on line 252 again here.

2023-06-28 21:17 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +
we should probably also note that removing a value from here does not null it in redpanda. There's a technical explanation for why, but it boils down to ansible not having state so not knowing that a value has been removed. Since we can't act on the lack of a thing (and haven't implemented a way for users to provide a value to be removed from the config yet) any values that should be unset must be unset manually by using RPK

2023-06-28 21:18 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +
"To upgrade a cluster" instead of "to enact an upgrade on a cluster"

2023-06-28 21:18 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +
Might want to add a warning about testing this in staging first

2023-06-28 21:19 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +By default, the playbook selects the latest version of the Redpanda packages, but an upgrade is only enacted if the `redpanda_install_status` variable is set to `latest`:
```suggestion
By default the playbook selects the latest version of the Redpanda packages, but an upgrade is only enacted if the `redpanda_install_status` variable is set to `latest`:
```

2023-06-28 21:20 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Redpanda previously delivered AWS code as simple in-place Terraform code, but it's now converted to a module. To migrate from the old AWS code:
```suggestion
Redpanda previously delivered AWS code as simple in-place Terraform code, but it is now converted to a module. To migrate from the old AWS code:
```

Nitpicking like crazy 😅

2023-06-29 20:10 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `redpanda_use_staging_repo` | `false` | Enables access to unstable builds. |
is it `redpanda_is_using_unstable `or just `is_using_unstable`?

2023-06-29 20:20 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Configure TLS with externally-provided and signed certificates (possibly through a corporate-provided Certmonger). Then run the `provision-tls-cluster` playbook, specifying the certificate locations
@gene-redpanda I'm not sure about the right terminology for this. Which of these is correct? 

Configure TLS with externally-provided and signed certificates (possibly through a corporate-provided cert-manager).
or
Configure TLS signed certificates (possibly through cert-manager).
or 
Configure TLS signed certificates (possibly generated by a corporate CA).
or 
Configure TLS signed certificates (through cert-manager or a corporate CA).

2023-06-30 14:15 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Configure TLS with externally-provided and signed certificates (possibly through a corporate-provided Certmonger). Then run the `provision-tls-cluster` playbook, specifying the certificate locations
we can safely delete this parenthetical:  "(possibly through a corporate-provided Certmonger)"

2023-06-30 14:18 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `redpanda_use_staging_repo` | `false` | Enables access to unstable builds. |
@micheleRP ```is_using_unstable: false```

2023-06-30 14:19 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Adding whitespace breaks configuration merging.
it might be worth specifying that adding whitespace *to the JSON* will break things

2023-06-30 14:22 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +terraform state list | while read -r line ; do terraform state mv "$line" "module.redpanda-cluster.$line"; done
This probably shouldn't be in the official docs as it is a hacky and jank solution to a temporary issue. While it will work most of the time, if someone has a different config or more stuff in their state file than just the stuff we created it could easily cause serious havoc

2023-06-30 17:06 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +If you use automation tools like Terraform and Ansible in your environment, you can use them to easily provision a Redpanda cluster for production. Terraform can set up the infrastructure and output
Please confirm if we need anything more in our [hosts example](https://deploy-preview-1694--redpanda-documentation.netlify.app/docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation/#configure-a-hosts-file).

2023-06-30 17:09 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> -### Clone the GitHub repository
I'm thinking this should stay in the readme, with a link to the updated doc page for more info. After the updated doc is published, I think almost everything on the readme can be removed except Basic Usage and Configuration Guide, but please confirm!

2023-06-30 17:25 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
>      Configuration options:
it might make sense to mention that this is a subset of available configuration options and link to the full list ([here](https://registry.terraform.io/modules/redpanda-data/redpanda-cluster/aws/latest?tab=inputs)) again.

2023-06-30 17:50 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> + ansible-playbook --private-key <your-private-key> -i hosts.ini -v ansible/playbooks/provision-node.yml
we no longer use provision-node.yml as it confused people. the most basic playbook is now provision-basic-cluster.yml

2023-06-30 17:50 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +To use your own playbook, replace `provision-node.yml` with your playbook name.
same comment

2023-06-30 17:50 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +If you use a playbook to create a cluster, also use it for any subsequent operations, like upgrades.
```suggestion
If you use a playbook to create a cluster also use it for any subsequent operations like upgrades.
```

2023-06-30 17:51 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> -### Clone the GitHub repository
Well, the environment variables are essential for ansible to work. otherwise i agree

2023-06-30 18:05 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Use a signed certificate from a valid CA for production environments.
```suggestion
Use a signed certificate from a valid CA for production environments. Our playbook defaults to using locally signed certs that are not recommended for production use and are intended for demo purposes only. You can provide a valid cert using these variables:

redpanda_certs_dir: /etc/redpanda/certs
redpanda_csr_file: "{{ redpanda_certs_dir }}/node.csr"
redpanda_key_file: "{{ redpanda_certs_dir }}/node.key"
redpanda_cert_file: "{{ redpanda_certs_dir }}/node.crt"
redpanda_truststore_file: "{{ redpanda_certs_dir }}/truststore.pem"

```

2023-06-30 18:24 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +- Test that your upgrade path is safe before using it in production.
It is generally a good idea with ansible to incorporate variables into the hosts.ini file rather than including them as extra vars so that future runs will be executed the same way as the first one.

2023-06-30 19:23 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +- Test that your upgrade path is safe before using it in production.
@gene-redpanda: Can you pls confirm that we should replace the first bullet here about incorporate settings as `--extra-vars` with: 

Because edits made to properties outside of the playbook may be overwritten by this procedure, incorporate variables into the `hosts.ini` file.

2023-06-30 19:24 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +- Test that your upgrade path is safe before using it in production.
Yeah that's fine

2023-07-06 19:04 UTC, Feediver1 commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Use the [Redpanda Ansible Collection](https://galaxy.ansible.com/redpanda/cluster) to build a Redpanda cluster. The recommended Redpanda playbook enables TLS encryption and Tiered Storage.
on the destination page, the heading reads "Ansible Collection for Redpanda"

2023-07-06 19:05 UTC, Feediver1 commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +If you prefer, you can download the modules and required roles and create your own playbook. For example, if you want to handle your own data directory, you can toggle that part off, and Redpanda jus
```suggestion
If you prefer, you can download the modules and required roles and create your own playbook. For example, if you want to handle your own data directory, you can toggle that part off, and Redpanda ensures that the permissions are correct. If you want to generate your own security certificates, you can. 
```

2023-07-06 19:17 UTC, Feediver1 commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `restart_node` | `false` | Node configuration to prevent Redpanda brokers from being restarted after updating. Use with care: this can cause `rpk` to be reconfigured but the broker not be restarted
```suggestion
| `restart_node` | `false` | Node configuration to prevent Redpanda brokers from being restarted after updating. Use with care: this can cause `rpk` to be reconfigured but the broker is not restarted and therefore is in an inconsistent state. |
```

2023-07-06 19:19 UTC, Feediver1 commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +To resolve this, try setting an environment variable:
```suggestion
Try setting an environment variable to resolve the error: 
```

2023-07-06 19:19 UTC, Feediver1 approved these changes
Nice

2023-07-06 19:35 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Use the [Redpanda Ansible Collection](https://galaxy.ansible.com/redpanda/cluster) to build a Redpanda cluster. The recommended Redpanda playbook enables TLS encryption and Tiered Storage.
thanks, fixed!

2023-07-06 19:47 UTC, hcoyote requested changes

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
>      | `distro_ami` | AWS AMI to use for each available distribution. These must be changed according to the chosen AWS region. |
this should note that this is an override for whatever is set in distro. distro will automatically choose the latest ami version for a given OS in a given region, but if the user needs a specific local one, they can set distro_ami accordingly. 

also, if they set distro_ami, they must also set distro_ssh_user.

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    | `nodes` | The number of brokers to base the cluster on. Keep in mind that one broker is used as a monitoring broker. Default: `1`|
@gene-redpanda I thought we separated out the monitoring node to it's own instance, separate from the broker instances?

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +5. Now you can install Redpanda either with Ansible or with the [Redpanda installation binary](../../production/production-deployment).
If this doc is focused on automated and repeatable installs, we shouldn't mention the Redpanda installation binary.

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +  export CLOUD_PROVIDER=<cloud-provider>
We should note what the available cloud provider values are for this so it's clear to the end user.

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +1. Set required Ansible variables:
need to make sure the user has gone back into the top-level directory for deployment-automation. I think if they're following along in the doc, they'd still be somewhere in a terraform directory when they got to this phase

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `id` | The node ID of the Redpanda instance. This must be unique for each host. |
is id still needed? I thought this requirement was removed since it was originally used for defining the internal broker id

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `private_ip` | The private IP address of the machine. This could be the same as the public IP address. |
@gene-redpanda  private_ip is optional if there's only one ip address for the host right?

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +You can add additional properties to configure features like rack awareness and Tiered Storage. The `[monitor]` section is only relevant if you have Prometheus and Grafana installed on a given host.
I'd reword this slightly

> The `[monitor]` section is only required if you want the Redpanda Ansible playbooks to install and configure a basic Prometheus and Grafana setup for observability. If you have a centralized monitoring setup or don't require monitoring, then remove this section.

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +Use the [Redpanda Ansible Collection](https://galaxy.ansible.com/redpanda/cluster) to build a Redpanda cluster. The recommended Redpanda playbook enables TLS encryption and Tiered Storage.
@gene-redpanda Thinking a bit more about deployments: TS will only be configurable if the user has access to an object store. When deploying via Ansible-only, we probably can't assume that because they likely will be on-prem with no access to an s3 compatible bucket.

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +To run the recommended Redpanda playbook and have a fully-running Redpanda cluster in one command, run:
> To install and start a Redpanda cluster in one command with the Redpanda playbook, run:

Can we restate to that?

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> + ansible-playbook --private-key <your-private-key> -i hosts.ini -v ansible/playbooks/provision-basic-cluster.yml
I think `-i hosts.ini` is not needed if we previously set the inventory location in a shell variable

we should also add a note that the private key used here is the one that corresponds to the public key loaded into the distro_user's ssh configuration.

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +When you use a playbook to create a cluster, you should also use the playbook for subsequent operations, like upgrades.
Good place to call out that the Ansible modules correctly (and safely) handle doing rolling upgrades, but you must still comply with the version path requirements for RP (there's a doc link we can add in here talking about that)

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +You can specify any available Redpanda configuration value, or set of values, by passing a JSON dictionary as an Ansible `extra-var`. These values are spliced with the calculated configuration and on
@gene-redpanda do we have an example that doesn't pass this in as a json data from the command line?

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +To deploy a Grafana node, you must have a `[monitor]` section in your hosts file. The Grafana URL is `http://<grafana-host>:3000/login`.
This would also deploy prometheus in combination.

This would be a good section to include a statement about Redpanda emitting Prometheus metrics that can be scrapped with a central collector. There's no need to use our playbooks to deploy prom/graf if they already have something setup.

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +-i hosts.ini \
not needed if we already previously defined the inventory file in the shell variable

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +-i hosts.ini \
not needed if we already previously defined the inventory file in the shell variable

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +--extra-vars create_demo_certs=false \
@gene-redpanda we should probably flip this so it's always false so we don't have to specify it every time. creating demo certs should be a special case.

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +-i hosts.ini \
not needed if we already previously defined the inventory file in the shell variable

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +:::
this is a good general note that we should have at the beginning of the ansible section.

the challenge with using multiple --extra-vars command flags is that you have to remember to use them every time., which is hard for repeatability. Tower makes this easier, I think.

but knowing that they can stick these in the hosts.ini for every host (or even better, if we could pull them in from a single include_vars file)

@gene-redpanda  thoughts?

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +To upgrade a cluster, run the playbook with a specific target version. If the target version is higher than the currently-installed version, then the cluster is upgraded and restarted automatically:
Can we rephrase slightly

> is upgraded and safely restarted using a rolling restart that operates on one broker at a time.

This is also a good place to stick a link to our general version upgrade docs talking about what versions you can upgrade between (e.g. 22.3->23.1, but not 22.2->23.1 since that skips a major)

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +ansible-playbook --private-key ~/.ssh/id_rsa ansible/<playbook-name>.yml -i hosts.ini -e redpanda_install_status=latest
does redpanda_install_status have to be `latest` or just any value? I think this corresponds back to the Ansible `state:` value right?

2023-07-06 19:47 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +\"redpanda_rpk_opts\": \"--user ${MY_USER} --password ${MY_USER_PASSWORD}\"
@gene-redpanda is there a better way to define the extra vars here that doesn't require backslashes?

2023-07-06 20:25 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `aws_region` |  | The region to be used if Tiered Storage is enabled. |
@hcoyote The doc will be the single source or truth. After this merges, we can remove the duplicate content from the repo readme.

2023-07-06 23:54 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `aws_region` |  | The region to be used if Tiered Storage is enabled. |
Works for me!

2023-07-07 17:43 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +:::
Yeah I've mentioned this a couple times as an important detail so am in agreement

2023-07-07 17:46 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +\"redpanda_rpk_opts\": \"--user ${MY_USER} --password ${MY_USER_PASSWORD}\"
This example is incorrect. Here is a correct example:

```shell
export JSONDATA='{"cluster":{"auto_create_topics_enabled":"true"},"node":{"developer_mode":"false"}}'
ansible-playbook ansible/<<<PLAYBOOK NAME>>>.yml --private-key artifacts/testkey -e redpanda="${JSONDATA}"
```

2023-07-07 17:47 UTC, gene-redpanda commented
Added some comments on the comments 😅

2023-07-07 22:34 UTC, hcoyote commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
>      | `distro` | Linux distribution to install. (This affects the `distro_` variables.) Default: `ubuntu-focal` |
We did that before. Let's not go back to that. This is so much easier compared to surfing for the right region-specific ami name.

2023-07-10 19:12 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +\"redpanda_rpk_opts\": \"--user ${MY_USER} --password ${MY_USER_PASSWORD}\"
@gene-redpanda please confirm that this looks correct now!

2023-07-10 19:13 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    | `nodes` | The number of brokers to base the cluster on. Keep in mind that one broker is used as a monitoring broker. Default: `1`|
Correct, that sentence has been wrong since before I got here 😂

2023-07-10 19:13 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `id` | The node ID of the Redpanda instance. This must be unique for each host. |
Can be removed

2023-07-10 19:13 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +| `private_ip` | The private IP address of the machine. This could be the same as the public IP address. |
I'd keep it

2023-07-10 19:15 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +You can specify any available Redpanda configuration value, or set of values, by passing a JSON dictionary as an Ansible `extra-var`. These values are spliced with the calculated configuration and on
You can take the value you'd put for the command line and put it into a hosts file for exactly the same result.

2023-07-10 19:20 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    | `nodes` | The number of brokers to base the cluster on. Keep in mind that one broker is used as a monitoring broker. Default: `1`|
I'll remove "Keep in mind that one node is used as a monitoring node."

2023-07-10 19:36 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +\"redpanda_rpk_opts\": \"--user ${MY_USER} --password ${MY_USER_PASSWORD}\"
Yep looks great!

2023-07-19 16:12 UTC, gene-redpanda approved these changes

2023-07-24 19:07 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> + ansible-playbook --private-key <your-private-key> -i hosts.ini -v ansible/playbooks/provision-basic-cluster.yml
```suggestion
 ansible-playbook --private-key <your-private-key> -v ansible/playbooks/provision-basic-cluster.yml
```

2023-07-24 19:08 UTC, gene-redpanda approved these changes
approved with some fixes for paths

2023-07-26 01:04 UTC, deniscoady commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    cd aws/standard
Is this supposed to be `aws/standard` or just `aws`? I believe I've always used aws/standard but would like to confirm with @gene-redpanda.

2023-07-26 20:22 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    cd aws/standard
aws/standard is what it will be in the new version so I'd like to be correct with that @deniscoady

2023-07-27 21:20 UTC, deniscoady commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    cd aws/standard
> aws/standard is what it will be in the **new version** so I'd like to be correct with that @deniscoady

When is this new version going to be publicly available? I just checked the repo and it's still just `aws/`. I want to make sure that the docs reflect what customers can do now.

2023-07-27 21:50 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    cd aws/standard
agreed, docs are public as soon as we merge, and because of our docs migration we want to merge this by Friday July 28. @gene-redpanda is it OK if I change this back to `aws/`, and we'll update to `aws/standard` when it changes?

2023-07-27 21:58 UTC, gene-redpanda commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    cd aws/standard
That's fine then. I will say it will change probably in the next week -- we're working thru the review process rn.

2023-07-27 22:39 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    cd aws/standard
Sorry to pile on, but this existing section may need updates too: https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/high-availability/#single-az-example

2023-07-28 20:53 UTC, deniscoady commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    cd aws/standard
If it'll be reviewed and ready by next week then I think it's okay. 

cc: @twmb

2023-07-28 20:55 UTC, deniscoady approved these changes

2023-07-28 21:14 UTC, micheleRP commented on docs/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation.mdx
> +    cd aws/standard
Confirmed that we'll merge this now to get this update included. We'll open a new issue to update `aws/standard` when it's ready, as well as any updates required here: https://docs.redpanda.com/docs/deploy/deployment-option/self-hosted/manual/high-availability/#single-az-example.

2023-07-28 21:14 UTC, merged