docs: #1769 what's new page
redpanda-data/documentation pull request #1791
Opened 2023-07-25 15:42 UTC by micheleRP

resolves #1769 

preview: https://deploy-preview-1791--redpanda-documentation.netlify.app/docs/get-started/whats-new/

2023-07-25 22:13 UTC, micheleRP commented
@bpraseed: Please see this small Cloud section in the What's New for 23.2 doc: https://deploy-preview-1791--redpanda-documentation.netlify.app/docs/get-started/whats-new/#repdanda-cloud. Is that messaging correct?

2023-07-26 22:15 UTC, mattschumpert commented on docs/get-started/whats-new.mdx
> +[Follower fetching](../../develop/consume-data/follower-fetching) lets a consumer fetch records from the closest replica of a topic partition, regardless of whether it's a leader or a follower. This
'minimize cloud networking costs'

2023-07-26 23:12 UTC, mattschumpert requested changes

2023-07-26 23:12 UTC, mattschumpert commented on docs/get-started/whats-new.mdx
> +Redpanda offers a new approach to deploying [Redpanda in Kubernetes](../../deploy/deployment-option/self-hosted/kubernetes/kubernetes-production-deployment/). You can choose to use Helm for its simpl
>  or you can combine Helm with the Redpanda Operator to leverage custom resource definitions (CRDs) for a more GitOps-friendly deployment process.

I'm not sure 'more GitOps friendly' is accurate. Helm is dev ops  friendly too.

@joejulian what would you say here.  'you can combine Helm with the Redpanda Operator to leverage additional automation for day 2 operations including self-healing, ....?'

2023-07-26 23:12 UTC, mattschumpert commented on docs/get-started/whats-new.mdx
> +- [`rpk cloud login`](../../reference/rpk/rpk-cloud/rpk-cloud-login/): This allows users to connect to cloud environments by browser.
connect to cloud environments using a browser.

2023-07-26 23:12 UTC, mattschumpert commented on docs/get-started/whats-new.mdx
> +- [Cluster support properties](../../reference/cluster-properties/#support-properties): Two new configuration flags for unsafe string checks.
@micheleRP 'support properties' seems to be the wrong link here (where are the unsafe string checks?). Also these can't be the only two new config properties overall (with all the other features)

2023-07-26 23:12 UTC, mattschumpert commented on docs/get-started/whats-new.mdx
> +To secure Redpanda Console using TLS, you can either let Redpanda Console handle TLS termination or you can offload it to an upstream component, such as a reverse proxy or a Cloud HTTPS LoadBalancer.
@weeco , @vladoschreiner  shouldn't we also document the new-ish AD/Keycload support for console, given it wasn't there in 23.1.1 IIRC?

2023-07-26 23:12 UTC, mattschumpert commented on docs/get-started/whats-new.mdx
> +Redpanda [managed connectors](../../deploy/deployment-option/cloud/managed-connectors/) are fully-managed solutions for integrating different data systems with your real-time clusters in Redpanda Clo
Managed connectors isn't entirely new since 23.1.1 is it @vladoschreiner ? Should we be only highlighting the specific connectors we launched since April?

2023-07-26 23:12 UTC, mattschumpert commented on docs/get-started/whats-new.mdx
> +Redpanda Cloud releases new features on a continuous basis and uptakes Redpanda platform (self-hosted) versions.
@micheleRP  how are we thinking about this "what's new" wrt cloud releases in general. Should we round up and include (but specifically clarify) this is what's new since April 2023 ?  Or something else

wdyt @bpraseed ?

2023-07-26 23:37 UTC, bpraseed commented on docs/get-started/whats-new.mdx
> +Redpanda Cloud releases new features on a continuous basis and uptakes Redpanda platform (self-hosted) versions.
Cloud "what's new" is independent of core release. We will have a separate release announcement next month for that and also have requested @Feediver1 to have a separate doc section for cloud to capture that so we could do something similar to https://www.cockroachlabs.com/docs/releases/cloud or https://docs.snowflake.com/release-notes/new-features

2023-07-26 23:39 UTC, bpraseed commented
> 

We should just highlight the delta of Connectors. Will let @vladoschreiner comment on this.

2023-07-27 02:13 UTC, micheleRP commented on docs/get-started/whats-new.mdx
> +- [Cluster support properties](../../reference/cluster-properties/#support-properties): Two new configuration flags for unsafe string checks.
@mattschumpert I added [those 2 links](https://deploy-preview-1791--redpanda-documentation.netlify.app/docs/get-started/whats-new/#new-commands-and-properties), but I don't think we want to maintain a list of every new/changed command or property in this What's New. In the [Documentation improvements section](https://deploy-preview-1791--redpanda-documentation.netlify.app/docs/get-started/whats-new/#documentation-improvements), we're listing significant doc updates that users may not have noticed. Let me know if there are other properties you want added to this list.

2023-07-27 19:55 UTC, micheleRP commented on docs/get-started/whats-new.mdx
> +Redpanda Cloud releases new features on a continuous basis and uptakes Redpanda platform (self-hosted) versions.
@mattschumpert Do you want to remove the What's New section for Redpanda Cloud, and keep a note at the bottom of the page that Redpanda Cloud releases on a continuous basis?

2023-07-28 14:21 UTC, vladoschreiner commented
> We should just highlight the delta of Connectors. Will let @vladoschreiner comment on this.

@bpraseed which release does this "What's new" refer to? Is it self-hosted 23.2 or general snapshot of new Redpanda's new features since 23.1 was released?

If 23.3:
- [KeyCloak](https://docs.redpanda.com/docs/manage/security/console/keycloak/) and [AD](https://docs.redpanda.com/docs/manage/security/console/azure-ad/) auth for Console
- [Console HTTPS termination](https://docs.redpanda.com/docs/manage/security/console/tls-termination/#use-redpanda-console-for-tls-termination)
- [Self-hosted connectors with MM2](https://github.com/redpanda-data/documentation/pull/1805)

If all new features since 23.1, including cloud:
- New Kafka connect setup & edit experience
- Connectors for Mongo ([import](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-mongodb-source-connector/), [export](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-mongodb-sink-connector/)), [MySQL/Debezium](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-mysql-source-connector/), [PSQL/Debezium](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-postgresql-connector/), JDBC ([import](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-source-connector/), [export](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-sink-connector/))
- [Grafana dashboard](https://github.com/redpanda-data/documentation/pull/1749) to monitor managed connectors
- [Connector log access](https://github.com/redpanda-data/documentation/issues/1641) for troubleshooting in the cloud

2023-07-28 20:13 UTC, micheleRP commented
> > We should just highlight the delta of Connectors. Will let @vladoschreiner comment on this.
> 
> @bpraseed which release does this "What's new" refer to? Is it self-hosted 23.2 or general snapshot of new Redpanda's new features since 23.1 was released?
> 
> If 23.3:
> 
> * [KeyCloak](https://docs.redpanda.com/docs/manage/security/console/keycloak/) and [AD](https://docs.redpanda.com/docs/manage/security/console/azure-ad/) auth for Console
> * [Console HTTPS termination](https://docs.redpanda.com/docs/manage/security/console/tls-termination/#use-redpanda-console-for-tls-termination)
> * [Self-hosted connectors with MM2](https://github.com/redpanda-data/documentation/pull/1805)
> 
> If all new features since 23.1, including cloud:
> 
> * New Kafka connect setup & edit experience
> * Connectors for Mongo ([import](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-mongodb-source-connector/), [export](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-mongodb-sink-connector/)), [MySQL/Debezium](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-mysql-source-connector/), [PSQL/Debezium](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-postgresql-connector/), JDBC ([import](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-source-connector/), [export](https://docs.redpanda.com/docs/deploy/deployment-option/cloud/managed-connectors/create-jdbc-sink-connector/))
> * [Grafana dashboard](https://github.com/redpanda-data/documentation/pull/1749) to monitor managed connectors
> * [Connector log access](https://github.com/redpanda-data/documentation/issues/1641) for troubleshooting in the cloud

@mattschumpert, @bpraseed, @vladoschreiner, @Feediver1: I've removed the Cloud and Console sections from this file. This is the first release that we've included a What's New in our doc. I think going forward, this file should include links to any doc with meaningful customer updates since the last product release (so, next version will cover changes from 23.2 to 23.3). We'll need to have a separate file for Cloud. Please confirm and approve, if this is OK!

2023-07-28 20:30 UTC, micheleRP commented on docs/get-started/whats-new.mdx
> +The new [`leader_balancer_mode`](../../manage/cluster-maintenance/cluster-balancing/#partition-leadership-balancing) property ensures that each shard in a cluster has an equal number of partitions. I
@mattschumpert I added a line about improved data balancing, see https://deploy-preview-1791--redpanda-documentation.netlify.app/docs/get-started/whats-new/#topic-aware-leadership-balancing

2023-07-28 20:57 UTC, joejulian commented on docs/get-started/whats-new.mdx
> +Redpanda offers a new approach to deploying [Redpanda in Kubernetes](../../deploy/deployment-option/self-hosted/kubernetes/kubernetes-production-deployment/). You can choose to use Helm for its simpl
Helm is dev-ops friendly, but gitops is where you check in your declarative state for deployment into your cluster through continuous release.

Since helm is an imperative step, it is not gitops friendly.

CRDs are a standard implementation detail. I feel like mentioning them here is superfluous.

```suggestion
Redpanda offers a new approach to deploying [Redpanda in Kubernetes](../../deploy/deployment-option/self-hosted/kubernetes/kubernetes-production-deployment/). You can choose to use Helm for its simplicity, or you can use the Redpanda Operator for a more GitOps-friendly declarative deployment process. Use either Helm or Operator as suits your needs, both are recommended.
```

2023-07-28 22:30 UTC, micheleRP commented on docs/get-started/whats-new.mdx
> +Redpanda offers a new approach to deploying [Redpanda in Kubernetes](../../deploy/deployment-option/self-hosted/kubernetes/kubernetes-production-deployment/). You can choose to use Helm for its simpl
Thanks, Joe! Committing your suggestion.

2023-07-31 16:04 UTC, micheleRP commented on docs/get-started/whats-new.mdx
> +- [Fine-grained caching](../../manage/tiered-storage/#caching): To support more concurrent consumers of historical data with less local storage, Redpanda can download small chunks of remote segments
Thanks, Evgeny! I've fixed that in the what's new and in the TS page.

2023-07-31 19:25 UTC, mattschumpert approved these changes

2023-07-31 19:25 UTC, mattschumpert commented on docs/get-started/whats-new.mdx
> +Redpanda Cloud releases new features on a continuous basis and uptakes Redpanda platform (self-hosted) versions.
I suggest:

"Redpanda Cloud releases new features on a continuous basis and includes the latest Redpanda platform major version"

2023-07-31 19:37 UTC, mattschumpert commented
@micheleRP 

I think all the Console stuff  SINCE 23.1 SHOULD be included (this is the approach taken for Core as well, even if it came in a patch release this is our window to announce)

The Connectors content should NOT be included if this page is focused on the self-hosted product since we don't have self-manaed connectors yet.

2023-07-31 19:58 UTC, micheleRP commented
> @micheleRP
> 
> I think all the Console stuff SINCE 23.1 SHOULD be included (this is the approach taken for Core as well, even if it came in a patch release this is our window to announce)
> 
> The Connectors content should NOT be included if this page is focused on the self-hosted product since we don't have self-managed connectors yet.
> 
> Unless @vladoschreiner you consider the MM2 self-hosted connector GA (though I see it's doc ticket is still open)

I added a small section for Console enhancements: https://deploy-preview-1791--redpanda-documentation.netlify.app/docs/get-started/whats-new/#redpanda-console-enhancements. Please review and confirm @mattschumpert, @vladoschreiner, @Feediver1

2023-07-31 21:09 UTC, Feediver1 commented on docs/get-started/whats-new.mdx
> +The following new features are included in version 23.2. For a complete list of updates, see the [Redpanda release notes](https://github.com/redpanda-data/redpanda/releases/tag/v23.2.1).
After reading this, my first question is--what is the difference between this and Rns? If RNs are a complete list of updates, is this an incomplete list? I think the distinction is important/should be clear. 

How about: This topic includes new content added in version 23.2. For a complete list of all product updates, see..."

^^ This gives us more latitude for additions not specific to the version (I know you have a section for that here).

Thoughts?

2023-07-31 21:12 UTC, Feediver1 commented on docs/get-started/whats-new.mdx
> +- [Fine-grained caching](../../manage/tiered-storage/#caching): To support more concurrent consumers of historical data with less local storage, Redpanda can download small chunks of remote segments
Looking at the content in the link, and it's just called "caching"--where/why does the "fine-grained" come in?

2023-07-31 21:15 UTC, Feediver1 commented on docs/get-started/whats-new.mdx
> +- [Automatic disk space management](../../manage/cluster-maintenance/disk-utilization/#local-storage-housekeeping): Redpanda now divides disk storage into different categories to provide a flexible c
Same here--the terminology for the link does not match the terms used in the link destination.

Reason I'm asking about these is that consistency regarding what we call these bits is important. Is it fine-grained caching or just caching? Automatic disk space management, or just local storage housekeeping?

2023-07-31 21:16 UTC, Feediver1 commented on docs/get-started/whats-new.mdx
> +Redpanda now lets you [delete data from the beginning of a partition up to a specific offset](../../develop/config-topics/#delete-records-from-a-topic). The offset represents the true creation time o
```suggestion
Redpanda enables you to [delete data from the beginning of a partition up to a specific offset](../../develop/config-topics/#delete-records-from-a-topic). The offset represents the true creation time of the event, not the time when it was stored by Redpanda. Deleting records frees up space in local disk and in object storage, which is especially helpful if your producers are pushing more data than you anticipated when sizing your storage infrastructure, or if you want to implement a data retention policy aligned with a particular business event and not based on age or size. There are different ways to delete records from a topic, including using the `rpk topic trim` command or using the DeleteRecords Kafka API with Kafka clients.
```

2023-07-31 21:18 UTC, micheleRP commented on docs/get-started/whats-new.mdx
> +Redpanda [managed connectors](../../deploy/deployment-option/cloud/managed-connectors/) are fully-managed solutions for integrating different data systems with your real-time clusters in Redpanda Clo
managed connectors will go in What's New in Redpanda Cloud.

2023-07-31 21:32 UTC, micheleRP commented on docs/get-started/whats-new.mdx
> +- [Fine-grained caching](../../manage/tiered-storage/#caching): To support more concurrent consumers of historical data with less local storage, Redpanda can download small chunks of remote segments
@mattschumpert @redpanda-data/cloud-ring0 the announcement blog calls these feature fine-grained caching and automatic disk space management. Our docs, which have been reviewed/approved, called these in our docs "caching" and "local storage housekeeping". Should we change the docs now to match this messaging? Or is the inconsistency OK?

2023-07-31 21:38 UTC, Feediver1 commented on docs/get-started/whats-new.mdx
> +- [Fine-grained caching](../../manage/tiered-storage/#caching): To support more concurrent consumers of historical data with less local storage, Redpanda can download small chunks of remote segments
@mattschumpert Consistency wrt nomenclature is paramount in our product docs. We cannot call these features two different things. I've asked @micheleRP to pick one name and stick with it throughout our docs. It appears that she had to cull through 7 different sources to get to this point/come up with the definitive list of features (another issue altogether). For now, please weigh in on a single name for these two features--that is what we will go with in the docs. Thanks!

2023-07-31 22:33 UTC, mattschumpert commented on docs/get-started/whats-new.mdx
> +- [Fine-grained caching](../../manage/tiered-storage/#caching): To support more concurrent consumers of historical data with less local storage, Redpanda can download small chunks of remote segments
Much of this is by design.  The context of 'what's new' (existing user upgrading) is slightly different from someone learning the product for the first time, so there is bound to be a little dissonance. 

1. Caching

 To an existing user trying to digest what's new it's 'more fine grained' than it used to be.  To a new user, they just want to understand how the TS cache works in general and they have no understanding of the previous behavior (where we cached by segment). , so this is 'caching'. Its absolutely correct that it's under the 'caching' docs topic in describing how the product works if learning it for the first time. It's also correct for out blogs and what's new to say 'fine-grained caching' or perhaps better 'finer grained caching'.

For this audience, let's go with 'finer-grained caching'.

2. On the disk space management , similar situation. We've always had local storage housekeeping (removing expired data), now housekeeping just functions in a way that's more automatic. It's the 'automatic' that's the new part.

However, to bridge the gap here, and as the new docs content covers a bit more than just the housekeeping process. let's rename the docs sub-section "l[ocal storage housekeeping](https://docs.redpanda.com/docs/manage/cluster-maintenance/disk-utilization/#local-storage-housekeeping)" to  just "Space management". It's already in a 'manage disk space' page which is by definition about local disk, and 'space management' more accurately covers this section and is more aligned.

2023-07-31 23:45 UTC, micheleRP commented on docs/get-started/whats-new.mdx
> +The following new features are included in version 23.2. For a complete list of updates, see the [Redpanda release notes](https://github.com/redpanda-data/redpanda/releases/tag/v23.2.1).
thanks, I've updated to this!

2023-08-01 00:02 UTC, micheleRP commented on docs/get-started/whats-new.mdx
> +- [Fine-grained caching](../../manage/tiered-storage/#caching): To support more concurrent consumers of historical data with less local storage, Redpanda can download small chunks of remote segments
Thanks @mattschumpert, makes sense. I've updated the what's new page to use "finer-grained caching" and I've changed the "Local storage housekeeping" heading (in the Disk Management page) to "Space management".

2023-08-01 13:36 UTC, vladoschreiner commented
> Unless @vladoschreiner you consider the MM2 self-hosted connector GA (though I see it's doc ticket is still open)

The feature is ready. We're waiting for docs. My guidance on what to include in What's new:
- Include the self-hosted docker image. Prioritize merging the docs. The feature is ready and the docs are just waiting for a review. https://github.com/redpanda-data/documentation/pull/1805
- Don't include self-hosted MM2. The docs are missing. https://github.com/redpanda-data/documentation/issues/1642

2023-08-01 20:02 UTC, Feediver1 approved these changes
Thanks for this @micheleRP

2023-08-02 04:00 UTC, micheleRP commented
> > Unless @vladoschreiner you consider the MM2 self-hosted connector GA (though I see it's doc ticket is still open)
> 
> The feature is ready. We're waiting for docs. My guidance on what to include in What's new:
> 
> * Include the self-hosted docker image. Prioritize merging the docs. The feature is ready and the docs are just waiting for a review. [Docs: added self-managed connectors docker image documentation #1805](https://github.com/redpanda-data/documentation/pull/1805)
> * Don't include self-hosted MM2. The docs are missing. [Self-managed mirrormaker2 connector #1642](https://github.com/redpanda-data/documentation/issues/1642)

Added connector Docker image: https://deploy-preview-1791--redpanda-documentation.netlify.app/docs/get-started/whats-new/#redpanda-console-enhancements

2023-08-02 04:00 UTC, merged