Redpanda Cloud-platform compatibility
redpanda-data/documentation pull request #1795
Opened 2023-07-25 21:01 UTC by Feediver1

Fixes #1613

2023-07-25 21:32 UTC, mattschumpert commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Follower fetching (available only in dedicated, VPC-peered clusters)
@bpraseed  is this correct (assuming 23.2?) Why isn't it available for BYOC customers?

2023-07-25 21:32 UTC, mattschumpert commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Admin API
@bpraseed and should we say (any RPK commands that depend on the admin aPI)/

2023-07-25 21:37 UTC, mattschumpert commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Follower fetching (available only in dedicated, VPC-peered clusters)
@Feediver1  just chatted with praseed. With 23.2 this IS available for BOTH  BYOC and Dedicated

2023-07-25 21:39 UTC, mattschumpert requested changes

2023-07-25 21:39 UTC, mattschumpert commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Admin API
@twmb to make this more intuitive for cloud users, should we not call out specific command groupings (e.g. rpk admin, rpk user, rpk cluster) which are non-functional in Cloud due to lack of Admin API.   Seems like a good opportunity to add some clarity here .   If so, do you have the list at hand (e.g. anything beginning with rpk foo,bar, if its that simple)

2023-07-26 18:08 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Follower fetching (available only in dedicated, VPC-peered clusters)
Thanks @mattschumpert ! I will remove. 
FYI @rkruze I know this came up in a recent POC and the doc update was requested--looks like it is no longer the case.

2023-07-26 22:23 UTC, twmb commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Admin API
There is no hard rule, and the rule is being bent a bit more as we add more and more to redpanda & rpk.
`rpk cluster` is mostly admin commands, minus `rpk cluster metadata` and `rpk cluster logdirs` and in the future, `rpk cluster txns`.

`rpk redpanda` is mostly admin api.

`rpk topic` is almost entirely Kafka api, minus `rpk topic describe-storage`.

`rpk group` is entirely Kafka api.

`rpk acl` is mostly Kafka api, minus `rpk acl user` which is admin api.

`rpk cloud` is cloud api.

`rpk container` talks to docker.

`rpk generate app` is a bit of a mix, cloud api or admin api and Kafka api.

This is why https://github.com/redpanda-data/redpanda/issues/8972 is important.

2023-08-01 14:09 UTC, twmb commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk cluster health`
`rpk cluster` contains a lot:
```
Available Commands:
  config      Interact with cluster configuration properties
  health      Queries cluster for health overview
  license     Manage cluster license
  logdirs     Describe log directories on Redpanda brokers
  maintenance Toggle a node's maintenance mode
  metadata    Request broker metadata
  partitions  Manage cluster partitions
  self-test   Start, stop and query runs of Redpanda self-test through the Admin API listener
  storage     Manage the cluster storage
```
the only one that does _not_ speak the admin API is `rpk cluster metadata`.

2023-08-01 14:09 UTC, twmb commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk container`
Everybody can use `rpk container` since it speaks to the local docker daemon

2023-08-01 14:11 UTC, twmb commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk group`
`rpk group` always uses the kafka api

2023-08-01 14:11 UTC, twmb commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk topic`
`rpk topic` almost always use the kafka api, except `rpk topic describe-storage`

2023-08-01 14:11 UTC, twmb commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk user`
`rpk acl user` uses the admin api (missing acl here)

2023-08-01 14:11 UTC, twmb commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk user`
Actually, this is the first bullet point -- `rpk user` doesn't exist

2023-08-01 20:40 UTC, hcoyote commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Remote Read Replicas (including Azure Blob Storage)
Is RRR only unsupported on ABS or do we not support it yet with BYOC across all clouds? Not sure how to read this.

2023-08-02 20:49 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Remote Read Replicas (including Azure Blob Storage)
@mattschumpert ?

2023-08-04 22:33 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk container`
Thx @twmb . Removed it here.

2023-08-04 22:35 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk generate app`
Hmmmm...sounds like either I should remove it here, OR, describe the use case with missing flags that impacts its use. Please advise @mattschumpert

2023-08-04 22:37 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk group`
removing here...

2023-08-04 22:42 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Remote Read Replicas (including Azure Blob Storage)
https://redpandadata.slack.com/archives/C0191NM4WU9/p1691188942354009

2023-08-04 22:46 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk cluster health`
added all except `rpk cluster metadata`

2023-08-05 01:43 UTC, splittingfield commented
If helpful, as part of our onboarding I have created this [sheet](https://docs.google.com/spreadsheets/d/1ki32DTo49lF-3kLKd6akOpLM7yNvyCkEGv5ap4ZOilY/edit) on my own that includes my current understanding of various support. In particular I point out loss of functionality around redpanda console such as managing remote Kafka connect clusters as well as the ability to run our own console to work around this.

2023-08-07 15:08 UTC, twmb commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +  - `rpk cluster health`
`rpk cluster logdirs` speaks the Kafka API as well -- my mistake, I forgot. We'll also be adding `rpk cluster txns` next release, which is the Kafka API.

2023-08-07 19:21 UTC, Feediver1 commented on docs/deploy/deployment-option/cloud/cloud-overview.mdx
> +- Remote Read Replicas (including Azure Blob Storage)
According to @c4milo , all contexts (ABS and BYOC). See https://redpandadata.slack.com/archives/C0191NM4WU9/p1691188942354009

2023-08-07 22:00 UTC, rkruze approved these changes

2023-08-08 20:44 UTC, merged