docs: Deprecated Operator migration guide
redpanda-data/documentation pull request #1806
Opened 2023-07-28 13:54 UTC by JakeSCahill

Review deadline: July 31

- Removed any cautions about Operator being in beta.
- Added migration guide for Operator v1 to v2.
- Added rollback steps for Helm to Operator migration guide.
- Added more troubleshooting steps for migration guides.

2023-07-31 15:16 UTC, JakeSCahill commented on docs/upgrade/migrate/kubernetes/operator.mdx
> +  kubectl describe helmrelease redpanda --namespace <namespace>
```suggestion
  kubectl describe helmrelease <cluster-name> --namespace <namespace>
```

2023-07-31 19:26 UTC, alejandroEsc reviewed
lgtm. This captures the procedure. I would like to emphasis the parts where we ask the user to test this process in another cluster if possible and futher to emphasis that they need to manually make changes to their Redpanda resources, like adding a secret for sasl and editing the sasl lines in order to have sasl in their cluster. These sort of changes are not made by the migration code, so they must be manual.

2023-07-31 19:26 UTC, alejandroEsc commented on docs/upgrade/migrate/kubernetes/operator.mdx
> +The deprecated Redpanda Operator is now managing your resources.
You can add here: Any changes made will be undone and resources that were delete should be once again applied.

2023-08-01 06:15 UTC, JakeSCahill commented on docs/upgrade/migrate/kubernetes/operator.mdx
> +  This step prevents you from experiencing downtime by making sure the Services do not get redeployed. The names of these Services match the names of the Services that the Redpanda Helm chart will tr
```suggestion
  This step prevents Services from being redeployed, which reduces downtime. Because the names of these Services match the names of the Services that the Redpanda Helm chart will try to deploy, these annotations and labels bring the existing Services under the management of Helm so that they do not get deleted and redeployed when you apply the Redpanda resource.
```

2023-08-01 12:44 UTC, JakeSCahill commented on docs/upgrade/migrate/kubernetes/operator.mdx
> +The deprecated Redpanda Operator is now managing your resources.
```suggestion
The deprecated Redpanda Operator is now managing your resources. Any changes that the Redpanda Operator made to your deployment will be undone and any resources that you deleted will be reapplied.
```

2023-08-03 12:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redpanda-data/documentation?pullRequest=1806) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/redpanda-data/documentation?pullRequest=1806) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: JakeSCahill<br/>:x: alejandroEsc<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redpanda-data/documentation?pullRequest=1806) it.</sub>

2023-08-03 13:03 UTC, JakeSCahill commented on docs/upgrade/shared/install-migration-cli/_install-migration-cli-linux.mdx
> +      ```
```suggestion
1. Download the `cluster-to-redpanda-migration` archive for Linux:

      ```bash
      curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/cluster-to-redpanda-migration-linux-amd64.zip
      ```
```

2023-08-03 13:04 UTC, JakeSCahill commented on docs/upgrade/shared/install-migration-cli/_install-migration-cli-macos.mdx
> +      ```
```suggestion
1. Download the `cluster-to-redpanda-migration` archive for macOS:

      ```bash
      curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/cluster-to-redpanda-migration-darwin-amd64.zip
      ```
```

2023-08-03 17:34 UTC, JakeSCahill commented on docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-production-deployment.mdx
> +- `metadata.name`: Name to assign the Redpanda cluster.
```suggestion
- `metadata.name`: Name to assign the Redpanda cluster. This name is also assigned to the Helm release.
```

2023-08-03 17:34 UTC, JakeSCahill commented on docs/upgrade/migrate/kubernetes/operator.mdx
> +When you find and fix the error, you must use the Flux CLI, `fluxctl`, to suspend and resume the reconciliation process:
```suggestion
When you find and fix the error, you must use the Flux CLI to suspend and resume the reconciliation process:
```

2023-08-03 17:34 UTC, JakeSCahill commented on docs/upgrade/migrate/kubernetes/operator.mdx
> +1. [Install Flux CLI](https://fluxcd.io/flux/installation/#install-the-flux-cli).
```suggestion
1. [Install the Flux CLI](https://fluxcd.io/flux/installation/#install-the-flux-cli).
```

2023-08-07 23:45 UTC, joejulian commented on docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-deploy.mdx
> +  kubectl --namespace <namespace> rollout status -w deployment/redpanda-controller-operator
personally, I always like seeing long-form flags in documentation. It's easier to know what they're doing.

2023-08-07 23:47 UTC, joejulian approved these changes
lgtm

2023-08-08 00:01 UTC, joejulian commented
![giphy](https://github.com/redpanda-data/documentation/assets/952828/1e04a4b9-85d8-4fe5-a380-7c85646d0443)

2023-08-08 02:30 UTC, JakeSCahill commented on docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-deploy.mdx
> +  kubectl --namespace <namespace> rollout status -w deployment/redpanda-controller-operator
```suggestion
  kubectl --namespace <namespace> rollout status --watch deployment/redpanda-controller-operator
```

2023-08-08 14:58 UTC, Feediver1 commented on docs/upgrade/deprecated/cluster-resource.mdx
> +    the Cluster and Console custom resources are deprecated and replaced by the Redpanda custom resource."/>
Does **Cluster** need init cap here? I know it is in the heading link that brings readers here, but I don't think it needs to be uc here.

2023-08-08 14:59 UTC, Feediver1 commented on docs/upgrade/deprecated/cluster-resource.mdx
> +|The Cluster custom resource was used to configure and deploy Redpanda clusters, while the Console custom resource was used to configure and deploy Redpanda Console.| The Redpanda custom resource is
Throughout--don't think you need uc for cluster.

2023-08-08 15:25 UTC, alejandroEsc requested changes
A few changes, are needed, specifically redpanda resource and the versions need to be updated. Looking good.

2023-08-08 15:25 UTC, alejandroEsc commented on docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-production-deployment.mdx
> +spec:
```suggestion
spec:
  chartRef:
    helmRepositoryName:
  clusterSpec:
```

or 

```
spec:
  chartRef:
  clusterSpec:
```

And this occurs in a few places, missed the missing indentation earlier. The point here should be that we have two very distinct fields that make your deployment easy to understand. The first how and where your configuration for the cluster comes from, how to handle lifecycle etc.. and the clusterSpec is the what. The cluster specific you are trying to build.

2023-08-08 15:25 UTC, alejandroEsc commented on docs/upgrade/migrate/kubernetes/operator.mdx
> +    --set image.tag=v23.2.2 \
```suggestion
    --set image.tag=v23.2.4 \
```

2023-08-08 18:55 UTC, joejulian commented on docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-deploy.mdx
> +  kubectl --namespace <namespace> rollout status --watch deployment/redpanda-controller-operator
We were assigned this by the Bureau of Repetitive Redundancy Administration.

But seriously, the `-operator` comes from the chart. The `redpanda-controller` comes from the release name. I'm not sure any other name we could select wouldn't cause confusion.

2023-08-08 19:18 UTC, joejulian commented on docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-production-deployment.mdx
> +  clusterSpec:
@alejandroEsc did you know you can do multi-line suggestions by dragging the blue plus downward?

```suggestion
spec:
  chartRef:
    helmRepositoryName:
  clusterSpec:
```

2023-08-08 19:19 UTC, joejulian commented on docs/upgrade/deprecated/cluster-resource.mdx
> +    the Cluster and Console custom resources are deprecated and replaced by the Redpanda custom resource."/>
These are the proper names of resources. They're treated as proper nouns so as not to confuse them with the generic term.

2023-08-09 10:12 UTC, merged