Update memory per core to 4 GB
redpanda-data/documentation pull request #196
Opened 2023-12-19 18:02 UTC by JakeSCahill

The latest guidance is 4 GB per core of memory for production deployments.

2023-12-19 18:36 UTC, vuldin approved these changes
LGTM

2023-12-19 20:09 UTC, Feediver1 approved these changes
lgtm

2023-12-20 15:26 UTC, JakeSCahill commented
Waiting for @mattschumpert and @piyushredpanda to confirm whether we want this change.

2023-12-20 17:38 UTC, hcoyote commented
HOld off making this change, we're discussing with perf team a nuance around this.

2023-12-20 18:35 UTC, mattschumpert commented
@JakeSCahill cancel this numerical change, but lets add a 'Requirements' heading just above the existing mem/cpu stuff to compliments the the 'Recommendations' (where we suggest 4 cores).

2023-12-21 16:06 UTC, mattschumpert requested changes
Not sure if you want to use the same PR or not. but 

- We're not adding 4GB / core requirement
- it would be good to lavel the bulleted items are 'Requirements' as the lower one about 4 cores is a 'Recommendation'

2023-12-21 16:11 UTC, JakeSCahill commented
> Not sure if you want to use the same PR or not. but
> 
> * We're not adding 4GB / core requirement
> * it would be good to lavel the bulleted items are 'Requirements' as the lower one about 4 cores is a 'Recommendation'

Done

2023-12-21 18:09 UTC, mattschumpert approved these changes

2023-12-21 18:21 UTC, merged