Add max_transactions__per_coordinator to properties reference
redpanda-data/documentation pull request #243
Opened 2024-01-11 19:44 UTC by Feediver1

This PR fixes doc [issue-2097](https://github.com/redpanda-data/documentation-private/issues/2097).

While it's great we adding this missing prop to the doc, would be ideal if we could also mention it in the appropriate contexts, along with any other specific guidance on its use. Thx.

2024-01-12 15:50 UTC, JFlath requested changes
I was actually under the impression the default was lower, I have my suspicions that we might want to actually lower this in future, it might be nice to have Core's take on things.

It's also important to call out that as this is *per coordinator*, the total number of txns in the cluster at any one time is `max_transactions_per_coordinator` * `transaction_coordinator_partitions` (which is now by default `50`). Perhaps `configuration.cc` should say the same actually - not sure what the preference is on having differences between docs and that file.

In terms of context, I think this is important to mention wherever we talk about running transactional workloads from clients. One particular gotcha is that this must be tuned to ~the expected number of *active* transactions that a user's clients will be running at any one time if they use clients where transaction ids are *not* reused.

That is, if you have this at default and then your clients make a new id for every transaction, you just keep adding more and never removing, and that bloats memory. By default I believe Flink works in this way.

2024-01-12 15:50 UTC, JFlath commented on modules/reference/pages/cluster-properties.adoc
> +*Default*: true
The default is actually `std::numeric_limits<uint64_t>::max()`, i.e. `9223372036854775807` or functionally unlimited.

2024-01-12 17:39 UTC, JFlath approved these changes

2024-01-12 19:58 UTC, micheleRP commented on modules/develop/pages/transactions.adoc
> +* When upgrading, make sure to use maintenance mode with xref:manage:cluster-maintenance/rolling-upgrade.adoc[rolling upgrades].
You could instead make rolling upgrade a [glossterm link](https://deploy-preview-243--redpanda-docs-preview.netlify.app/current/reference/glossary/#rolling-upgrade) or have the link go direct to the [rolling upgrade section](https://deploy-preview-243--redpanda-docs-preview.netlify.app/current/upgrade/rolling-upgrade/#perform-a-rolling-upgrade)?

2024-01-12 20:03 UTC, micheleRP commented on modules/develop/pages/transactions.adoc
> +* When running transactional workloads from clients, it is recommended that you tune xref:reference:cluster-properties#max_transactions_per_coordinator[`max_transactions_per_coordinator`] to the expe
```suggestion
* When running transactional workloads from clients, tune xref:reference:cluster-properties#max_transactions_per_coordinator[`max_transactions_per_coordinator`] to the expected number of active transactions that your clients are running at any given time (if your client transaction IDs are not reused). The total number of transactions in the cluster at any one time is `max_transactions_per_coordinator * transaction_coordinator_partitions` (default is 50). When the threshold is exceeded, Redpanda terminates old sessions. If an idle producer corresponding to the terminated session wakes up and produces, its batches are rejected with the message `invalid producer epoch` or `invalid_producer_id_mapping`, depending on where it is in the transaction execution phase.
```

2024-01-12 20:09 UTC, micheleRP commented on modules/develop/pages/transactions.adoc
> +Be aware that if you use the default and your clients create a new ID for every transaction, this will continue to accumulate and never remove, which will bloat memory.
```suggestion
Be aware that if you keep the default as 50 and your clients create a new ID for every transaction, the total continues to accumulate, which bloats memory.
```
I don't completely understand this bullet. Not positive, but this is my suggested text.

2024-01-12 20:14 UTC, micheleRP approved these changes
left some suggestions, but looks good!

2024-01-15 09:23 UTC, mmaslankaprv approved these changes

2024-01-23 19:35 UTC, micheleRP commented on modules/develop/pages/transactions.adoc
> +* When upgrading, make sure to use maintenance mode with xref:manage:cluster-maintenance/rolling-upgrade.adoc[rolling upgrades].
```suggestion
* When upgrading, make sure to use maintenance mode with a glossterm:rolling upgrade[].
```

2024-01-23 19:43 UTC, merged