add note about broker properties restart
redpanda-data/documentation pull request #556
Opened 2024-06-14 16:23 UTC by Deflaimun

## Description

Resolves https://github.com/redpanda-data/documentation-private/issues/2542
Review deadline:

## Page previews

## Checks

- [ ] New feature
- [ ] Content gap
- [ ] Support Follow-up
- [ ] Small fix (typos, links, copyedits, etc)

2024-06-14 16:31 UTC, micheleRP commented on modules/reference/pages/properties/broker-properties.adoc
> +NOTE: Modifying a broker property requires that you restart Redpanda for your changes to take effect.
```suggestion
NOTE: All broker property require that you restart Redpanda for any update to take effect.
```

2024-06-14 16:33 UTC, micheleRP commented on modules/reference/pages/properties/broker-properties.adoc
> +NOTE: Modifying a broker property requires that you restart Redpanda for your changes to take effect.
@Deflaimun Let's put a similar NOTE on the cluster properties page and the object storage properties page:

- NOTE: Some cluster properties require that you restart Redpanda for any update to be applied. 
- NOTE: Some object storage properties require that you restart Redpanda for any update to be applied. 

And is it correct that no topic properties require restart?

2024-06-17 19:22 UTC, Deflaimun commented
Related conversation 
https://redpandadata.slack.com/archives/C04LYNJQUGN/p1718388434136009

2024-06-17 20:14 UTC, kbatuigas requested changes
Just one typo to fix!

2024-06-17 20:14 UTC, kbatuigas commented on modules/reference/pages/properties/broker-properties.adoc
> +NOTE: All broker property require that you restart Redpanda for any update to take effect.
```suggestion
NOTE: All broker properties require that you restart Redpanda for any update to take effect.
```

2024-06-17 20:23 UTC, kbatuigas approved these changes

2024-06-17 21:12 UTC, merged