Explain the difference between helm install and helm upgrade
redpanda-data/documentation pull request #675
Opened 2024-08-06 16:17 UTC by JakeSCahill

## Description

Resolves https://github.com/redpanda-data/documentation-private/issues/2608
Review deadline: 9 August

## Page previews

## Checks

- [ ] New feature
- [ ] Content gap
- [x] Support Follow-up
- [ ] Small fix (typos, links, copyedits, etc)

2024-08-06 19:52 UTC, RafalKorepta approved these changes

2024-08-07 12:39 UTC, JakeSCahill commented on modules/manage/pages/kubernetes/k-configure-helm-chart.adoc
> +When reinstalling Redpanda with `helm install`, cluster configuration overrides specified in the Helm values may not take effect due to PersistentVolumeClaim (PVC) retention. By default, most PVCs ar
```suggestion
When reinstalling Redpanda with `helm install`, cluster configuration overrides specified in the Helm values may not take effect due to PersistentVolumeClaim (PVC) retention. By default, most PVCs are retained when a Helm release is uninstalled. As a result, when Redpanda is reinstalled, the previously created PVCs are adopted, restoring the state of the previous cluster. This adoption results in the new `bootstrap.yaml` file being ignored and the `post_upgrade` job not running. The `post_upgrade` job is a component in the Helm chart that ensures the application of configuration overrides during an upgrade.
```

2024-08-07 12:40 UTC, JakeSCahill commented on modules/manage/pages/kubernetes/k-configure-helm-chart.adoc
> +=== Reinstall Redpanda with `helm install`
```suggestion
=== Reinstall Redpanda
```

2024-08-07 12:40 UTC, JakeSCahill commented on modules/manage/pages/kubernetes/k-configure-helm-chart.adoc
> +=== Configure an existing cluster with `helm upgrade`
```suggestion
=== Configure an existing cluster
```

2024-08-07 12:41 UTC, JakeSCahill commented on modules/manage/pages/kubernetes/k-configure-helm-chart.adoc
> +When managing Redpanda deployments with Helm, it's important to understand the differences between `helm install` and `helm upgrade`, particularly in how they handle cluster configuration overrides.
```suggestion
When managing Redpanda deployments with Helm, it's important to understand the differences between `helm install` and `helm upgrade`, particularly in how they handle cluster configuration overrides.

Use `helm install` to install or reinstall Redpanda. Use `helm upgrade` to reconfigure an existing deployment.
```

2024-08-07 12:44 UTC, asimms41 commented on modules/manage/pages/kubernetes/k-configure-helm-chart.adoc
> +When reinstalling Redpanda with `helm install`, cluster configuration overrides specified in the Helm values may not take effect due to PersistentVolumeClaim (PVC) retention. By default, most PVCs ar
```suggestion
When reinstalling Redpanda with `helm install`, cluster configuration overrides specified in the Helm values may not take effect due to PersistentVolumeClaim (PVC) retention. 

By default, most PVCs are retained when a Helm release is uninstalled. As a result, when Redpanda is reinstalled, the previously created PVCs are adopted, restoring the state of the previous cluster. This adoption results in the new `bootstrap.yaml` file being ignored and the `post_upgrade` job not running. The `post_upgrade` job is a component in the Helm chart that applies configuration overrides during an upgrade.
```

2024-08-07 12:46 UTC, asimms41 commented on modules/manage/pages/kubernetes/k-configure-helm-chart.adoc
> +During a `helm upgrade`, the `post_upgrade` job is triggered, ensuring that the latest overrides are applied to the cluster.
```suggestion
During a `helm upgrade`, the `post_upgrade` job is triggered, which applies the latest overrides to the cluster.
```

2024-08-07 12:50 UTC, asimms41 commented on modules/manage/pages/kubernetes/k-configure-helm-chart.adoc
> +. Delete the existing PVCs before re-installing Redpanda:
```suggestion
. Delete the existing PVCs before reinstalling Redpanda:
```

2024-08-07 12:50 UTC, asimms41 requested changes
Looks great! Just a couple of suggestions.

2024-08-07 13:56 UTC, chrisseto approved these changes
Beautifully crafted 🎉 Thanks Jake!

2024-08-07 14:34 UTC, asimms41 approved these changes
Looks great! Thanks for the updates.

2024-08-07 15:39 UTC, merged