docs: include rpk install instructions
redpanda-data/documentation pull request #705
Opened 2022-10-11 20:50 UTC by Deflaimun

Resolves #698

Preview:

2022-10-11 20:52 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-linux-amd64.zip
@daisukebe can you review this link? I'm not sure what's the correct one for fedora/red hat

2022-10-12 02:09 UTC, daisukebe commented on docs/quickstart/rpk-install.mdx
> +curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-linux-amd64.zip
It just works in Fedora (or RH/CentOS) in the same way too. Confirmed below.

```
$ docker pull fedora:37
$ docker run --rm -ti fedora:37 bash
[root@9735e26ae11f /]# curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-linux-
[root@9735e26ae11f /]# sudo yum install unzip -y
[root@9735e26ae11f /]# unzip rpk-linux-amd64.zip
[root@9735e26ae11f /]# ./rpk --help
rpk is the Redpanda CLI & toolbox

Usage:
  rpk [command]

Available Commands:
  acl         Manage ACLs and SASL users
  cluster     Interact with a Redpanda cluster
  container   Manage a local container cluster
  debug       Debug the local Redpanda process
  generate    Generate a configuration template for related services
  group       Describe, list, and delete consumer groups and manage their offsets
  help        Help about any command
  iotune      Measure filesystem performance and create IO configuration file
  plugin      List, download, update, and remove rpk plugins
  redpanda    Interact with a local Redpanda process
  topic       Create, delete, produce to and consume from Redpanda topics
  version     Check the current version
  wasm        Deploy and remove inline WASM engine scripts

Flags:
  -h, --help      Help for rpk
  -v, --verbose   Enable verbose logging (default: false)

Use "rpk [command] --help" for more information about a command.
```

2022-10-12 02:11 UTC, daisukebe commented on docs/quickstart/rpk-install.mdx
> +Download the `rpk` archive for Ubuntu with:
Not `Ubuntu` specific. This is for any Linux distributions. @twmb , correct?

2022-10-12 02:19 UTC, daisukebe commented on docs/quickstart/rpk-install.mdx
> +It is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with rpk easily using the tab button. Please review th
Regarding autocompletion, I think we should link to https://docs.redpanda.com/docs/reference/rpk/rpk-generate/rpk-generate-shell-completion

2022-10-12 02:20 UTC, daisukebe commented on docs/quickstart/rpk-install.mdx
> +As mentioned above, `rpk` is a single binary application.
Not sure this introduction is required in our doc. Could you advise, @Feediver1?

2022-10-12 15:55 UTC, Feediver1 commented on docs/quickstart/rpk-install.mdx
> +As mentioned above, `rpk` is a single binary application.
I think we can make this less "sales-y":

As mentioned previously, `rpk` is a single binary application, and designed to be an easy-to-use CLI for developers  who need to build, maintain, and debug a production streaming system using Redpanda.

2022-10-12 15:56 UTC, Feediver1 commented on docs/quickstart/rpk-install.mdx
> +As mentioned above, `rpk` is a single binary application.
^^ @Deflaimun

2022-10-12 15:57 UTC, Feediver1 commented on docs/quickstart/rpk-install.mdx
> +As mentioned above, `rpk` is a single binary application.
```suggestion
As mentioned previously, `rpk` is a single binary application, and designed to be an easy-to-use CLI for developers who need to build, maintain, and debug a production streaming system using Redpanda. 
```

2022-10-12 15:58 UTC, Feediver1 commented on docs/quickstart/rpk-install.mdx
> +It is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with rpk easily using the tab button. Please review th
```suggestion
It is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with `rpk` easily using the tab button. For details, see [rpk documentation](../../reference/rpk/).
```

2022-10-12 15:58 UTC, Feediver1 commented on docs/quickstart/rpk-install.mdx
> +To install `rpk` bundled with Redpanda, check our [60-Second guides](../).
```suggestion
To install `rpk` bundled with Redpanda, refer to the [60-Second guides](../).
```

2022-10-12 15:59 UTC, Feediver1 commented on docs/quickstart/rpk-install.mdx
> +It's also possible to install the `rpk` binary independently.
```suggestion
You can also install the `rpk` binary independently. 
```

2022-10-12 16:00 UTC, Feediver1 commented on docs/quickstart/rpk-install.mdx
> +
```suggestion
After it’s completed, run `rpk version`, which shows the rpk binary version, not the Redpanda server version.

```

2022-10-12 16:01 UTC, Feediver1 approved these changes
See updates I've added.

Once the SMEs approve for accuracy, good to go.
Thanks @Deflaimun

2022-10-13 16:56 UTC, r-vasquez commented on docs/quickstart/rpk-install.mdx
> +Download the `rpk` archive for Ubuntu with:
Yes, thanks @daisukebe

2022-10-13 18:03 UTC, r-vasquez commented on docs/quickstart/rpk-install.mdx
> +
If we suggest they move the binary to a location in their `$PATH` can we give the full one-line command?

```bash
unzip rpk-linux-amd64.zip -d /usr/local/bin/
```

2022-10-14 16:18 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-linux-amd64.zip
Nice, thanks !

2022-10-14 16:19 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +
Thanks @r-vasquez

2022-10-14 16:22 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +As mentioned above, `rpk` is a single binary application.
Resolved with @Feediver1 review.

2022-10-14 18:03 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +It is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with rpk easily using the tab button. Please review th
Good idea. Thanks !

2022-10-14 18:03 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +Download the `rpk` archive for Ubuntu with:
Nice.

2022-10-14 18:08 UTC, Deflaimun commented
@r-vasquez @daisukebe the feedback points have been addressed. Thank you for your input !

2022-10-14 21:20 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +`rpk` is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with easily using the tab button. For details, see
I think "with the Redpanda broker" may be a bit odd -- I'd change it to (and merge the rest of the sentence with)" `with any Redpanda package`.

`It also` seems like an odd way to me to start a sentence, and this is a random spot to mention autocompletion. Most people forget about the autocompletion though, so it's good to have here -- the sentence just feels a bit awkward. Unfortunately, I don't have a good alternative.

2022-10-14 21:24 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +unzip rpk-linux-amd64.zip -d /usr/local/bin/
We may want to recommend some other path -- /usr/local/bin is not user writable, as much as the name implies. @andrewhsu recently recommended $HOME/.local/rpk/, but we'd also need to add an instruction to add this path you the user's $PATH.

2022-10-14 21:24 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +unzip rpk-darwin-amd64.zip -d /usr/local/bin/
Same path comment -- and it gets even weirder on mac, I think.

2022-10-14 22:36 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-darwin-amd64.zip
This needs to be arm64 I think

2022-10-14 22:38 UTC, twmb commented
Another install related thing to fix, potentially in this PR:
https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1665769957932529
Our quick start macos instructions say "amd64" but should probably say arm64

2022-10-15 05:26 UTC, daisukebe commented on docs/quickstart/rpk-install.mdx
> +`rpk` is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with easily using the tab button. For details, see
> `It also` seems like an odd way to me to start a sentence

Indeed. Can we mention it at the end of the page simply like `To enable autocompletion, see <link>`?

2022-10-15 05:31 UTC, daisukebe commented on docs/quickstart/rpk-install.mdx
> +unzip rpk-linux-amd64.zip -d /usr/local/bin/
Why don't we follow the way the kubectl doc does? https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

`Install kubectl binary with curl on Linux` --> `3. Install kubectl` --> `Note`

<img width="589" alt="image" src="https://user-images.githubusercontent.com/350206/195970606-0a55a029-edaa-4ac9-9b15-302758a210e8.png">

2022-10-15 05:48 UTC, daisukebe commented on docs/quickstart/rpk-install.mdx
> +curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-darwin-amd64.zip
kubectl doc mentions both amd64 and arm64, https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#install-kubectl-binary-with-curl-on-macos. Cockroach's ccloud doc does too https://www.cockroachlabs.com/docs/cockroachcloud/ccloud-get-started.html.

2022-10-15 05:48 UTC, daisukebe commented on docs/quickstart/rpk-install.mdx
> +unzip rpk-darwin-amd64.zip -d /usr/local/bin/
Seems like `/usr/local/bin` is fine on Mac as `/usr/libexec/path_helper` does add `/usr/local/bin` to $PATH when a shell launches. Confirmed it on my personal Mac too (Apple M1 Pro, macOS Monterey).

ref. https://unix.stackexchange.com/questions/356688/what-is-the-difference-between-echo-path-and-etc-paths

2022-10-17 16:24 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +`rpk` is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with easily using the tab button. For details, see
@daisukebe isn't autocompletion enabled by default?

2022-10-17 16:29 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +`rpk` is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with easily using the tab button. For details, see
```suggestion
`rpk` is bundled with Redpanda, so when you install Redpanda it also installs `rpk`. 

`rpk` features autocompletion, which helps you interact with easily using the tab button. For details, refer to [rpk documentation](../../reference/rpk/rpk-generate/rpk-generate-shell-completion).
```

2022-10-18 00:56 UTC, AnneLeeperRP commented
@Deflaimun 
Here's a suggested rewrite for lines 8 - 14 (the introduction that leads up to the tabs with the separate instructions). I purposely omitted the part about autocompletion, since this topic just focuses on installation.

Redpanda Keeper (rpk) is a single binary application that provides a way to interact with your Redpanda clusters from the command line. You can install rpk as part of a bundle that includes Redpanda (see the 60-Second Guides for those instructions), or you can install the rpk binary separately. If you are preparing to deploy a BYOC cluster using the Redpanda Cloud UI, for example, you only need to install the rpk binary.

Note: For a list of all `rpk` commands and their syntax, see [rpk documentation](../../reference/rpk).

To install the rpk binary as a standalone application, follow the instructions for your operating system.

2022-10-18 01:46 UTC, daisukebe commented on docs/quickstart/rpk-install.mdx
> +`rpk` is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with easily using the tab button. For details, see
> @daisukebe isn't autocompletion enabled by default?

No, users need to configure it manually.

2022-10-18 16:21 UTC, Deflaimun commented
Thanks for the review @AnneLeeperRP . I added your suggestion to the main page and added a section about autocompletion in rpk reference page.

2022-10-18 16:23 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +unzip rpk-darwin-amd64.zip -d /usr/local/bin/
@twmb resolution for this? I assume we can go forward with this.

2022-10-18 16:24 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +`rpk` is installed with the Redpanda broker, which is contained in all Redpanda packages. It also provides autocompletion, which helps you interact with easily using the tab button. For details, see
I addressed this with @AnneLeeperRP 's suggestion. Please reopen the conversation if you guys feel that we need to change the wording.

2022-10-18 17:03 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +unzip rpk-linux-amd64.zip -d /usr/local/bin/
Let's recommend:
"Ensure your $PATH includes `~/.local/bin`, and then
```
mkdir -p ~/.local/bin
unzip rpk-linux-amd64.zip -d ~/.local/bin/
```
(perhaps worded better / formatting cleaned up)

2022-10-18 18:34 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +unzip rpk-darwin-amd64.zip -d /usr/local/bin/
Same comment as above

2022-10-19 22:25 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +curl -LO https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-darwin-amd64.zip
I've added a tab for  Intel macOS (with amd64) and Apple Silicon(with arm64). What do you guys think?

2022-10-19 22:26 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +unzip rpk-linux-amd64.zip -d /usr/local/bin/
I've split the commands. Implemented as: 

Ensure your `$PATH` includes `~/.local/bin`:

```bash
mkdir -p ~/.local/bin
```

Execute the following command:

```bash
unzip rpk-linux-amd64.zip -d ~/.local/bin/
```

2022-10-19 22:26 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +unzip rpk-linux-amd64.zip -d /usr/local/bin/
WDYT?

2022-10-20 05:54 UTC, AnneLeeperRP requested changes

2022-10-20 05:54 UTC, AnneLeeperRP commented on docs/quickstart/rpk-install.mdx
> +```
Instead of "Execute the following command:", can we describe what the command is doing? Would it be correct to say:
Unzip the `rpk` files to your `.local/bin/` directory:
(COMMAND)

2022-10-20 05:54 UTC, AnneLeeperRP commented on docs/quickstart/rpk-install.mdx
> +```
The command that follows the instruction is just making a directory along with its parent directory; it's not ensuring that the directory is included in $PATH.

We need new text to introduce the `mkdir` command, and probably an additional step about updating $PATH with the new directory.

2022-10-20 05:54 UTC, AnneLeeperRP commented on docs/quickstart/rpk-install.mdx
> +Download the `rpk` archive for macOS with:
Remove "with".

2022-10-20 05:54 UTC, AnneLeeperRP commented on docs/quickstart/rpk-install.mdx
> +```
(Same comment as before for this text)
The command is not ensuring that $PATH includes the directory; it's just making the directory and the necessary parent directory.

We need to explain that the user has to create the directory, add it to $PATH, then unzip the files to that directory.

2022-10-20 05:54 UTC, AnneLeeperRP commented on docs/quickstart/rpk-install.mdx
> +Execute the following command:
(General edit): Replace this with a description of what the command is doing.
Style Guide note: Use "run" instead of "execute" (except that the whole sentence will be replaced, so no need).

2022-10-20 05:54 UTC, AnneLeeperRP commented on docs/quickstart/rpk-install.mdx
> +After it’s completed, run `rpk version`, which shows the rpk binary version, not the Redpanda server version.
What does "it" refer to? How about:
"After the files have been unzipped, run `rpk version` to display the `rpk` binary version."

We don't need to say that 'version' is not the server version; we can just say it's the binary version.

2022-10-20 05:54 UTC, AnneLeeperRP commented on docs/quickstart/rpk-install.mdx
> +```
Suggestion:
"The output displays the version number and the latest commit; for example:"
Also, how about using the latest GA version in the example? (That version will soon be out-of-date, but at least it's not as old as 22.1.2.)

2022-10-20 05:54 UTC, AnneLeeperRP commented on docs/reference/rpk/rpk-commands.mdx
> +`rpk` features autocompletion, which helps you easily interact using the tab button. For details, refer to [rpk autocompletion documentation](../../reference/rpk/rpk-generate/rpk-generate-shell-compl
Suggestion:
The `rpk` commands feature autocompletion, so you can write the first few letters that uniquely identify a command, then use the tab key to complete it. For more information, see [rpk autocompletion documentation](../../reference/rpk/rpk-generate/rpk-generate-shell-completion).

Style Guide note: We use "see" instead of "refer to".

2022-10-20 16:32 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +```
Good idea. Implemented.

2022-10-20 16:53 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +Download the `rpk` archive for macOS with:
done

2022-10-20 16:53 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +Execute the following command:
done

2022-10-20 16:55 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +After it’s completed, run `rpk version`, which shows the rpk binary version, not the Redpanda server version.
done (good idea too! )

2022-10-20 16:58 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +```
I would say that the latest hash commit is not as important. I would stick only to the version number.

And for the actual number, we can in the future have a injectable version that always gets the latest number. (this requires a bit of work, which this PR doesn't have at the moment.)

2022-10-20 16:58 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +```
```suggestion
The output displays the version number:

```bash
v22.1.2 (rev 449eef2)
```
```

2022-10-20 17:00 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +```
Implemented as 

> The output displays the version number:
> 
> ```bash
> v22.1.2 (rev 449eef2)
> ```

2022-10-20 17:04 UTC, Deflaimun commented on docs/reference/rpk/rpk-commands.mdx
> +`rpk` features autocompletion, which helps you easily interact using the tab button. For details, refer to [rpk autocompletion documentation](../../reference/rpk/rpk-generate/rpk-generate-shell-compl
done

2022-10-20 17:08 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +```
Implemented as

> Ensure that you have the folder `~/.local/bin`:

> ```bash
> mkdir -p ~/.local/bin
> ```
> 
> Add it to your `$PATH`:
> 
> ```bash
> export PATH="~/.local/bin:$PATH"
> ```
> 
> Unzip the `rpk` files to your `.local/bin/` directory:
> 
> ```bash
> unzip rpk-linux-amd64.zip -d ~/.local/bin/
> ```

2022-10-20 17:08 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +```
@twmb could you approve the commands for accuracy?

2022-10-20 19:17 UTC, AnneLeeperRP approved these changes

2022-10-21 00:27 UTC, twmb reviewed
nits, but content lgtm

2022-10-21 00:27 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +You can install `rpk` as part of a bundle that includes Redpanda (see the [60-Second Guides](../) for those instructions), or you can install the `rpk` binary separately.
Should `for those instructions` just be `for instructions??

2022-10-21 00:27 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +You can install `rpk` as part of a bundle that includes Redpanda (see the [60-Second Guides](../) for those instructions), or you can install the `rpk` binary separately.
Also, "that includes Redpanda" -- I think we prefer lowercase if we are referring to the binary itself

2022-10-21 00:27 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +<TabItem value="intemac" label="Intel macOS" default>
`intemac` => `intelmac`?

2022-10-21 00:27 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +<TabItem value="applesillicon" label="Apple Silicon" default>
`sillicon` => `silicon`

2022-10-21 00:27 UTC, twmb commented on docs/reference/rpk/rpk-commands.mdx
> +The `rpk` commands feature autocompletion, so you can write the first few letters that uniquely identify a command, then use the tab key to complete it. For more information, see [rpk autocompletion
`autocompletion, so you can` => `autocompletion so that you can`; `identify a command, then use` => `identify a command and then use`

perhaps

2022-10-21 00:27 UTC, twmb commented on docs/quickstart/rpk-install.mdx
> +Unzip the `rpk` files to your `.local/bin/` directory:
Here and below, I'd prefix `./local/bin` with `~/`, to be explicit. `./` refers to the directory the person might currently be in, and every other usage of this has `~/`

2022-10-21 02:21 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +You can install `rpk` as part of a bundle that includes Redpanda (see the [60-Second Guides](../) for those instructions), or you can install the `rpk` binary separately.
done.

2022-10-21 02:22 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +<TabItem value="intemac" label="Intel macOS" default>
these are just html values, so it doesn't really matter. they just gotta be different.
Anyway, addressed.

2022-10-21 02:22 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +<TabItem value="applesillicon" label="Apple Silicon" default>
these are just html values, so it doesn't really matter. they just gotta be different.
Anyway, addressed.

2022-10-21 02:22 UTC, Deflaimun commented on docs/reference/rpk/rpk-commands.mdx
> +The `rpk` commands feature autocompletion, so you can write the first few letters that uniquely identify a command, then use the tab key to complete it. For more information, see [rpk autocompletion
good one. done.

2022-10-21 02:22 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +Unzip the `rpk` files to your `.local/bin/` directory:
Yes. We must keep it accurate. good find.

2022-10-21 02:23 UTC, Deflaimun commented on docs/quickstart/rpk-install.mdx
> +You can install `rpk` as part of a bundle that includes Redpanda (see the [60-Second Guides](../) for those instructions), or you can install the `rpk` binary separately.
Yes, that's true. done.

2022-10-21 02:23 UTC, merged