docs:#605 tiered storage retention controls
redpanda-data/documentation pull request #709
Opened 2022-10-13 02:50 UTC by micheleRP

resolves #605

2022-10-20 22:59 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +To maximize cloud storage, Redpanda supports retention limits and compaction. Set retention limits to purge topic data after it reaches a specified age or size, or to purge data from local disks when
fixed

2022-10-20 23:01 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +### Set retention limits
Thank you @jcsp! This was very helpful. Would you please check review this change: https://deploy-preview-709--redpanda-documentation.netlify.app/docs/data-management/tiered-storage/#set-retention-limits

2022-10-24 12:12 UTC, Lazin commented on docs/data-management/tiered-storage.mdx
> +| `redpanda.remote.recovery` | Recovers or reproduces a topic from cloud storage. Use this flag during topic creation. It does not apply to existing topics.  |
This might change before next release. cc @jcsp @mattschumpert

2022-10-24 12:16 UTC, Lazin commented on docs/data-management/tiered-storage.mdx
> +Replacing non-compacted segments with compacted segments saves space and minimizes the time needed to consume the entire topic. Redpanda prevents compaction from processing any segments below `max_co
The `max_collectible_offset` is an internal detail users don't need to know about. I think that here we should say that redpanda doesn't compact segments which wasn't uploaded to the cloud storage yet. We upload everything twice: first non-compacted (to guarantee that everything is uploaded and we don't have any gaps in data) and eventually with compaction applied (to save space).

2022-10-24 12:17 UTC, Lazin commented on docs/data-management/tiered-storage.mdx
> +| `cloud_storage_reconciliation_interval_ms` | Sets the interval, in milliseconds, used to reconcile partitions that need to be uploaded. A long reconciliation interval can result in a delayed reacti
The default is 500ms now.

2022-10-24 23:27 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +Replacing non-compacted segments with compacted segments saves space and minimizes the time needed to consume the entire topic. Redpanda prevents compaction from processing any segments below `max_co
Thanks @Lazin! Does this sound correct: 
To save space, Redpanda compacts segments after they have been uploaded to cloud storage. Redpanda initially uploads all (non-compacted) segments. It then reuploads the segments with compaction applied.

2022-10-25 05:19 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +| `cloud_storage_reconciliation_interval_ms` | Sets the interval, in milliseconds, used to reconcile partitions that need to be uploaded. A long reconciliation interval can result in a delayed reacti
thank you, fixed!

2022-11-03 04:02 UTC, micheleRP commented
@jcsp @mattschumpert @Lazin: This PR needs to be merged on Friday. Would you please approve it or add any necessary comments/corrections? Thank you!

2022-11-03 23:27 UTC, micheleRP commented
@jcsp @mattschumpert @Lazin: Another reminder about this! Our doc deadline for 22.3 is tomorrow. Would you please approve it or add any necessary comments/corrections? Thank you!

2022-11-04 01:11 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +| `redpanda.remote.recovery` | Recovers or reproduces a topic from cloud storage. Use this flag during topic creation. It does not apply to existing topics.  |
@Lazin @jcsp @mattschumpert: Is this correct for 22.3?

2022-11-04 20:22 UTC, mattschumpert commented on docs/data-management/tiered-storage.mdx
>  Remote write is the process that constantly uploads log segments to cloud storage. The process is created for each partition and runs on the leader node of the partition. It only uploads the segments
Also, doesn't compaction ONLY happen when the user explicitly decides to use a compacted topic @mmaslankaprv , @Lazin ?

2022-11-04 20:33 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +You can enable Tiered Storage for a cluster or a topic. Topic-level tags override cluster-level settings. For example, if you have Tiered Storage enabled on the cluster and you create a topic with Ti
fixed

2022-11-04 20:38 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +Starting in Redpanda release 22.3, cloud storage is the default platform for all streaming data, and retention properties work the same for Tiered Storage topics and local storage topics. Data is ret
fixed

2022-11-04 20:39 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +To reduce cloud storage costs, Redpanda supports retention limits and compaction. Set retention limits to purge topic data after it reaches a specified age or size.
fixed

2022-11-04 20:40 UTC, Feediver1 commented on docs/data-management/tiered-storage.mdx
> +| `redpanda.remote.recovery` | Recovers or reproduces a topic from cloud storage. Use this flag during topic creation. It does not apply to existing topics.  |
@micheleRP Let's go with @mattschumpert 's guidance here. If @Lazin has any other recommendations wrt this one, he can put an an issue and you can update post GA.

2022-11-04 20:40 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +Set topic-level properties to tune your local storage. Settings can depend on the size of your drive, how many partitions you have, and how much data you keep for each partition.
fixed

2022-11-04 20:40 UTC, Feediver1 commented on docs/data-management/tiered-storage.mdx
> +Replacing non-compacted segments with compacted segments saves space and minimizes the time needed to consume the entire topic. Redpanda prevents compaction from processing any segments below `max_co
Same as above @micheleRP - Go with this and if @Lazin wants you to modify, you can capture post-GA.

2022-11-04 20:42 UTC, Feediver1 commented on docs/data-management/tiered-storage.mdx
> +Tiered Storage lets you save storage costs by offloading log segments to cloud storage. You can specify the amount of local storage you want to provision and configure Tiered Storage to move the rest
@micheleRP @mattschumpert Given the time difference, @Lazin will not likely respond today--PR must be merged today--so my guidance is to remove any statements that are not 100% correct. Thinking you can have a single post-GA tiered storage update ticket and deal with it there. Unless @mattschumpert provides an updated statement to replace this...

2022-11-04 20:45 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +Tiered Storage lets you save storage costs by offloading log segments to cloud storage. You can specify the amount of local storage you want to provision and configure Tiered Storage to move the rest
fixed

2022-11-04 21:08 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> -* `cloud_storage_reconciliation_interval_ms` - Sets the interval, in milliseconds, that is used to reconcile partitions that need to be uploaded. A long reconciliation interval can result in a delaye
@mattschumpert pls confirm if this revision is correct:
Starting in release 22.3, when you delete a topic in Redpanda, the data is also deleted in cloud storage. Topics created prior to 22.3 can alter their configuration to this behavior on a topic level after upgrading.

2022-11-04 21:22 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +### Set retention limits
@mattschumpert: I replaced that sentence with:
Retention limits apply to data stored in cloud storage, even though additional data may be cached or managed in local storage.

2022-11-04 21:35 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +| `redpanda.remote.recovery` | Recovers or reproduces a topic from cloud storage. Use this flag during topic creation. It does not apply to existing topics.  |
@mattschumpert: I updated this intro paragraph as:
Topic-level properties override cluster-level properties. For example, if you have Tiered Storage enabled on the cluster and you create a topic with Tiered Storage turned off, it is also turned off for that topic. When cluster-level properties are changed, the changes apply only to new topics, not existing topics.

2022-11-04 21:44 UTC, mattschumpert commented on docs/data-management/tiered-storage.mdx
> +You can configure the `cloud_storage_initial_backup_ms` property to set the time, in milliseconds, that is used as an initial backoff interval in the exponential backoff algorithm to handle an error.
Not a comment on the docs but rather the property itself seems wrongly named (should be 'backoff', no @jcsp , @Lazin )?

2022-11-04 21:46 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
>  3. Grant the user permission to read and create objects in cloud storage.
fixed

2022-11-04 21:46 UTC, mattschumpert requested changes

2022-11-04 21:46 UTC, mattschumpert commented on docs/data-management/tiered-storage.mdx
> +You can configure the `cloud_storage_initial_backup_ms` property to set the time, in milliseconds, that is used as an initial backoff interval in the exponential backoff algorithm to handle an error.
NM this IS a doc issue, below the reference shows it at 'backoff ' @micheleRP

2022-11-04 21:54 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +You can configure the `cloud_storage_initial_backup_ms` property to set the time, in milliseconds, that is used as an initial backoff interval in the exponential backoff algorithm to handle an error.
fixed

2022-11-04 21:58 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
>  When you create a topic, you can use remote recovery to download the topic data from cloud storage. Only the data that matches the retention policy of the topic is downloaded. The data that is not do
removed

2022-11-04 22:12 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +- If properties are not specified, Redpanda uses the default values (infinite retention).
fixed

2022-11-04 22:18 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +Topic configuration flags override any cluster-level configuration. For example, if `cloud_storage_enable_remote_write` is set to `true`, you can set `redpanda.remote.write` to `false` to turn it off
fixed

2022-11-04 22:22 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
>  ```properties
@mattschumpert Can you pls provide the examples we should use here?

2022-11-04 22:31 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
>  Note that the cluster-level `cloud_storage_enabled` property must be set to `true` to enable Tiered Storage at the cluster level or the topic level. If you want to have Tiered Storage turned off at t
@mattschumpert please see the revised text & let me know if you have other suggestions

2022-11-04 23:00 UTC, mattschumpert approved these changes

2022-11-04 23:14 UTC, Feediver1 commented on docs/data-management/tiered-storage.mdx
>  Do not use Tiered Storage with [data transforms](../../data-management/data-transform), which is in technical preview. Technical preview features are not supported for production usage.
Please add a link to the Technical Preview topic here.

2022-11-04 23:18 UTC, Feediver1 commented on docs/data-management/tiered-storage.mdx
> +## Set up
Why isn't this a "Prerequisites" section? Are all these steps required to use Tiered Storage--it's unclear if they are required or not? Or are they the actual set up steps for Tiered Storage? Unclear to me.

2022-11-04 23:21 UTC, Feediver1 commented on docs/data-management/tiered-storage.mdx
> +Topic configuration flags override any cluster-level configuration. For example, on new topics, if `cloud_storage_enable_remote_write` is set to `true`, you can set `redpanda.remote.write` to `false`
I don't think the last line needs to be in parenthesis.

2022-11-04 23:24 UTC, Feediver1 commented on docs/data-management/tiered-storage.mdx
> +Set topic-level properties to control retention of topic data in local storage. Settings can depend on the size of your drive, how many partitions you have, and how much data you keep for each partit
```suggestion
You can use topic-level properties to control retention of topic data in local storage. Settings can depend on the size of your drive, how many partitions you have, and how much data you keep for each partition. 
```

2022-11-04 23:25 UTC, Feediver1 commented on docs/data-management/tiered-storage.mdx
> +  - New topics starting in release 22.3 use the default retention values of 1 (local) and 7 days (S3).
```suggestion
  - Starting in release 22.3, new topics use the default retention values of 1 (local) and 7 days (S3).
```

2022-11-04 23:25 UTC, Feediver1 commented on docs/data-management/tiered-storage.mdx
> +To save space, Redpanda compacts segments after they have been uploaded to cloud storage. Redpanda initially uploads all (non-compacted) segments. It then reuploads the segments with compaction appli
```suggestion
To save space, Redpanda compacts segments after they have been uploaded to cloud storage. Redpanda initially uploads all (non-compacted) segments. It then re-uploads the segments with compaction applied.
```

2022-11-04 23:31 UTC, Feediver1 approved these changes
See suggestions. Otherwise, LGTM

2022-11-05 00:16 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
> +Topic configuration flags override any cluster-level configuration. For example, on new topics, if `cloud_storage_enable_remote_write` is set to `true`, you can set `redpanda.remote.write` to `false`
fixed

2022-11-05 00:20 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
>  Do not use Tiered Storage with [data transforms](../../data-management/data-transform), which is in technical preview. Technical preview features are not supported for production usage.
@Feediver1 There is a link to the Data Transforms page here. Links look different when they're inside an admonition. But this also will be a conflict since it linking to the old Tech Preview location instead of new Logs section.

2022-11-05 01:49 UTC, merged

2022-11-07 17:34 UTC, micheleRP commented on docs/data-management/tiered-storage.mdx
>  rpk topic create <topic_name> -c redpanda.remote.read=true -c redpanda.remote.write=true
not an issue (per https://redpandadata.slack.com/archives/C02BDN76HUK/p1667625446367879?thread_ts=1667571457.890479&cid=C02BDN76HUK)