docs:#602 basic auth for proxy and schema registry
redpanda-data/documentation pull request #718
Opened 2022-10-17 22:43 UTC by micheleRP

resolves #602

2022-10-18 12:52 UTC, NyaliaLui commented
@micheleRP I'm glad to help with the review but what are you looking from me here? Do I simply review the text?

2022-10-18 13:00 UTC, NyaliaLui requested changes

2022-10-18 13:00 UTC, NyaliaLui commented on docs/security/authentication.mdx
> +To configure basic authentication, set `authentication_type` of the listener to `http_basic`.
```suggestion
To configure basic authentication, set `authentication_method` of the listener to `http_basic`.
```

2022-10-18 13:11 UTC, NyaliaLui commented on docs/security/authentication.mdx
> +## Configure basic authentication
It may be worth noting that Basic Authentication is only supported on the Admin API, HTTP Proxy, and Schema Registry.

2022-10-19 15:36 UTC, micheleRP commented
Adding from slack: 

[@Ben Pope (BST; London)](https://redpandadata.slack.com/team/U016TV8LRJ9)
I'm not sure how to document ephemeral secrets. Is it correct to remove the existing section [Configure SASL for HTTP Proxy and Schema Registry](https://deploy-preview-718--redpanda-documentation.netlify.app/docs/security/authentication/#configure-sasl-for-http-proxy-and-schema-registry) and replace it with a note similar to the following:

HTTP Proxy and Schema Registry connect to Redpanda over the Kafka API. For the Kafka username and password, Redpanda uses ephemeral secrets internal to the cluster, which change on cluster restart. When a node receives a Kafka request with a username that looks internal, it consults the in-memory store of ephemeral secrets to authenticate. If there is no secret matching the name, it broadcasts to other nodes to share the secret. If no secret is available, it asks the controller leader to mint a new secret.

Ben Pope
I'll try to add more clarity over the next few days, but the goal, and especially for Pandaproxy, is that the existing configuration can be used to override the ephemeral credentials, should the need arise (and for backwards compatibility).

2022-10-20 21:10 UTC, mattschumpert commented on docs/security/authentication.mdx
> +    <meta name="description" content="Redpanda supports multiple forms of authentication including SASL/SCRAM, basic authentication, mTLS with principal mapping, and mixed-mode with multiple listener
This mixes a few things (not all endpoints support all forms of auth).

Maybe we should say something about 'Different components of Redpanda support a wide variety of authentication methods...'

Maybe it's too detailed but it may be worth specifying that 'listeners' relate specifically to  the Kafka API endpoint.

2022-10-20 21:10 UTC, mattschumpert commented on docs/security/authentication.mdx
> +HTTP Proxy and Schema Registry connect to Redpanda over the Kafka API, and they must be configured with a username and password.
@micheleRP this doesn't talk about ephemeral credentials (the other option here that makes this statement not true).  I thought we were adding that content in this PR?

2022-10-20 21:10 UTC, mattschumpert commented on docs/security/authentication.mdx
> +For Schema Registry, the configuration node is `schema_registry_client`:
@BenPope  a nit, it's a bit confusing that we're talking about SR/PP itself and not a client TO them with this conf.

2022-10-20 21:10 UTC, mattschumpert commented on docs/security/authentication.mdx
> +Basic authentication is supported on the Admin API, HTTP Proxy, and Schema Registry.
This section doesn't address how basic auth on the Admin API is configured.  Is it just 'always-on' @BenPope ?  If so, we should say that here for completeness @micheleRP

2022-10-20 21:10 UTC, mattschumpert commented on docs/security/authentication.mdx
>  To disable authentication for a listener, set `authentication_method` to `none`. If authorization is enabled, connections to this listener use the anonymous user.
Maybe an example?

2022-10-20 21:41 UTC, BenPope commented on docs/security/authentication.mdx
> +    <meta name="description" content="Redpanda supports multiple forms of authentication including SASL/SCRAM, basic authentication, mTLS with principal mapping, and mixed-mode with multiple listener
>  and mixed-mode with multiple listeners.

This is a bit awkward, mixed-mode isn't really a thing that's like the others; each listener has an auth mode and there can be multiple listeners.

> Maybe it's too detailed but it may be worth specifying that 'listeners' relate specifically to the Kafka API endpoint.

Multiple listeners is supported for Kafka API, Schema Registry, and HTTP Proxy (at least in theory, I don't know if helm and operator directly support that).

2022-10-20 21:43 UTC, BenPope commented on docs/security/authentication.mdx
> +For Schema Registry, the configuration node is `schema_registry_client`:
Yeah, this could probably be clearer.

`Configure HTTP Proxy and Schema Registry to connect to Redpanda with SASL`

2022-10-20 21:44 UTC, BenPope commented on docs/security/authentication.mdx
> +Basic authentication is supported on the Admin API, HTTP Proxy, and Schema Registry.
[admin_api_require_auth](https://docs.redpanda.com/docs/reference/cluster-properties/#:~:text=admin_api_require_auth)

2022-10-20 21:48 UTC, BenPope commented on docs/security/authentication.mdx
> -The HTTP Proxy and Schema Registry require valid client certificates.
The example connects Schema Registry to Redpanda with mTLS. If the `kafka_api` listener it connects to has `mtls_identity`, then that will be used. I wrote this part of the doc to highlight the second scenario.

2022-10-21 15:40 UTC, micheleRP commented on docs/security/authentication.mdx
> +For Schema Registry, the configuration node is `schema_registry_client`:
thx, fixed

2022-10-21 16:52 UTC, micheleRP commented on docs/security/authentication.mdx
> +    <meta name="description" content="Redpanda supports multiple forms of authentication including SASL/SCRAM, basic authentication, mTLS with principal mapping, and mixed-mode with multiple listener
@mattschumpert or @BenPope I've updated the intro paragraph: https://deploy-preview-718--redpanda-documentation.netlify.app/docs/security/authentication/. Is this correct?

2022-10-21 16:53 UTC, micheleRP commented on docs/security/authentication.mdx
> +Basic authentication is supported on the Admin API, HTTP Proxy, and Schema Registry.
> [admin_api_require_auth](https://docs.redpanda.com/docs/reference/cluster-properties/#:~:text=admin_api_require_auth)

@BenPope Would you please confirm if this is now correct: https://deploy-preview-718--redpanda-documentation.netlify.app/docs/security/authentication/#configure-basic-authentication

2022-10-21 17:03 UTC, micheleRP commented
@NyaliaLui You'll need to clear that your requested changes were incorporated before this PR can merge. Can you please do that, so it doesn't delay the merge at the end? And please review the entire page again, since there have been some changes and open feedback from Matt and Ben. Thank you!

2022-10-24 12:53 UTC, NyaliaLui commented on docs/security/authentication.mdx
>  To disable authentication for a listener, set `authentication_method` to `none`. If authorization is enabled, connections to this listener use the anonymous user.
To make it easier, here is what the example would look like:
```yaml
pandaproxy:
  pandaproxy_api:
  - address: "localhost"
    port: 8082
    authentication_method: none

schema_registry:
  schema_registry_api:
    address: "localhost"
    port: 8081
    authentication_method: none
```

2022-10-24 14:25 UTC, micheleRP commented on docs/security/authentication.mdx
>  To disable authentication for a listener, set `authentication_method` to `none`. If authorization is enabled, connections to this listener use the anonymous user.
@NyaliaLui thank you!

2022-10-24 20:44 UTC, NyaliaLui commented on docs/security/authentication.mdx
> +To disable authentication for a listener, set `authentication_method` to `none`:
Disabling authentication on the Kafka API is slightly more involved than on the Schema Registry and HTTP Proxy. It may be worth noting that here.

For the Kafka API, the user disables authentication by disabling `kafka_enable_authorization` and setting `authentication_method` to none for all listeners. For example:
`rpk cluster config set kafka_enable_authorization false` and
```yaml
redpanda:
  kafka_api:
    - address: 0.0.0.0
      port: 9092
      name: sasl_listener
      authentication_method: none
```

The writing and examples for disabling authentication on the Proxy and Schema Registry are correct so no changes there.

2022-10-24 20:54 UTC, NyaliaLui commented on docs/security/authentication.mdx
> +You can enable basic authentication to use Kafka API username/password credentials to authenticate to HTTP Proxy and Schema Registry.
```suggestion
You can enable basic authentication to use Kafka API username/password credentials to authenticate to HTTP Proxy and Schema Registry. This requires that SASL is turned on for Kafka API endpoints.
```

Both the HTTP Proxy and Schema Registry require that SASL is enabled on Kafka API endpoints

2022-10-24 21:10 UTC, NyaliaLui commented on docs/security/authentication.mdx
> +- HTTP Proxy: Users represented in the HTTP basic authorization header are subject to authorization restrictions by Redpanda ACLs. Access to the Kafka API impersonates the user whose credentials were
It seems that this bullet point is intended to describe **how** we implemented basic authentication on the HTTP Proxy. With that in mind, I suggest a slight re-ordering to the sentences so readers can differ between the conceptual and implementation elements. We also don't need to mention the authorization header here since it is an industry standard.

```suggestion
- HTTP Proxy: Access to the Kafka API impersonates the user whose credentials were used to authenticate to HTTP Proxy and the user is subject to authorization restrictions by Redpanda ACLs. To support this design, Redpanda passes the username/password in memory to a SASL-enabled Kafka client.
```

2022-10-24 21:19 UTC, NyaliaLui commented on docs/security/authentication.mdx
> +
Also, here is an example of how to use basic authentication after the feature is enabled. This could help with understanding.

```
rpk acl user create foo --password bar # Creates a SASL user for the Kafka API
curl -u "foo:bar" "http://localhost:8082/topics" # A request to the HTTP Proxy with user "foo"
curl -u "foo:bar" "http://localhost:8081/subjects" # A request to the Schema Registry with user "foo" 
```

2022-10-24 21:23 UTC, NyaliaLui approved these changes

2022-10-24 21:24 UTC, NyaliaLui reviewed
I did not know how to clear my "request changes" so I approved and then redid the review.

2022-10-25 17:04 UTC, Feediver1 commented on docs/security/authentication.mdx
> +Specify the name of the superuser, either an existing user or a user that does not exist yet. For example, if you used superuser `admin`, Redpanda allows the `admin` user to do anything, but Redpanda
I think it would be nice/helpful to our customers if there were more background/context here that answers the questions:
- Why should our customers create/include superusers in the RP config file?
 Here, the parenthetical kind of touches on it--is the parenthetical the primary reason our customers need to create superusers? If so, maybe present as the explanation? eg. "When you configure authentication, it is highly recommended that you include one or more superusers in the Redpanda configuration file. This user has [ALL permissions](../../security/authorization#operations) on the cluster and grants permissions to new users. 
Without a superuser, you can create other users, but you can't grant them permissions to the cluster.

2022-10-25 17:27 UTC, Feediver1 commented on docs/security/authentication.mdx
> +Schema Registry and HTTP Proxy require valid client certificates to secure the transport. Continuing with the previous example, where the certificate contains an identity for authentication (`kafka_a
```suggestion
Schema Registry and HTTP Proxy require valid client certificates to secure the transport. Continuing with the previous example, where the certificate contains an identity for authentication (`kafka_api` listener set to `mtls_identity`), the following example shows how to connect Schema Registry and HTTP Proxy to Redpanda with mTLS certificate-based identity.
```

2022-10-26 22:27 UTC, mattschumpert commented on docs/security/authentication.mdx
> +Schema Registry and HTTP Proxy connect to Redpanda over the Kafka API. For the Kafka username and password, Redpanda uses ephemeral secrets internal to the cluster, which change on cluster restart. W
This page is good place to document it @Feediver1 .

 ephemeral credentials ('AutoAuth') is still landing this week, but we should probably have a separate PR for this as it' arguably its own 'feature' @micheleRP .  But I still think the 'authentication' page is the right context in which to read about it

2022-10-26 23:32 UTC, Feediver1 commented on docs/security/authentication.mdx
> +The `admin` user has full access to the cluster and can then grant permissions to other users.
```suggestion
The `admin` user has full access to the cluster and can grant permissions to other users. 
```

2022-10-26 23:33 UTC, Feediver1 commented on docs/security/authentication.mdx
> +As a security best practice, you don't want to use the superuser to interact with the cluster, but you also don't want to delete the superuser (in case you need to grant permissions to new users late
```suggestion
As a security best practice, don't use the superuser to interact with the cluster and do not delete the superuser (in case you need to grant permissions to new users later on). In addition, when you create the superuser, specify a password, which adds a level of security to the superuser. If you delete the user, someone else might re-create the user with a different password. 
```

2022-10-27 14:11 UTC, micheleRP commented on docs/security/authentication.mdx
> +Schema Registry and HTTP Proxy connect to Redpanda over the Kafka API. For the Kafka username and password, Redpanda uses ephemeral secrets internal to the cluster, which change on cluster restart. W
@Feediver1 @mattschumpert We already have https://github.com/redpanda-data/documentation/issues/607, which I included in this PR with basic auth.

2022-10-27 14:38 UTC, micheleRP commented on docs/security/authentication.mdx
> +To disable authentication for a listener, set `authentication_method` to `none`:
thanks @NyaliaLui. I added this:  https://deploy-preview-718--redpanda-documentation.netlify.app/docs/security/authentication/#disable-authentication

2022-10-27 14:42 UTC, micheleRP commented on docs/security/authentication.mdx
> +
Thanks @NyaliaLui! Can you please confirm if this looks correct, just dropping it in? https://deploy-preview-718--redpanda-documentation.netlify.app/docs/security/authentication/#configure-basic-authentication

2022-10-27 14:44 UTC, micheleRP commented on docs/security/authentication.mdx
> +As a security best practice, you don't want to use the superuser to interact with the cluster, but you also don't want to delete the superuser (in case you need to grant permissions to new users late
fixed!

2022-10-27 14:44 UTC, micheleRP commented on docs/security/authentication.mdx
> +The `admin` user has full access to the cluster and can then grant permissions to other users.
fixed

2022-10-27 14:53 UTC, BenPope commented on docs/security/authentication.mdx
> -The HTTP Proxy and Schema Registry require valid client certificates.
Looks good

2022-10-27 14:56 UTC, BenPope commented on docs/security/authentication.mdx
> +Schema Registry and HTTP Proxy require valid client certificates to secure the transport. Continuing with the previous example, where the certificate contains an identity for authentication (`kafka_a
Looks good.

Perhaps: "Schema Registry and HTTP Proxy require valid client certificates to secure the connection to Redpanda."

2022-10-27 14:59 UTC, BenPope commented on docs/security/authentication.mdx
> +### Configure mTLS for Schema Registry and HTTP Proxy
```suggestion
### Configure Schema Registry and HTTP Proxy to connect to Redpanda with mTLS
```

2022-10-27 14:59 UTC, BenPope commented on docs/security/authentication.mdx
> +### Configure SASL for Schema Registry and HTTP Proxy
```suggestion
### Configure Schema Registry and HTTP Proxy to connect to Redpanda with SASL
```

2022-10-27 15:03 UTC, NyaliaLui commented on docs/security/authentication.mdx
> +To disable authentication for a listener, set `authentication_method` to `none`:
Looks good.

2022-10-27 15:04 UTC, NyaliaLui commented on docs/security/authentication.mdx
> +
Looks good.

2022-11-02 19:08 UTC, micheleRP commented on docs/security/authentication.mdx
> +Specify the name of the superuser, either an existing user or a user that does not exist yet. For example, if you used superuser `admin`, Redpanda allows the `admin` user to do anything, but Redpanda
rephrased this

2022-11-02 19:12 UTC, micheleRP commented
@BenPope @NyaliaLui @mattschumpert: This PR needs to be merged on Friday. Would you please approve it or add any necessary comments/corrections? Thank you!

2022-11-02 19:18 UTC, BenPope approved these changes

2022-11-03 12:55 UTC, NyaliaLui approved these changes

2022-11-04 00:35 UTC, Feediver1 commented on docs/security/authentication.mdx
> +Schema Registry and HTTP Proxy connect to Redpanda over the Kafka API. For the Kafka username and password, Redpanda uses ephemeral credentials internal to the cluster. Ephemeral credentials are regu
So much better/more clear/helpful!

2022-11-04 00:36 UTC, Feediver1 approved these changes
LGTM

2022-11-04 15:30 UTC, merged