docs: change node properties description and add note
redpanda-data/documentation pull request #858
Opened 2022-11-28 14:21 UTC by Deflaimun

Resolves #652 

Preview:

2022-11-28 14:23 UTC, Deflaimun commented
@dlex notice that we have different descriptions for 22.3 and previous versions. Which one is the most accurate? 

22.3 
> A number that uniquely identifies the node within the cluster. This property must not be changed after a node joins the cluster. If unset, Redpanda assigns one automatically. If set, it must be a positive number.

older versions <= 22.2
> A number that identifies the node within the cluster. This value can be assigned automatically by a deployment tool, or it can be assigned by the user. Each node must have a unique node_id, and nodes should be numbered in sequence. This property must not be changed once a node joins a cluster.

2022-11-28 14:24 UTC, Deflaimun commented
Also, this doc is not present on `21.11` . Should it be there too?

2022-11-28 20:15 UTC, Feediver1 commented on versioned_docs/version-22.2/platform/reference/node-properties.mdx
> +You must include the following required properties in your configuration. If you omit them, `redpanda` will not start.
I'm curious why in the other instance you refer to Redpanda, and in this instance "`redpanda`"

2022-11-28 20:16 UTC, Feediver1 commented on versioned_docs/version-22.2/platform/reference/node-properties.mdx
> +You must include the following required properties in your configuration. If you omit them, `redpanda` will not start.
Same goes for the inconsistency in formatting of node_id.

2022-11-28 20:17 UTC, Feediver1 approved these changes
Please await feedback from @AnneLeeperRP and @dlex 
Also, please make the formatting of the text flagged below consistent between versions. Otherwise, approved. Thx @Deflaimun

2022-11-28 20:57 UTC, Deflaimun commented on versioned_docs/version-22.2/platform/reference/node-properties.mdx
> +You must include the following required properties in your configuration. If you omit them, `redpanda` will not start.
For Redpanda vs `redpanda` is because the process `redpanda` won't start.

2022-11-28 20:59 UTC, Deflaimun commented on versioned_docs/version-22.2/platform/reference/node-properties.mdx
> +You must include the following required properties in your configuration. If you omit them, `redpanda` will not start.
> Same goes for the inconsistency in formatting of node_id.
The problem here is bit bigger because there's difference between the writing in the old versions and current version. So for this one, I have to wait for @dlex 's instruction.

2022-11-29 20:08 UTC, dlex commented
> Which one is the most accurate?

Both are accurate for their respective versions.

2022-11-29 20:14 UTC, dlex requested changes

2022-11-29 20:14 UTC, dlex commented on docs/platform/reference/node-properties.mdx
> +| node_id | A number that uniquely identifies the node within the cluster. This property must not be changed after a node joins the cluster. If unset, Redpanda assigns one automatically. If set, it m
`node_id` is not a required property since v22.3. This sentence from the description illustrates that:
> If unset, Redpanda assigns one automatically.

As of now, the only required property is `data_directory`.

2022-12-01 17:21 UTC, dlex approved these changes
Technically correct

2022-12-01 17:21 UTC, dlex commented on versioned_docs/version-22.2/platform/reference/node-properties.mdx
> +You must include the following required properties in your configuration. If you omit them, `redpanda` will not start.
> For Redpanda vs `redpanda` is because the process `redpanda` won't start.

Right, but in other versions it's also about the process, and the doc uses "Redpanda" there.

2022-12-01 17:34 UTC, Deflaimun commented
Thanks @dlex

2022-12-01 17:34 UTC, merged