Document support for PKCS#12
redpanda-data/documentation pull request #860
Opened 2024-11-14 16:37 UTC by JakeSCahill

## Description

Resolves https://github.com/redpanda-data/documentation-private/issues/<add-your-issue-number-here>
Review deadline:

## Page previews

## Checks

- [ ] New feature
- [ ] Content gap
- [ ] Support Follow-up
- [ ] Small fix (typos, links, copyedits, etc)

2024-11-14 16:37 UTC, JakeSCahill commented on modules/manage/pages/security/encryption.adoc
> +- A Truststore file (`ca.crt`). All brokers can have the same `ca.crt` file.
```suggestion
- A truststore file (`ca.crt`). All brokers can have the same `ca.crt` file.
```

2024-11-20 13:48 UTC, michael-redpanda requested changes
Looks great!  Now the fun part - turns out PKCS#12 doesn't work in FIPS.  So I think we need a call out for that.

So some background information on this (discovered in [this PR](https://github.com/redpanda-data/redpanda/pull/24094))

The MAC key derivation algorithm used for PKCS#12 is PKCS12KDF.  This is _not_ a FIPS supported algorithm.  This means that, when running in FIPS mode, the OpenSSL FIPS provider will error out on unwrapping a PKCS#12 file.

A proposal ([rfc9579](https://datatracker.ietf.org/doc/html/rfc9579)) has been made to replace that with PBMAC1 which is FIPS compliant.  The ability to unwrap a PKCS#12 file using that is in OpenSSL 3.4, which we haven't updated to yet.

Some other reading can be found here: https://www.redhat.com/en/blog/fips-140-3-changes-pkcs-12

2024-11-25 16:17 UTC, JakeSCahill commented
> Looks great! Now the fun part - turns out PKCS#12 doesn't work in FIPS. So I think we need a call out for that.
> 
> So some background information on this (discovered in [this PR](https://github.com/redpanda-data/redpanda/pull/24094))
> 
> The MAC key derivation algorithm used for PKCS#12 is PKCS12KDF. This is _not_ a FIPS supported algorithm. This means that, when running in FIPS mode, the OpenSSL FIPS provider will error out on unwrapping a PKCS#12 file.
> 
> A proposal ([rfc9579](https://datatracker.ietf.org/doc/html/rfc9579)) has been made to replace that with PBMAC1 which is FIPS compliant. The ability to unwrap a PKCS#12 file using that is in OpenSSL 3.4, which we haven't updated to yet.
> 
> Some other reading can be found here: https://www.redhat.com/en/blog/fips-140-3-changes-pkcs-12

Thanks @michael-redpanda - I added some of this context to the TLS doc and the FIPS doc

2024-11-26 13:38 UTC, michael-redpanda approved these changes

2024-11-26 13:38 UTC, michael-redpanda commented on modules/manage/pages/security/encryption.adoc
> +NOTE: PKCS#12 keys are not supported when xref:manage:security/fips-compliance.adoc[FIPS mode] is enabled in Redpanda. The PKCS12KDF algorithm used in PKCS#12 is not FIPS-compliant. To use Redpanda i
praise: 👍

2024-11-26 16:02 UTC, asimms41 commented on modules/get-started/pages/whats-new.adoc
> +Redpanda now supports configuring TLS using PKCS#12 files, allowing you to manage both the certificate and private key in a single, password-protected file.
```suggestion
Redpanda now supports configuring TLS using PKCS#12 files, which allows you to manage both the certificate and private key in a single, password-protected file.
```

2024-11-26 16:22 UTC, asimms41 approved these changes
Just a couple of minor comments/observations.

2024-11-26 16:22 UTC, asimms41 commented on modules/manage/pages/security/encryption.adoc
> +. Create the CA's private key and set its permissions:
The rendering of the apostrophe on the preview looks a little odd.

2024-11-26 16:22 UTC, asimms41 commented on modules/manage/pages/security/encryption.adoc
> +The output `ca.crt` is the CA's public certificate, which you'll use in the truststore.
Again, the rendering of the apostrophe looks odd?

2024-11-26 16:22 UTC, asimms41 commented on modules/manage/pages/security/encryption.adoc
> +- You prefer file-based configurations with separate key, certificate, and truststore file.
```suggestion
- You prefer file-based configurations with a separate key, certificate, and truststore file.
```

2024-11-26 16:22 UTC, asimms41 commented on modules/manage/pages/security/encryption.adoc
> +If you have separate `key_file`, `cert_file`, and `truststore_file`, use the following configuration in `redpanda.yaml`:
```suggestion
If you have separate a `key_file`, `cert_file`, and `truststore_file`, use the following configuration in `redpanda.yaml`:
```

2024-11-26 16:22 UTC, asimms41 commented on modules/manage/pages/security/encryption.adoc
> +    truststore_file: <path-to-pem-CA-file>
The caps in CA are stopping this from being an editable field.

2024-11-26 16:43 UTC, JakeSCahill commented on modules/manage/pages/security/encryption.adoc
> +. Create the CA's private key and set its permissions:
```suggestion
. Create a private key for the CA and set its permissions:
```

2024-11-26 16:43 UTC, JakeSCahill commented on modules/manage/pages/security/encryption.adoc
> +The output `ca.crt` is the CA's public certificate, which you'll use in the truststore.
```suggestion
The output `ca.crt` is the CA's public certificate, which you'll use in the truststore.
```

2024-11-26 16:44 UTC, JakeSCahill commented on modules/manage/pages/security/encryption.adoc
> +    truststore_file: <path-to-pem-CA-file>
```suggestion
    cert_file: <path-to-pem-cert-file>
    key_file: <path-to-pem-key-file>
    truststore_file: <path-to-pem-ca-file>
```

2024-11-26 17:03 UTC, merged