K8S-380 Add Iceberg info to Topic CRD doc
redpanda-data/documentation pull request #881
Opened 2024-11-29 17:33 UTC by JakeSCahill

## Description

Review deadline: 2 December

Did some testing to make sure the property gets added to the topic in 24.3: https://redpandadata.atlassian.net/browse/K8S-380

## Page previews

https://deploy-preview-881--redpanda-docs-preview.netlify.app/24.3/manage/kubernetes/k-manage-topics/#configure-iceberg-topics

Note: the link to the Iceberg doc will work when #800 is merged

## Checks

- [x] New feature
- [ ] Content gap
- [ ] Support Follow-up
- [ ] Small fix (typos, links, copyedits, etc)

2024-12-02 19:21 UTC, david-yu commented on modules/manage/pages/kubernetes/k-manage-topics.adoc
> +
Should we add a note here saying that an Enterprise license is required?

2024-12-02 19:22 UTC, david-yu approved these changes
LGTM assuming we add enterprise license blurb.

2024-12-03 09:40 UTC, asimms41 commented on modules/get-started/pages/whats-new.adoc
> +== Leader pinning
There are duplicate leader pinning paragraphs in What's new.

2024-12-03 09:41 UTC, asimms41 commented on modules/manage/pages/kubernetes/k-manage-topics.adoc
> +- Tiered Storage is enabled in your Redpanda cluster.
Should Tiered Storage come first with a link to enable this feature?

2024-12-03 09:41 UTC, asimms41 requested changes
Looks good. Not sure how the duplicate leader pinning got in?

2024-12-03 11:06 UTC, asimms41 approved these changes
LGTM

2024-12-03 11:18 UTC, merged