docs:#865 architecture and sizing
redpanda-data/documentation pull request #890
Opened 2022-11-30 19:34 UTC by micheleRP

adding pages for architecture and sizing
also updates index and sidebars

2022-12-02 17:29 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +Before running performance benchmark testing, set Redpanda into production mode and run the auto tuning tool on every node. This enables the necessary hardware optimizations and ensures that the kern
SMEs: What is the auto-tuning too? Is it `rpk iotune`?

2022-12-02 20:29 UTC, micheleRP commented
@jrkinley, @dcoded: Please review this doc based on James's Architecture and Sizing paper. The overview and architecture content is a new page in the Introduction section. The sizing content is in 2 pages in the Deployment section. I'd like to merge this into our doc by Friday, Dec 9th!
Denis: I added you as a PM reviewer for this new content. If someone else from Product should do this instead, please reassign it! 
James: I didn't include the images from your paper. If you want them included, can you please send me the original PNG files?

2022-12-02 22:25 UTC, micheleRP commented
@Feediver1 A reminder that this PR just covers the architecture & sizing info from James's paper. The clean-up of all overview content will go next with https://github.com/redpanda-data/documentation/issues/151 (e.g., the other content in the [intro bucket](https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/introduction/) will change).

2022-12-09 00:22 UTC, micheleRP commented
@jrkinley, @dcoded: Reminder to please review/approve this PR. I expect with issue #151 (hopefully next sprint), the architecture content will move a bit, with the Redpanda features moving into a new introduction and this page containing just Redpanda architecture. @jrkinley please let me know if anything from the existing [Designed for Performance page](https://docs.redpanda.com/docs/platform/introduction/autotune/) should be integrated into this new [Sizing Guidelines page](https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/deployment/sizing/), or if that content should be removed. Thank you!

2022-12-09 15:25 UTC, Feediver1 commented
I'm curious why sizing use cases are not a subtopic of sizing guidelines? Seems weird to have them at the same heading level, as they both fall under the heading: Sizing...Maybe have:
Sizing
  Guidelines
  Use Cases
Thoughts?

2022-12-09 15:29 UTC, Feediver1 commented on docs/platform/deployment/sizing.mdx
> +It’s important to measure the network bandwidth between nodes, and between clients and nodes, to make sure that you’re getting the expected performance from the network. This is especially important
I think AWS actually uses AWS I3en (uppercase "i")

2022-12-09 15:50 UTC, Feediver1 commented on docs/platform/deployment/sizing-use-cases.mdx
> +At this scale, Redpanda generates over three TB of writes each hour and over 80 TB each day. Local storage is going to fill up quickly, and the window of opportunity for consumers to read from local
Make the Tiered Storage reference a link here--especially because you are saying it is essential. Makes it quicker/easier for customer to get there.

2022-12-09 15:51 UTC, Feediver1 commented on docs/platform/deployment/sizing.mdx
> +See also: [Set Redpanda production mode](../../platform/deployment/production-deployment/#set-redpanda-production-mode)
This link doesn't work

2022-12-09 15:53 UTC, Feediver1 approved these changes
See the comments I shared

2022-12-09 15:58 UTC, micheleRP commented
> I'm curious why sizing use cases are not a subtopic of sizing guidelines? Seems weird to have them at the same heading level, as they both fall under the heading: Sizing...Maybe have: **Sizing**
> 
> * Guidelines
> * Use Cases
> 
> Thoughts?

@Feediver1: Yeah, I thought about that, but that would nest it 3 levels in our nav tree (Deployment/PerformanceTuning/Sizing/UseCases). Is that OK? We have rpk commands nested that deep, but no doc pages.

2022-12-09 16:02 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +See also: [Set Redpanda production mode](../../platform/deployment/production-deployment/#set-redpanda-production-mode)
fixed, thanks!

2022-12-09 16:04 UTC, micheleRP commented on docs/platform/deployment/sizing-use-cases.mdx
> +At this scale, Redpanda generates over three TB of writes each hour and over 80 TB each day. Local storage is going to fill up quickly, and the window of opportunity for consumers to read from local
fixed

2022-12-09 16:05 UTC, micheleRP commented on docs/platform/deployment/sizing-use-cases.mdx
> +This use case has many topics, hundreds of partitions, and a high throughput. The combined producer and replication data equates to 8 Gbps of network traffic. Plus 16 Gbps for the consumers and 8 Gbp
fixed

2022-12-09 16:07 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +It’s important to measure the network bandwidth between nodes, and between clients and nodes, to make sure that you’re getting the expected performance from the network. This is especially important
fixed, thanks!

2022-12-12 09:21 UTC, jrkinley requested changes
Redpanda has moved on somewhat since we published the architecture and sizing guide. Specifically with "cloud first" storage in `v22.3` and the latest performance benchmarks. I think these docs need to be refreshed to include some of the latest messaging and positioning covered in: https://redpanda.com/blog/whats-new-in-redpanda-22-3.

2022-12-12 09:21 UTC, jrkinley commented on docs/platform/deployment/sizing-use-cases.mdx
> +title: Sizing Use Cases
I think this information is a little out of date. I suggest we run this past @travisdowns and @tmgstevens for input on what scenarios to include based on recent benchmark / performance testing.

2022-12-12 09:21 UTC, jrkinley commented on docs/platform/deployment/sizing-use-cases.mdx
> +title: Sizing Use Cases
Ideally, this should cover self-hosted (bare metal and VMs) and Redpanda Cloud.

2022-12-12 09:21 UTC, jrkinley commented on docs/platform/deployment/sizing.mdx
> +- MB/sec of data being produced (after compression, if applied)
- MB/sec of data being produced and consumed

2022-12-12 09:21 UTC, jrkinley commented on docs/platform/deployment/sizing.mdx
> +- `retention.ms`: This also controls the size of a partition directory, but it does so based on the age of log segments rather than their combined size. Log segments are discarded when their maximum
As above, the behaviour of `retention.bytes` and `retention.ms` has changed in `v22.3`.

2022-12-12 23:49 UTC, micheleRP commented
> > I'm curious why sizing use cases are not a subtopic of sizing guidelines? Seems weird to have them at the same heading level, as they both fall under the heading: Sizing...Maybe have: **Sizing**
> > 
> > * Guidelines
> > * Use Cases
> > 
> > Thoughts?
> 
> @Feediver1: Yeah, I thought about that, but that would nest it 3 levels in our nav tree (Deployment/PerformanceTuning/Sizing/UseCases). Is that OK? We have rpk commands nested that deep, but no doc pages. Do you mean to move it into a separate Sizing section at the same level as Performance and Tuning?

@Feediver1 can you please confirm: Does your thumbs up mean I should move Sizing Guidelines up to the same level as Performance and Tuning, with Sizing Use Cases nested under it? Or that I should leave the structure as it is right now?

2022-12-13 04:58 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +Key performance metrics:
@jrkinley should we replace this with a link to the metrics: https://docs.redpanda.com/docs/platform/cluster-administration/monitoring/?

2022-12-13 04:59 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +Before running performance benchmark testing, set Redpanda into production mode and run the auto-tuning tool (`rpk redpanda tune all`) on every node. This enables the necessary hardware optimizations
@jrkinley please confirm if `rpk redpanda tune all` is correct here.

2022-12-13 05:01 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +Key performance metrics:
@jrkinley should we replace this list of key performance metrics with a link to the latest metric doc page: https://docs.redpanda.com/docs/platform/cluster-administration/monitoring/?

2022-12-15 16:37 UTC, micheleRP commented
Status: Adding @tmgstevens and @travisdowns as reviewers for input on what scenarios to include based on recent benchmark / performance testing. Per James: ideally, this should cover self-hosted (bare metal and VMs) and Redpanda Cloud.

2022-12-20 15:18 UTC, micheleRP commented
Marking as blocked until Travis and Tristan can review.

2022-12-21 16:14 UTC, tmgstevens commented on docs/platform/deployment/sizing.mdx
> +- Test with I3en (AWS), n2-standard (GCP), and lsv2 (Azure) cloud instance types
Type: I3 should be i3

2023-01-10 01:50 UTC, shorgi commented on docs/platform/deployment/sizing.mdx
> +A basic Redpanda cluster can have three nodes, a topic with a single partition and a replication factor of three, and a single producer and consumer. For every 100 MB written to the partition’s leade
```suggestion
To understand the network usage of a basic Redpanda cluster, consider a cluster with three nodes, a topic with a single partition and a replication factor of three, and a single producer and consumer. For every 100 MB written to the partition’s leader, 200 MB is transmitted across the network to other nodes for replication, and 100 MB is transmitted to the consumer. In this case, producing 100 MB/sec equates to 400 MB/sec (3,200 Mbps) of network traffic. Even with the same amount of data produced, increasing the replication factor or the number of consumers increases bandwidth utilization.
```

2023-01-10 01:50 UTC, shorgi commented on docs/platform/deployment/sizing.mdx
> +Topic partitions are the unit of parallelisation in Redpanda. Adding partitions is how you scale to meet workload demands. Redpanda is designed to scale up to utilize all available hardware and scale
```suggestion
Redpanda is designed to scale up to utilize all available hardware and scale out to distribute performance across multiple nodes. Topic partitions are the unit of parallelization in Redpanda. Adding partitions is how you scale to meet workload demands. 
```

2023-01-10 01:50 UTC, shorgi commented on docs/platform/deployment/sizing.mdx
> +Redpanda can handle approximately one GB/sec of writes for each core, depending on the workload. Since NVMe disks can have a sustained write speed of over one GB/sec, it takes two cores to saturate a
```suggestion
Redpanda can handle approximately one GB/sec of writes for each core, depending on the workload. Since NVMe disks can have a sustained write speed of over one GB/sec, it takes two cores to saturate a single NVMe disk. At higher throughput rates, a 2:1 core-to-disk ratio is important to avoid I/O bottlenecks, so a minimum of four cores is needed.
```

2023-01-10 01:50 UTC, shorgi commented on docs/platform/deployment/sizing.mdx
> +Redpanda is basically a distributed transaction log, with well-understood access patterns. It appends data to the end of log files, and sequentially reads data from log files. For this reason, Redpan
```suggestion
Redpanda is basically a distributed transaction log with well-understood access patterns. It appends data to the end of log files and sequentially reads data from log files. For this reason, Redpanda bypasses the Linux page cache and manages its own memory and disk I/O. This gives Redpanda complete control over the underlying hardware to optimize I/O performance, deliver predictable tail latencies, and minimize its memory footprint. A minimum of two GB of memory for each core is recommended, but more is better.
```

2023-01-10 01:50 UTC, shorgi commented on docs/platform/deployment/sizing.mdx
> +If high throughput and low latency is most important, then use locally-attached NVMe SSD disks. This is also a good option in the cloud. Just remember that local disks are ephemeral and data is wiped
What are `hyper-clouds`?

2023-01-10 01:50 UTC, shorgi commented on docs/platform/deployment/sizing.mdx
> +Redpanda Tiered Storage enables multi-tiered remote storage that archives log segments to object storage in near real time. Tiered Storage can be combined with local storage to provide infinite data
```suggestion
Redpanda Tiered Storage enables multi-tiered remote storage that archives log segments to object storage in near real time.

With only local storage, data retention is limited to the provisioned capacity: you must provision more nodes to increase capacity. Adding nodes is expensive, because you’re forced to overprovision infrastructure regardless of whether you need the additional compute power. In most cases, overprovisioning leads to underutilization and higher operational costs.

Tiered Storage can be combined with local storage to provide infinite data retention and disaster recovery on a per-topic basis. Retention properties work the same for Tiered Storage topics and local storage topics. Data is retained in the cloud until it reaches the configured time or size limit. 
```

2023-01-10 13:26 UTC, tmgstevens commented on docs/platform/deployment/sizing-use-cases.mdx
> +| Persistent Storage | - | - | - | 20 TB (Standard SSD) |
```suggestion
| Persistent Storage | - | - | - | 20 TB (Standard SSD) |
| Available Local Retention | 17 hrs | 8 hrs | 5 hrs | 9 days |
```

2023-01-10 13:26 UTC, tmgstevens commented on docs/platform/deployment/sizing-use-cases.mdx
> +Producing an average of 500 MB every second equates to over 40 TB of data each day. With a retention period of one year, the cluster needs over 14 PB of storage. This is more than can be squeezed int
```suggestion
Producing an average of 500 MB every second equates to over 40 TB of data each day. With a retention period of one year, the cluster needs over 14 PB of storage. This is more than can be squeezed into three nodes, so you’re forced to overprovision just to handle the data retention requirements. This isn’t an issue in the cloud with high-performance persistent storage options (like io2 in AWS, Extreme PD in GCP, and Ultra SSD in Azure), but at this scale, it’s very expensive.

A consideration for balancing the available local disk is exactly how many reads can be serviced from local storage. With difference instance types or attached SSDs/NVMe we result in differing amounts of local storage and hence amount of data that is available without going back to the cloud.
```

2023-01-10 13:26 UTC, tmgstevens commented on docs/platform/deployment/sizing.mdx
> +- Run hardware and Redpanda benchmark tests to provide a performance baseline
```suggestion
- Run hardware and Redpanda benchmark tests to provide a performance baseline
- The number of nodes should be chosen based on the above criteria and additional nodes added for fault tolerance. This ensure that the system can operate with full throughput in a degraded state.
```

2023-01-10 22:22 UTC, micheleRP commented on docs/platform/deployment/sizing-use-cases.mdx
> +At this scale, Redpanda generates over three TB of writes each hour and over 80 TB each day. Local storage is going to fill up quickly, and the window of opportunity for consumers to read from local
@shorgi: I agree that it reads better in that instance as 3.

2023-01-10 22:32 UTC, hcoyote commented on docs/platform/deployment/sizing-use-cases.mdx
> +At this scale, Redpanda generates over three TB of writes each hour and over 80 TB each day. Local storage is going to fill up quickly, and the window of opportunity for consumers to read from local
Somewhat related: what's our style recommendations around abbreviating bits vs bytes? Does it make sense to be explicit (e.g. TBytes, MBytes) especially given we do this in some of the network bandwidth sizing (Mbps)?

2023-01-10 22:49 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +- Test with i3en (AWS), n2-standard (GCP), and lsv2 (Azure) cloud instance types
fixed

2023-01-10 23:03 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +This is encapsulated in the Kafka API, so clients can continue to produce and consume data from Redpanda in the same way. Consumers that keep up with producers continue to read from local storage and
> 

Thanks @hcoyote. Please let me know if this section is still confusing: https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/deployment/sizing/#tiered-storage

2023-01-10 23:32 UTC, micheleRP commented on docs/platform/deployment/sizing-use-cases.mdx
> +Producing an average of 500 MB every second equates to over 40 TB of data each day. With a retention period of one year, the cluster needs over 14 PB of storage. This is more than can be squeezed int
Thanks @tmgstevens. I added this as: "To balance the available local disk, consider exactly how many reads can be serviced from local storage. Different instance types or attached SSDs/NVMe provide different amounts of local storage, so different amounts of available data without going back to the cloud." Please let me know if my rewrite is not clear or correct.

2023-01-10 23:55 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +Whichever option you choose, benchmark Redpanda’s underlying storage for read and write performance, at least from an I/O perspective. FIO is a good tool for replicating Redpanda’s sequential write p
added this

2023-01-11 00:00 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +The following example uses [iPerf3](https://iperf.fr/) to test the network bandwidth between two Debian-based servers:
added

2023-01-11 00:02 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +If high throughput and low latency is most important, then use locally-attached NVMe SSD disks. This is also a good option in the cloud. Just remember that local disks are ephemeral and data is wiped
> What are `hyper-clouds`?

@shorgi this isn't in the text anymore. It's rewritten as:
If high throughput and low latency is most important, then use locally-attached NVMe SSD disks. This is also a good option in the cloud. Just remember that in the cloud, local disks are ephemeral, so data is wiped when an instance is restarted. An alternative in the cloud is to use SSD-backed remote storage to persist data between instance restarts. Most cloud providers have options for guaranteeing throughput and provisioned IOPS performance of network-attached storage, although network-attached storage almost always exhibits slightly higher tail latencies than direct-attached storage.

2023-01-11 16:02 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +Before running performance benchmark testing, set Redpanda into production mode and run the auto tuning tool on every node. This enables the necessary hardware optimizations and ensures that the kern
I think it's both, but there is some complication around containers: running redpanda in a container is more complicated because (a) I am not sure the `rpk` well-known-io detection logic will work inside a container or it may depend on the container networking config (see https://redpandadata.slack.com/archives/C024H6DSU2H/p1673450827074599) and (b) it is less clear how to run `rpk iotune`: you can't just run it on the host or inside the container, probably it has to be run on the host then the results written to somewhere accessible to the container, which we don't really document.

In general we don't document much about `rpk iotune` except that it exists and you should run it: probably an area for improvement?

2023-01-11 16:24 UTC, travisdowns commented on docs/platform/deployment/sizing-use-cases.mdx
> +This use case uses the minimum number of Redpanda nodes. Despite the relatively low throughput of 150 MB/sec (producer and consumer), it’s important to calculate the expected bandwidth utilization an
Change `for the consumer group` to `for the consumers`.

2023-01-11 16:25 UTC, travisdowns commented on docs/platform/deployment/sizing-use-cases.mdx
> +
It is a bit unclear that we say "this case uses the minimum number of nodes" but doesn't mention how many that is in the table or in this paragraph.

2023-01-11 17:11 UTC, travisdowns commented on docs/platform/deployment/sizing-use-cases.mdx
> +
I think we need to be clearer about the network bandwidth when it comes to the number of nodes. We get a figure of 300 MB/s but that's spread across the N nodes in a specific way. It's note that each node needs 300 MB/s of full-duplex bandwidth.

Maybe we can talk about what a single node needs?

Also, the 150 MB/s of bandwidth for the replicas is full duplex (each byte send by a broker is received by some other broker), but the 75 MB/s producer and consumer flows are half-duplex since the client "endpoint" in each case is outside of the cluster. Probably we should mention the intra-cluster bandwidth separately, so it would be like:

150 MB/s of intra-cluster full duplex bandwidth
75 MB/s of ingress from producers
75 MB/s of egress to consumers

So in total 225 MB of both incoming and outgoing flows>

All of those numbers would be divided by the node count (3, here) to get the per-node BW requirements, under the "fully balanced" scenarios.

Note that this also discards other sources of network traffic, protocol overhead and so on. So I think you'd want at least a 2x buffer here.

2023-01-11 17:25 UTC, hcoyote commented on docs/platform/deployment/sizing-use-cases.mdx
> +
I spent time reasoning through this yesterday. I think the 300MB/s is accurate from the leader's perspective. And to account for failovers, you have to have the same available bandwidth capacity for each follower that has the potential to take over.

It seems to get complicated as you get more topics, partitions, and replicas.

2023-01-11 18:58 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +Redpanda can handle approximately one GB/sec of writes for each core, depending on the workload. Since NVMe disks can have a sustained write speed of over one GB/sec, it takes two cores to saturate a
I don't think this is the right way of thinking about it: a 2:1 ratio might be right for some specific combination of disks, but "1 disk" is not a specific unit of performance: disks might reasonable range anywhere from 0.1 to 4+ GB/s in throughput, while cores have a much smaller performance range. Furthermore, the cloud blurs what even is a "disk", since physical disks may be logically partitioned up among tenants and with network storage with configurable performance characteristics making a 2:1 ratio even less meaningful.

For the disk, what matters most is IOPS and throughput. For throughput, we could do something similar to network bandwidth where we describe how to calculate the aggregate write bandwidth needed, etc.

How many cores we need is a very complicated topic, in line with the _general caveat_. Maybe we should just say something very ballpark like 100 MB/s per core for now.

2023-01-11 19:26 UTC, travisdowns commented on docs/platform/deployment/sizing-use-cases.mdx
> +
@hcoyote - the assumption is that every node is both a leader and a follower, and the above analysis assumes a sufficient number of partitions for good distribution [1]. So the analysis considers a "typical" node which is the leader for 1/Nth of the partitions in a cluster with N nodes, and a follower for 2/Nths of the partitions.

My claim is the 300 MB/s is wrong in two ways:

 - It is more like 225 MB/s full duplex. The difference is because the replication traffic is full duplex (wrt the cluster) while the producer & consumer traffic is half duplex (one of the endpoints is outside the cluster).
 - This is the _total bandwidth_ needed across all nodes so for the purposes of benchmarking e.g., you would probably want a per-node figure, so you should divide by 3: each node needs to be capable of 75 MB/s full-duplex bandwidth, not 300 MB/s.
 
Here's another way to do the reasoning.

Consider 1 second worth of 75/75 (producer/consumer) MB/s traffic, which is 75 MB in from producers and 75 out to consumers. Focusing only _one_ node and considering that this is correct also for the other two nodes but just for different bytes in that 75 MB payload:

- The 75 is split 3 days, so each node will handle 25 MB of producer (in) + 25 MB of consumer traffic (out)
- With N=3 and `r=3` every partition is replicated on every node (1 leader + 2 followers)
- So the node we focus on sends that 25 MB out to both replicas (2 x 25 MB out).
- By symmetry, it will also receive 25 MB from each replication (50 MB in)


So that's totally 75 out and 75 in. Every node is the same, so summing all nodes it's 225 in and 225 out, or 450 total if we count bandwidth in a half-duplex way. However, as above I think the "per node" value is more useful since you need to check "does this machine type provide X bandwidth" rather than caring about the sum of all bandwidth requirements across the cluster. Also, as mentioned, I think many customers will want to handle the 25 MB/s external ingress/egress differently than the 50 MB/s intra-cluster traffic since it may have totally different performance limitations depending on the network infra (and different costs).

If your analysis disagrees, can you show me where?

2023-01-11 19:41 UTC, travisdowns commented on docs/platform/deployment/sizing-use-cases.mdx
> +
I should add that though the above assumes "evenly distributed load" the totals end up the same regardless of the distribution, but the per node values would vary a lot.

That's another reason you need some headroom: to account for the inexact distribution of load (which can be both because our own partition balancing may not be even over the topics of interest, or also because the customer or client library does not write to each partition evenly).

2023-01-11 19:44 UTC, micheleRP commented on docs/platform/introduction/architecture.mdx
> +If a follower triggers an election, but the incumbent leader subsequently springs back to life and starts sending data again, then it’s too late. As part of the election process, the follower (now an
this page now is in a different branch, but I'll incorporate this feedback there!

2023-01-11 20:33 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +$ sudo vim fio-seq-write.job
I don't think `vim` makes sense here. Probably something like:

```
cat > fio-seq-write.job <<EOF
... (file contents>
EOF
```

2023-01-11 20:37 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +- MB/sec of data being produced and consumed (after compression, if applied)
Better to say "Throughput of data ..." I think.

2023-01-11 20:38 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +- Have a 2:1 core-to-local-disk ratio for maximum I/O performance (preferably NVMe SSD).
Per other comment, I think this 2:1 core-to-disk ratio is mostly meaningless.

2023-01-11 20:39 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +- Have a minimum of 2 GB memory for each core, but more memory is better.
Maybe we should say "per shard" not "per core"? Because I assume we are trying to recommend 2 GB per _shard_ but _core_ could be 1 or 2 shards depending on hyperthreading and also customer may not assign all shards to cores.

2023-01-11 20:43 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +- Test with i3en, i4i, is4gen (AWS), n2-standard (GCP), and lsv2 (Azure) cloud instance types.
This seems like an unusual order to a user? They should test on every cloud type? Or maybe I'm reading it wrong, and it is trying to say: _If_ you are on AWS, try these 3 types, and _if_ you are GCP ... ?

In that case it may need to restructured since there is only 1 option listed for GCP and Azure.

2023-01-11 20:46 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +To understand the network usage of a basic Redpanda cluster, consider a cluster with three nodes, a topic with a single partition and a replication factor of three, and a single producer and consumer
As mentioned in the other doc, the 100 + 200 + 100 isn't exactly right because the 200 part (replication) requires bandwidth to both send and receive (since both endpoints are in the cluster) while the 100 values have only 1 end in the cluster. So if we count send + recv seperately (i.e., 1 broker sending 1 byte to another counts as 1 + 1 = 2) then it's 100 + 200 * 2 + 100.

2023-01-11 20:50 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +It’s important to measure the network bandwidth between nodes, and between clients and nodes, to make sure that you’re getting the expected performance from the network. This is especially important
On AWS network bandwidth is guaranteed also on the smaller instance sizes, but AWS just chooses to list the burst bandwidth ("up to 25 Gbps") on the main overview pages. 

See here for the values:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/storage-optimized-instances.html

Where it shows that i3en.3xlarge has a guaranteed bandwidth of 12.5 Gbps which is half that of the 6x instance size, so exactly in line with its size.

This advice is still correct in spirit because short tests may use only the burst bandwidth and get unrealistically good results because of it, but I think this should be re-worked to just mention the way bursting works and how to avoid testing only the burst bandwidth rather than making a claim about "lack of guaranteed bandwidth".

2023-01-11 20:52 UTC, travisdowns commented on docs/platform/deployment/sizing.mdx
> +To do a full network stress test, run iperf3 for every combination of network routes. Unlike iperf2, iperf3 does not accept multiple network connections.
What this is asking the user to do is not clear to me. Also, why do we mention iperf2 if we aren't using it?

2023-01-11 23:11 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +To do a full network stress test, run iperf3 for every combination of network routes. Unlike iperf2, iperf3 does not accept multiple network connections.
@travisdowns: I think this was suggested by @hcoyote. I removed the last line. Please see https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/deployment/sizing/#network and let me know if it's OK.

2023-01-11 23:12 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +It’s important to measure the network bandwidth between nodes, and between clients and nodes, to make sure that you’re getting the expected performance from the network. This is especially important
@travisdowns: Please review this edited section: https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/deployment/sizing/#sizing-considerations

2023-01-11 23:16 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +To understand the network usage of a basic Redpanda cluster, consider a cluster with three nodes, a topic with a single partition and a replication factor of three, and a single producer and consumer
@travisdowns: Please see this edited section (I used the same values we used in the sizing use cases page): https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/deployment/sizing/#network

2023-01-11 23:16 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +- Test with i3en, i4i, is4gen (AWS), n2-standard (GCP), and lsv2 (Azure) cloud instance types.
fixed

2023-01-11 23:17 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +- MB/sec of data being produced and consumed (after compression, if applied)
@travisdowns: I'm not positive that I read your suggestion correctly. Please let me know if this is correct: https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/deployment/sizing/

2023-01-11 23:21 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +$ sudo vim fio-seq-write.job
Hi @shorgi. Would you please help me make this edit? https://github.com/redpanda-data/documentation/pull/890#discussion_r1067431877

2023-01-11 23:23 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +Redpanda can handle approximately one GB/sec of writes for each core, depending on the workload. Since NVMe disks can have a sustained write speed of over one GB/sec, it takes two cores to saturate a
@travisdowns: Please confirm if this is correct: https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/deployment/sizing/#cpu-and-memory

2023-01-11 23:24 UTC, micheleRP commented on docs/platform/deployment/sizing-use-cases.mdx
> +
Thank you for the detailed description, @travisdowns and @hcoyote--this was very helpful to me! Please review this edited section: https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/deployment/sizing-use-cases/#low-throughput-short-retention. There's also similar content now in the Sizing Guidelines pages.

2023-01-11 23:40 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +This topic describes sizing considerations. In general:
No, the bullets don't exactly align with the sections.

2023-01-11 23:42 UTC, micheleRP commented on docs/platform/deployment/sizing-use-cases.mdx
> +Three nodes satisfy Redpanda’s minimum deployment requirement (so Raft can form quorums) and also the single node failure tolerance. The throughput is not high enough to warrant any more than two cor
> Does `how much room the cluster has` refer to CPU and/or disk margin?

@travisdowns I added this suggestion to this paragraph: "Be mindful of predicted growth of CPU and/or disk usage, and estimate when the cluster might need to scale up or scale out." Please let me know if that's not correct.

2023-01-11 23:45 UTC, micheleRP commented on docs/platform/deployment/sizing-use-cases.mdx
> +This use case uses the minimum number of Redpanda nodes. Despite the relatively low throughput of 150 MB/sec (producer and consumer), it’s important to calculate the expected bandwidth utilization an
@tmgstevens: Could you please review the latest draft of this (which includes feedback from Travis Downs), and then confirm for me what changes you want here? Are you saying that all 3 use cases should use Tiered Storage? And that all of the 20 TB storage should change to 7 TB? See  https://deploy-preview-890--redpanda-documentation.netlify.app/docs/platform/deployment/sizing-use-cases/#low-throughput-short-retention

2023-01-12 00:29 UTC, micheleRP commented on docs/platform/deployment/sizing-use-cases.mdx
> +title: Sizing Use Cases
@jrkinley: Travis and Tristan have reviewed this now. Could you please review this updated pull request and approve? Hoping to merge it by Friday.

2023-01-12 10:54 UTC, tmgstevens commented on docs/platform/deployment/sizing.mdx
> +iodepth=16
```suggestion
```bash
$ sudo apt -y update; sudo apt -y install fio
$ cd /var/lib/redpanda/data
$ sudo cat < fio-seq-write.job << EOF
[global]
name=fio-seq-write
filename=fio-seq-write
rw=write
bs=16K
direct=1
numjobs=4
group_reporting
time_based
runtime=300 # 5 minute runtime
[file1]
size=10G
ioengine=libaio
iodepth=16
EOF
```

2023-01-12 10:55 UTC, tmgstevens commented on docs/platform/deployment/sizing.mdx
> +Key performance metrics:
No, these are specifically referring to fio

2023-01-12 14:52 UTC, vuldin reviewed
This isn't a full review, but just a few comments.

2023-01-12 14:52 UTC, vuldin commented on docs/platform/deployment/sizing.mdx
> +- Have a minimum of 2 GB memory for each shard, but more memory is better.
At some point we probably need to have a page to point users where they can find the answer to the question: "what is a shard?" But for now maybe its best to replace shard with core to avoid confusion?

```suggestion
- Have a minimum of 2 GB memory for each core, but more memory is better.
```

2023-01-12 14:52 UTC, vuldin commented on docs/platform/deployment/sizing.mdx
> +- For AWS, test with either i3en, i4i, or is4gen; for GCP, test with n2-standard (GCP); and for Azure, test with lsv2.
```suggestion
- For AWS, test with either i3en, i4i, or is4gen; for GCP, test with n2-standard (GCP); and for Azure, test with lsv2. In general, choose instance types that prioritize storage and network performance.
```

2023-01-12 15:12 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +iodepth=16
Thank you @tmgstevens!

2023-01-12 16:19 UTC, hcoyote commented on docs/platform/deployment/sizing-use-cases.mdx
> +
Ok, that definitely makes sense in a well-balanced scenario. I guess 300MB/s would be worst-case, assuming something went horribly wrong and cluster balancing wasn't working (and everything got somehow pinned to one leader node)

2023-01-12 16:40 UTC, hcoyote commented on docs/platform/deployment/sizing.mdx
> +- Total network bandwidth must account for writes, replication, and reads.
typo: "max rights" should probably be "max writes"

2023-01-12 17:15 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +- Total network bandwidth must account for writes, replication, and reads.
Thanks @vuldin and @hcoyote. I changed this list item to:
* Total network bandwidth must account for maximum simultaneous writes and reads, multiplied by the replication factor.

2023-01-12 18:40 UTC, hcoyote commented on docs/platform/deployment/sizing.mdx
> +To do a full network stress test, run iperf3 for every combination of network routes. Unlike iperf2, iperf3 does not accept multiple network connections.
wasn't me. not sure what that comment referred to. while iperf2 server supported multiple client connections in parallel, a single server wouldn't do the full cross-sectional test (e.g. N to N pathways). but I agree that taking it out is right.

Basically, we want the user to test for a 3-node environment:

NodeA <-> Node B
NodeB <-> Node C
NodeC <-> Node A

Might actually be good to come with a standalone ansible runbook or something to help them do this test.

2023-01-12 20:50 UTC, micheleRP commented on docs/platform/deployment/sizing.mdx
> +Before running performance benchmark testing, set Redpanda into production mode and run the auto tuning tool on every node. This enables the necessary hardware optimizations and ensures that the kern
Thanks @travisdowns. I added info this to issue #979.

2023-01-13 17:07 UTC, jrkinley approved these changes

2023-01-13 17:23 UTC, hcoyote commented on docs/platform/deployment/sizing.mdx
> +To do a full network stress test, run iperf3 for every combination of network routes. Unlike iperf2, iperf3 does not accept multiple network connections.
btw, we can probably expand the details on iperf testing in another issue, it doesn't need to hold this up.

2023-01-13 18:14 UTC, merged