docs: Get started Kubernetes tutorial
redpanda-data/documentation pull request #920
Opened 2022-12-09 17:40 UTC by JakeSCahill

Fixes #873

Pre-merge TODOs:

- [ ] Linux instructions for external access with kind (@joejulian please could you help with that part. I need some realistic sample output and I can't produce it myself without Linux)

2022-12-10 00:22 UTC, joejulian requested changes
I think some context has been lost. In the section titled `Configure external access to the Redpanda brokers using IP addresses`, most of it is about how to use external access by hostname. Should we just change it to `Configure external access`?

2022-12-12 09:19 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> -* [Go](https://go.dev/doc/install) - v1.17 or later (only required for Windows setup)
this was from @vuldin:

> The reason is EKS. So as of now we are using EKS 0.114.0 (I think). This version comes with kubernetes 1.22. There is a new eksctl, but it updates to a new kubernetes version and also changes some other things that right now breaks the install. So the docs stick to that older EKS version so anyone following along will not run into issues.

@vuldin is this still valid?

2022-12-12 09:20 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> -* [Go](https://go.dev/doc/install) - v1.17 or later (only required for Windows setup)
@joejulian I think the sections are needed. Not all of those prerequisites apply to all platforms. For example, links to minikube installation or the EBS CSI. Since we use tabs to separate content by platform elsewhere, it's a more consistent user experience to use tabs in the prerequisites.

2022-12-12 09:27 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +The kind tool is meant for local testing. To test external access, use GKE or EKS.
Yes. It doesn't seem to work on macOS. Please could you provide the steps for kind like we have for minikube?

2022-12-12 09:34 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +## Inspect the Kubernetes components
This part is about teaching users what's included in their deployment. We are writing for the developer persona who may not be an expert in Kubernetes or Redpanda so this part provides the contextual information for the following steps.

Maybe we can use 'Explore the Kubernetes components'?

2022-12-12 09:36 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +* [One PersistentVolumeClaim](#persistentvolume) for each Pod, each with a capacity of 20Gi.
Since the PersistenVolumeClaim is an important component in the deployment, and we explain what it's for in this section, I think we still need the bullet.

Maybe we can edit the leading sentence to something more generic like: 'Your deployment includes the following components by default:

2022-12-12 10:10 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +The kind tool is meant for local testing. To test external access, use GKE or EKS.
I left an empty space for them here:

```
<Tabs groupId="kubernetes-platforms">
<TabItem value="kind" label="kind" default>

<Tabs groupId="operating-systems">
<TabItem value="linux" label="Linux" default>

Linux instructions here

</TabItem>
```

2022-12-12 14:20 UTC, vuldin commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> -* [Go](https://go.dev/doc/install) - v1.17 or later (only required for Windows setup)
The reason there are specific restrictions on Kubernetes, kubectl, and eksctl versions here is because of the new requirement in more recent versions of EKS for installing the Amazon EBS CSI driver. It would be great if we could standardize versions across all quickstart paths.

We have also listed this driver as a requirement, which is a good step towards being able to call out these versions. But I don't think linking to the page as we currently do is sufficient for the quickstart, as the steps to get up and running are not easily found.

I feel these steps are the best way to handle this:
- remove the version differences from the EKS path as Joe suggested
- list the [specific commands](https://github.com/redpanda-data/documentation/issues/738#issuecomment-1287561872) the user must run in order to install the new CSI driver

2022-12-12 16:29 UTC, vuldin reviewed
This looks almost complete to me... I only have one remaining question.

2022-12-12 16:29 UTC, vuldin commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +<TabItem value="linux" label="Linux" default>
It looks like this section is missing for kind, but it exists for minikube. Would it be possible to copy over the minikube docs and then slightly modify to fit kind on Linux?

2022-12-12 16:32 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +<TabItem value="linux" label="Linux" default>
Yes, exactly. I added this to the pre-merge TODOs. It seems that the `/etc/hosts` method works only on Linux. I'd love to have the kind instructions before we merge if someone can provide those with the outputs like we have for minikube.

2022-12-12 16:52 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +## Inspect the Kubernetes components
Agreed. I'll add a generic note about getting started tips being displayed. I'll also work some of those `rpk` commands into the doc.

2022-12-12 16:53 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +  ```
Agreed. I'll add a generic note about getting started tips being displayed. I'll also work some of those rpk commands into the doc.

2022-12-12 17:31 UTC, vuldin commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +<TabItem value="linux" label="Linux" default>
Ahh, I see you did call this out. I can take a look at this section but it may take longer than we want in order to merge. Maybe we could add a note here that says something like "This section is being worked on" or something similar. Another option would be to just remove this tab for now.

2022-12-12 21:43 UTC, Feediver1 commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +This tutorial uses the recommended Helm chart. For information about the older Redpanda Operator, see [Redpanda Operator](../../reference/redpanda-operator).
This seems a bit vague/confusing. Our customers/readers might not clearly understand what is meant by "older" here (as internal users/Redpanda employees, we have knowledge that can fill in such a gap - what about our customers?) Can you add more detail, and perhaps clarify under what conditions a customer might want to refer to our Operator content vs this Helm chart guidance?

2022-12-12 21:45 UTC, Feediver1 commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +## Inspect the Kubernetes components
+1 on your suggestion here @JakeSCahill

2022-12-12 21:49 UTC, Feediver1 commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +<TabItem value="linux" label="Linux" default>
Given that this goes onto our live site, we would not have a note like ""This section is being worked on". I'd suggest either wait to merge and get that material in here, or, merge this PR and create an issue to get the missing material added ASAP. Your call @JakeSCahill.

2022-12-13 00:58 UTC, vuldin commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +This tutorial uses the recommended Helm chart. For information about the older Redpanda Operator, see [Redpanda Operator](../../reference/redpanda-operator).
At one point I explained the differences between the two helm charts in the README of the helm chart [here](https://github.com/redpanda-data/helm-charts/commit/7edf690fa9f995f382c7ea9775a8920f4848d4d6).

2022-12-13 01:35 UTC, vuldin commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +<TabItem value="linux" label="Linux" default>
I'll remove my block since I'm fine either way.

2022-12-13 01:38 UTC, vuldin approved these changes
LGTM. We discussed the missing Kind/Linux section and I'm fine with it either being included in this PR or in a separate PR to follow. I also linked to how I explained the differences between our two helm charts at one point [here](https://github.com/redpanda-data/documentation/pull/920/files#r1046560747).

2022-12-13 12:35 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +<TabItem value="linux" label="Linux" default>
I decided to set up a Linode server for myself so that I can test it out. It'll be useful for the future too.

2022-12-13 18:39 UTC, JakeSCahill commented on docs/platform/quickstart/kubernetes-qs-dev.mdx
> +This tutorial uses the recommended Helm chart. For information about the older Redpanda Operator, see [Redpanda Operator](../../reference/redpanda-operator).
New content is in a collapsed section with a CTA explicitly for users who are looking for the Redpanda Operator:

If you're an existing user of the Redpanda Operator, see the Redpanda Operator documentation.

Warning: Redpanda does not recommend the Redpanda Operator for new deployments. The Redpanda Operator was built for Redpanda Cloud and has unique features and workflows for that specific use case. If you're not already using the Redpanda Operator, continue with this tutorial to get started with the `redpanda` Helm chart.

2022-12-13 21:32 UTC, joejulian approved these changes

2022-12-14 16:12 UTC, Feediver1 approved these changes

2022-12-14 16:13 UTC, merged