console: Add recently added config properties
redpanda-data/documentation pull request #933
Opened 2022-12-13 00:29 UTC by weeco

Adds the currently undocumented configuration properties which have been added in the latest minor or patch release

2022-12-14 14:19 UTC, JakeSCahill requested changes

2022-12-14 14:19 UTC, JakeSCahill commented on docs/platform/console/reference/config.mdx
> +  # Cookies in Console are used to store user's session data. The session data
We can simplify this paragraph. How about:

`Console stores users' session data in cookies with no fixed size. Because some browsers enforce maximum size limits on cookies, you can enable useCookieChunking to split a single big cookie into multiple smaller ones. When useCookieChunking is enabled, cookies are kept below 4KiB, which is a maximum size limit that is set by most browsers.`

2022-12-14 14:19 UTC, JakeSCahill commented on docs/platform/console/reference/config.mdx
> +    # By default, the baseDir/root is used to import proto files from. To use
How about:

importPaths is a list of paths from which to import Proto files into Redpanda Console. Paths are relative to the (base?root?) directory.

2022-12-14 14:19 UTC, JakeSCahill commented on docs/platform/console/reference/config.mdx
> +    # By default, the baseDir/root is used to import proto files from. To use
How are we defining the difference between base directory and root directory?

2022-12-14 14:19 UTC, JakeSCahill commented on docs/platform/console/reference/config.mdx
> +    # By default, the baseDir/root is used to import proto files from. To use
Is this configuration only relevant if you set `git.enabled`?

2022-12-14 15:05 UTC, weeco commented on docs/platform/console/reference/config.mdx
> +# By default sending anonymized usage statistics is enabled. The data is
All grammar improvements are always fine by me. Do you mind pushing them straight into the PR or submitting them as code suggestions so that it's easier to apply? I have several PRs opened here and the effort to apply the feedback is higher than needed otherwise I believe.

2022-12-14 15:09 UTC, weeco commented on docs/platform/console/reference/config.mdx
> +    # By default, the baseDir/root is used to import proto files from. To use
> Is this configuration only relevant if you set git.enabled?

Yes. It would make sense to add for the file system provider as well, but it doesn't exist today.

> How are we defining the difference between base directory and root directory?

Synonyms in that context

2022-12-14 15:28 UTC, JakeSCahill commented on docs/platform/console/reference/config.mdx
> +  # limit of 4KiB.
```suggestion
# Redpanda Console stores users' session data in cookies with no fixed size.
# Because some browsers enforce maximum size limits on cookies, you can enable useCookieChunking 
# to split a single big cookie into multiple smaller ones.
# When useCookieChunking is enabled, cookies are kept below 4KiB, 
# which is a maximum size limit that is set by most browsers.
```

2022-12-14 15:32 UTC, JakeSCahill reviewed
Added suggestions now that I know how to suggest over multiple lines 😄

2022-12-14 15:32 UTC, JakeSCahill commented on docs/platform/console/reference/config.mdx
> +# evaluate feature usage.
```suggestion
# analytics configures the telemetry service that sends anonymized usage statistics to Redpanda.
# Redpanda uses these statistics to evaluate feature usage.
```

2022-12-14 15:32 UTC, JakeSCahill commented on docs/platform/console/reference/config.mdx
> +    # This flag only affects the git provider.
```suggestion
    # importPaths is a list of paths from which to import Proto files into Redpanda Console.
    # Paths are relative to the root directory.
    # The `git` configuration must be enabled to use this feature.
```

2022-12-15 11:06 UTC, JakeSCahill approved these changes

2022-12-15 15:23 UTC, weeco commented
Thanks @JakeSCahill !

2022-12-15 15:23 UTC, merged