console: Add guide for troubleshooting oidc
redpanda-data/documentation pull request #940
Opened 2022-12-14 12:00 UTC by weeco

I added two guides which are supposed to help troubleshooting when using the generic OIDC provider. They are not very straightforward, but this is currently the best what we can do until we spend more time on improving the behaviour.

2022-12-14 14:51 UTC, JakeSCahill requested changes

2022-12-14 14:51 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +If you used a claim key in the role bindings that did not exist in the id token, Console will print
Question about terminology: A code comment above `userIdentifyingClaimKey` uses the phrase `identity provider's issued access token payload`. Is it called an ID token or an access token? We should be consistent.

```suggestion
If the claim key in a role binding does not exist in the ID token, Redpanda Console prints
```

2022-12-14 14:51 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +> ```
No need for the `>` symbols.

2022-12-14 14:51 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +The error message may look similar to this:
```suggestion
Here is an example error message:
```

2022-12-14 14:51 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +that Console tried to look up, as well as all existing claim keys for this specific user.
```suggestion
that Redpanda Console tried to look up, as well as all existing claim keys for this specific user.
```

2022-12-14 14:51 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +If you are unsure what claim keys and values would be attached to your id token by your identity provider,
```suggestion
If you are unsure about which claim keys and values are attached to your id token by your identity provider,
```

2022-12-14 14:51 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +### User claim keys and values are unknown
```suggestion
### Find your claim keys and values
```

2022-12-14 14:51 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +When you browse to the Console login landing page it will ask you to authetncate with your configured
These are instructions. It would be clearer to present them as numbered steps.

1. Open the Redpanda Console login page. Don't click the **OIDC** login button yet.
2. Open your browser's developer tools and inspect the network requests.
3. If your browser has the option to preserve logs, enable it.
  Without this option enabled, some browsers such as Google Chrome truncate the network request logs after a 
  redirection.
4. Click the **OIDC** login button and authenticate with your identity provider.
5. Search the network requests in your browser's developer tools for a request that starts with the relative path `/auth/callbacks/oidc?code=`.
6. Copy the value of the `jwt` cookie in the `set-cookie` header. The value of that cookie is an encrypted and compressed JSON web token.
7. Send the JSON web token to Redpanda Console to decode.
  ```
  curl -sL -X POST 'https://your-console-url.com/admin/session-token/decode' \
  -H 'Content-Type: application/json' \
  --data-raw '{
      "token": "<your-token>"
  }'
  ```
  The response is a JSON object, which includes your token in the `oAuthToken.access_token` field.
8. Paste your token into https://jwt.io, where you can inspect all your decoded claim keys.

2022-12-14 14:51 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +When you browse to the Console login landing page it will ask you to authetncate with your configured
This assumes that OIDC is the label of the button, if not, we should update the bold test to the button label.

2022-12-14 15:18 UTC, weeco commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +If you used a claim key in the role bindings that did not exist in the id token, Console will print
id token is correct, good call

2022-12-14 15:40 UTC, JakeSCahill reviewed
Add comments as suggestions.

2022-12-14 15:40 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +own account in the browser.
```suggestion
you can extract them from the JSON web token that is sent to your browser as a cookie. Because the claim values may be 
sensitive, Redpanda Console never logs them in the backend.
```

2022-12-14 15:40 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +and you can inspect all decoded claims that can be used in your role bindings.
```suggestion
1. Open the Redpanda Console login page. Don't click the OIDC login button yet.

1. Open your browser's developer tools and inspect the network requests.

1. If your browser has the option to preserve logs, enable it.
  Without this option enabled, some browsers such as Google Chrome truncate the network request logs after a redirection.
  
1. Click the OIDC login button and authenticate with your identity provider.

1. Search the network requests in your browser's developer tools for a request that starts with the relative path `/auth/callbacks/oidc?code=`.

1. Copy the value of the `jwt` cookie in the `set-cookie` header. The value of that cookie is an encrypted and compressed JSON web token.

1. Send the JSON web token to Redpanda Console to decode.

  \```bash
  curl -sL -X POST 'https://your-console-url.com/admin/session-token/decode' \
  -H 'Content-Type: application/json' \
  --data-raw '{
      "token": "<your-token>"
  }'
  \```

  The response is a JSON object, which includes your token in the `oAuthToken.access_token` field.

8. Paste your token into [https://jwt.io/](https://jwt.io/), where you can inspect all your decoded claim keys.
```

2022-12-15 10:59 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +  \```bash
```suggestion
  ```bash
```

2022-12-15 10:59 UTC, JakeSCahill commented on docs/platform/console/single-sign-on/identity-providers/generic-oidc.mdx
> +  \```
```suggestion
  ```
```

2022-12-15 11:07 UTC, JakeSCahill approved these changes

2022-12-15 15:24 UTC, weeco commented
Thanks a lot @JakeSCahill !

2022-12-15 15:24 UTC, merged