Configuring Producers doc
redpanda-data/documentation pull request #977
Opened 2022-12-23 17:07 UTC by Feediver1

Resolves #943 

New topic: Configuring Producers

2022-12-24 01:37 UTC, rkruze commented on docs/platform/development/configure-producers.mdx
> +in the form of events. In other woords, the role of the producer is to send
replace woords with words

2022-12-24 01:37 UTC, rkruze commented on docs/platform/development/configure-producers.mdx
> +messagesto a topic in the cluster. Producers communicate with Redpanda through
space between messages and to

2022-12-24 01:37 UTC, rkruze commented on docs/platform/development/configure-producers.mdx
> +the Kafka Producer API.
I would say the Kafka API

2022-12-24 01:42 UTC, rkruze commented on docs/platform/development/configure-producers.mdx
> +Producers can also publish messages to a particular partition.
This paragraph jumps from talking about the partition to the target topic and back to talking about partitions. It might be better to mention how a specific partition is selected for producing to. 

Every event is made up of a key and value. If the key is blank, then the producer will round-robin between the topic's partitions. If a key is provided, it is hashed using murmur2 and then module across the number of partitions.

2022-12-24 01:44 UTC, rkruze commented on docs/platform/development/configure-producers.mdx
> +is not acknowledged by the broker, and is useful when you are working with
Should that be "is acknowledged" instead of "is not acknowledged"?

2022-12-27 06:48 UTC, daisukebe commented on docs/platform/development/configure-producers.mdx
> +(and therefore, implicitly, all) replicas acknowledge the message. This increases
> after the leader and the majority of (and therefore, implicitly, all) replicas acknowledge the message

It's a bit confusing. Can we simply say `after the majority of (and therefore, implicitly, all) replicas acknowledge the message`?

2022-12-27 06:48 UTC, daisukebe commented on docs/platform/development/configure-producers.mdx
> +`acks=all`, then the producer will wait for all replicas to acknowledge the
> all replicas to acknowledge

`majority of replicas to acknowledge`?

2023-01-04 20:45 UTC, Feediver1 commented on docs/platform/development/configure-producers.mdx
> +(and therefore, implicitly, all) replicas acknowledge the message. This increases
Thx @daisukebe

2023-01-05 09:20 UTC, jrkinley commented on docs/platform/development/configure-producers.mdx
> +kind of response from the broker. This is the least safe option because a
+1

This is essentially a "fire and forget" mode for the producer.

2023-01-05 09:23 UTC, jrkinley commented on docs/platform/development/configure-producers.mdx
> +single-node crash can cause data loss. However, this setting is useful in cases
`a leader-node crash can cause data loss if the data has not yet replicated to the other nodes in the replica set`. I think we should make it clear that the data is still replicated, but the producer doesn't wait for it to happen. So the producer cannot guarantee that the messages it sends will persist after a crash.

2023-01-06 14:36 UTC, graphcareful commented on docs/platform/development/configure-producers.mdx
> +Redpanda provides a myriad of configuration options for all components of a
This section implies that the following are redpanda configuration options when they are not. They are configuration options that are set on the consumers end. It may be confusing to a user who is unfamiliar with kafka and then they may try to set some of these options in `redpanda.yml` thinking it may take effect.

2023-01-06 14:37 UTC, graphcareful commented on docs/platform/development/configure-producers.mdx
> +### Additional producer configuration options
Aren't there a bunch more configuration options? Does this article attempt to only cover the most used ones? Maybe it should be renamed to something like `redpanda most commonly used producer config options` or something?

2023-01-06 21:41 UTC, Feediver1 commented on docs/platform/development/configure-producers.mdx
> +Redpanda provides a myriad of configuration options for all components of a
@graphcareful Thanks Rob. Does this work?
"There are a myriad of configuration options for all components of a cluster."

If we don't claim that these are Redpanda-specific options, does that work?

2023-01-07 15:39 UTC, daisukebe approved these changes
LGTM

2023-01-09 19:17 UTC, shorgi requested changes

2023-01-09 19:17 UTC, shorgi commented on docs/platform/development/configure-producers.mdx
> +and [Consumer Offsets](../consumer-offsets).
Change to note admonition?

2023-01-09 19:17 UTC, shorgi commented on docs/platform/development/configure-producers.mdx
> +duplicates, or service downtime, you can test `acks` settings. If you set
```suggestion
duplicates, or service downtime, you can use higher durability `acks` settings. If you set
```

2023-01-09 19:25 UTC, Feediver1 commented on docs/platform/development/configure-producers.mdx
> +components of a Redpanda deployment. Within streaming applications, producers
I haven't seen an issue in the HTML output as of yet. In my last job, restructured text limited us to 80 character or something like that--anyway, I keep the lines short because it keeps the source easy to navigate--long lines required scrolling across the window and so I do it to avoid that.

2023-01-09 20:41 UTC, Feediver1 commented on docs/platform/development/configure-producers.mdx
> +partition in the cluster is complete.
Good suggestion.

2023-01-09 20:58 UTC, Feediver1 commented on docs/platform/development/configure-producers.mdx
> +* `buffer.memory`
Great catch

2023-01-09 21:07 UTC, Feediver1 commented on docs/platform/development/configure-producers.mdx
> +### Producer acknowledgement settings
Agree--we should always link to the setting description if/when it exists. In this case, there is no reference that offers more detailed guidance on these options than what appear in this doc.

2023-01-09 21:28 UTC, shorgi commented on docs/platform/development/configure-producers.mdx
> +Tune the btaching configuration using:
```suggestion
Tune the batching configuration using:
```

2023-01-09 21:30 UTC, shorgi approved these changes
Fix the typo in my previous comment, then LGTM.

2023-01-09 22:04 UTC, graphcareful commented on docs/platform/development/configure-producers.mdx
> +Redpanda provides a myriad of configuration options for all components of a
Maybe `client configuration options`. Indicating that these options that are referenced to in the article are client options, not broker options

2023-01-09 22:45 UTC, Feediver1 commented on docs/platform/development/configure-producers.mdx
> +Redpanda provides a myriad of configuration options for all components of a
Thanks @graphcareful !

2023-01-09 22:54 UTC, merged