docs: #866 Update Intro to Redpanda
redpanda-data/documentation pull request #987
Opened 2023-01-04 00:38 UTC by micheleRP

Resolves #866 

This updates the introduction to Redpanda. 

Preview:

2023-01-05 19:52 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +- With events, updates indicates that an action occurred at a specific time. They are not directed to a specific recipient.
```suggestion
- With events, updates indicate that an action occurred at a specific time. They are not directed to a specific recipient.
```

2023-01-05 21:19 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +In event-driven architecture, all actions are defined and packaged as events to precisely identify individual actions and how they're processed throughout the system. Instead of processing updates in
My understanding is that within Kafka, events are actions or operations (for example, authentication events, or authorization events), and that Kafka publishes streams of these events. What I'm not sure of, though, is whether events as you have categorized them here (purchase, payment, delivery, inventory, etc) map to events as defined in Kafka. I definitely think it is worthwhile to have a PM weigh in on the analogy here to see if it is apt for our audience. I could be out in left field on this one, but that is the thought I had after reading this.

2023-01-05 21:21 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +Producers are client applications that write data to Redpanda in the form of events. Redpanda reads the events in sequence and organizes them into topics, representing a replayable log of changes in
```suggestion
Producers are client applications that write data to Redpanda in the form of events. Redpanda reads the events in sequence and organizes them into topics, which represent a replayable log of changes in the system. 
```

2023-01-05 21:23 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +Consumers are client applications that then read these events from Redpanda topics. Consumers can store, process, or react to the events.
```suggestion
Consumers are client applications that read these events from Redpanda topics. Consumers can store, process, or react to the events. 
```

2023-01-06 20:07 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +| Event-driven updates | Message-driven updates |
Boy, this would be a fantastic place for a diagram that depicts this difference. Have you thought about that? We can request through Ben...let me know if you want to do that. I just think a visual representation of this that a reader could scan would reinforce/clarify the difference.

2023-01-06 20:08 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +Redpanda is less complex and less costly than any other mission-critical event streaming platform. It's fast, it's easy, and it keeps your data safe.
Please run this by PM. We have to be 100% sure this claim is absolutely true.

2023-01-06 20:10 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +- Redpanda is designed for maximum performance on any data streaming workload. It can scale up to use all available resources on a single machine and scale out to distribute performance across multip
How about setting each of the first statements off from the rest of the paragraph for emphasis and clarity wrt to our key claims?
- Redpanda is designed for maximum performance on any data streaming workload. 
   Redpanda can scale up to use all available resources on a single machine and scale out to distribute 
   performance across multiple machines. This enables previously-unimaginable use cases that require high 
   throughput, low latency, and a minimal hardware footprint.

2023-01-06 20:11 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +- Redpanda is packaged as a single binary: it doesn't rely on any external systems. It's fully compatible with the Kafka API, so it works with the ecosystem of tools and integrations built on Kafka.
```suggestion
- Redpanda is packaged as a single binary: it doesn't rely on any external systems. 
   Redpanda is fully compatible with the Kafka API, so it works with the ecosystem of tools and integrations built 
   on Kafka. Redpanda can be deployed on bare metal, containers, or virtual machines in a data center or in the 
   cloud. And Redpanda Console makes it easy to set up, manage, and monitor your clusters. Additionally, Tiered 
   Storage lets you archive log segments to cloud storage in near real time, providing infinite data retention and 
   topic recovery. 
```

2023-01-06 20:12 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +- Redpanda is packaged as a single binary: it doesn't rely on any external systems. It's fully compatible with the Kafka API, so it works with the ecosystem of tools and integrations built on Kafka.
- Redpanda is packaged as a single binary: it doesn't rely on any external systems. 
   Redpanda is fully compatible with the Kafka API, so it works with the ecosystem of tools and integrations 
   built on Kafka. Redpanda can be deployed on bare metal, containers, or virtual machines in a data center or 
   in the cloud. And Redpanda Console makes it easy to set up, manage, and monitor your clusters. 
   Additionally, Tiered Storage lets you archive log segments to cloud storage in near real time, providing 
   infinite data retention and topic recovery.

2023-01-06 20:13 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +- Redpanda is packaged as a single binary: it doesn't rely on any external systems. It's fully compatible with the Kafka API, so it works with the ecosystem of tools and integrations built on Kafka.
ignore formatting grimness--you get the gist of it...

2023-01-06 20:13 UTC, Feediver1 commented on docs/platform/introduction/intro-to-events.mdx
> +- Redpanda uses the [Raft consensus algorithm](https://raft.github.io/) to write data to log files and replicate that data across multiple servers. Raft facilitates communication between the nodes in
- Redpanda uses the [Raft consensus algorithm](https://raft.github.io/) to write data to log files and replicate that data across multiple servers. 
Raft facilitates communication between the nodes in a Redpanda cluster to make sure that they agree on changes and remain in sync, even if a minority of them are in a failure state. This allows Redpanda to tolerate partial environmental failures and deliver predictable performance, even at high loads.

2023-01-06 21:11 UTC, Feediver1 commented on docs/platform/introduction/architecture.mdx
> +## Tiered Storage
I'm wondering if there is already a diagram floating around - perhaps within PM or Marketing - that lays out the interaction/relationship between all of the features you describe here. If not, I think this doc sure could use it -- kind of the "big picture" of how RP works.

2023-01-06 21:32 UTC, Feediver1 commented on docs/platform/introduction/architecture.mdx
> +From a sizing perspective, Redpanda’s ability to efficiently use all available hardware lets it scale up to get the most out of your infrastructure, before you’re forced to scale out to meet the dema
```suggestion
From a sizing perspective, Redpanda’s ability to efficiently use all available hardware enables it to scale up to get the most out of your infrastructure, before you’re forced to scale out to meet the demands of your workload. Redpanda delivers better performance with a smaller footprint, resulting in reduced operational costs and complexity.
```

2023-01-06 21:33 UTC, Feediver1 approved these changes
LGTM @micheleRP !

2023-01-07 04:53 UTC, micheleRP commented on docs/platform/introduction/intro-to-events.mdx
> +| Event-driven updates | Message-driven updates |
@Feediver1: I agree! This page could use an image to visualize benefits of Redpanda.

2023-01-07 04:53 UTC, micheleRP commented on docs/platform/introduction/intro-to-events.mdx
> +Redpanda is less complex and less costly than any other mission-critical event streaming platform. It's fast, it's easy, and it keeps your data safe.
@mattschumpert Would you please review this? I know we say it, and post it... but this OK to put in our docs?

2023-01-08 22:14 UTC, larsenpanda commented
The box that explains event driven va message driven updates is not really usable on mobile. Maybe thats just in the preview display but thought i'd bring it up.

2023-01-08 22:15 UTC, larsenpanda commented on docs/platform/introduction/architecture.mdx
> +## Tiered Storage
+1 I've been asked for this

2023-01-08 22:19 UTC, larsenpanda commented
Re: "Redpanda uses the Raft consensus algorithm".. part, I think it would be good to word it to illustrates that Redpanda has raft woven throughout the platform, given the fact that "kafka uses raft" as well but totally separately with a different platform/nodes to manage.

2023-01-09 13:57 UTC, daisukebe commented on docs/platform/introduction/architecture.mdx
> +Raft is a majority vote algorithm. For a leader to acknowledge that an event has been committed to a partition, a majority of its replicas must have written that event to their copy of the log. When
> respond to the producer to acknowledge receipt of the event

This depends on `acks` the producer has. Better to document in the way below? And we may want to link to the Producer doc (https://github.com/redpanda-data/documentation/pull/977)?

> respond to the producer to acknowledge receipt of the event when `acks=all (-1)`

2023-01-09 13:57 UTC, daisukebe commented on docs/platform/introduction/architecture.mdx
> +Raft is a majority vote algorithm. For a leader to acknowledge that an event has been committed to a partition, a majority of its replicas must have written that event to their copy of the log. When
@Feediver1 ^^

2023-01-09 15:34 UTC, hcoyote commented on docs/platform/introduction/intro-to-events.mdx
> +- Redpanda uses the [Raft consensus algorithm](https://raft.github.io/) to write data to log files and replicate that data across multiple servers.
Is it more correct to state: "Redpanda uses the Raft consensus algorithm to _coordinate_ writing data to log files ..." ?

2023-01-09 15:45 UTC, hcoyote commented on docs/platform/introduction/architecture.mdx
> +As long as the leader and a majority of the replicas are stable, Redpanda can tolerate disturbances in a minority of the replicas. If gray failures cause a minority of replicas to respond slower than
A link to a discussion on what "gray failures" are would be good here. Inexperienced practitioners may not know what that is.

2023-01-09 15:50 UTC, hcoyote commented on docs/platform/introduction/architecture.mdx
> +When this happens, the follower increments its term and votes for itself to be the leader for that term. It then sends a vote request to the other nodes and waits for one of the following scenarios:
Is there a name for what "this" refers to in "When this happens"? skipped heratbeat? failed heartbeat?

2023-01-09 16:00 UTC, hcoyote commented on docs/platform/introduction/architecture.mdx
> +## Partition leadership elections
I know we mention raft.github.io page in the previous section for more information. It might be good to reinforce in this section the existence of the protocol visualizer that exists in that page.

2023-01-10 01:19 UTC, mattschumpert commented on docs/platform/introduction/intro-to-events.mdx
> +Redpanda is less complex and less costly than any other mission-critical event streaming platform. It's fast, it's easy, and it keeps your data safe.
we might want to add the word 'commercial' to event streaming platform.  One can certainly make an argument that Apache Kafka (free software) can be used for mission-critical event streaming.

2023-01-10 17:51 UTC, micheleRP commented on docs/platform/introduction/intro-to-events.mdx
> +- Redpanda uses the [Raft consensus algorithm](https://raft.github.io/) to write data to log files and replicate that data across multiple servers.
Thanks, @hcoyote! "How's this: Redpanda uses the [Raft consensus algorithm](https://raft.github.io/) throughout the platform to coordinate writing data to log files and replicating that data across multiple servers."

2023-01-10 17:53 UTC, micheleRP commented on docs/platform/introduction/architecture.mdx
> +Raft is a majority vote algorithm. For a leader to acknowledge that an event has been committed to a partition, a majority of its replicas must have written that event to their copy of the log. When
Thanks @daisukebe! I updated that line and added a link to the new Producer Acknowledgement Settings page  https://deploy-preview-987--redpanda-documentation.netlify.app/docs/platform/introduction/architecture/#raft-consensus-algorithm

2023-01-10 19:47 UTC, hcoyote commented on docs/platform/introduction/intro-to-events.mdx
> +- Redpanda uses the [Raft consensus algorithm](https://raft.github.io/) to write data to log files and replicate that data across multiple servers.
+1

2023-01-13 09:25 UTC, jrkinley requested changes

2023-01-13 09:25 UTC, jrkinley commented on docs/platform/introduction/intro-to-events.mdx
> +| Event-driven updates | Message-driven updates |
@micheleRP I think the table should make it clear to the reader that Redpanda only supports events. Redpanda doesn't support sending messages directly from a producer to a consumer.

2023-01-13 09:25 UTC, jrkinley commented on docs/platform/introduction/intro-to-events.mdx
> +| Events are sent from the producer to an event processing system (Redpanda) that acknowledges receipt and guarantees delivery to multiple consumers. The system tracks communication between producers
> _Events are sent from the producer to an event processing system (Redpanda) that acknowledges receipt and guarantees delivery to multiple consumers. The system tracks communication between producers and consumers if there's a broken connection._

From a producer perspective, Redpanda will acknowledge receipt of a write and this provides inherent guarantees that the write is durable within the system. A producer is not aware of any consumers, they are completely decoupled. Redpanda does guarantee delivery to the subscribed consumers, but I'm not sure what you mean by the system tracks communication between producers and consumers if there is a broken connection.

2023-01-13 09:25 UTC, jrkinley commented on docs/platform/introduction/intro-to-events.mdx
> +Redpanda is less complex and less costly than any other commericial mission-critical event streaming platform. It's fast, it's easy, and it keeps your data safe.
I think we should remove the word _commercial_ here otherwise we're ignoring Apache Kafka.

2023-01-13 09:25 UTC, jrkinley commented on docs/platform/introduction/intro-to-events.mdx
> +  It's fully compatible with the Kafka API, so it works with the ecosystem of tools and integrations built on Kafka. Redpanda can be deployed on bare metal, containers, or virtual machines in a data
> _It's fully compatible with the Kafka API_

It's compatible with the Kafka API

2023-01-13 09:25 UTC, jrkinley commented on docs/platform/introduction/architecture.mdx
> +Redpanda [Tiered Storage](../../data-management/tiered-storage/) is a multi-tiered remote storage solution that provides the ability to archive log segments to cloud storage in near real time. Tiered
> _provides the ability to archive log segments to cloud storage_

provides the ability to **offload** log segments to cloud storage

2023-01-13 09:25 UTC, jrkinley commented on docs/platform/introduction/architecture.mdx
> +Local storage is finite and managed by Redpanda’s data retention settings. The size of the provisioned storage determines how much data your topics can retain. This is typically no more than a few we
I'd remove the last paragraph about finite local storage.

2023-01-13 14:51 UTC, micheleRP commented on docs/platform/introduction/intro-to-events.mdx
> +Redpanda is less complex and less costly than any other commericial mission-critical event streaming platform. It's fast, it's easy, and it keeps your data safe.
@jrkinley: Matt had suggested that we add "commercial" to this line. See https://github.com/redpanda-data/documentation/pull/987#discussion_r1065249663.

2023-01-13 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redpanda-data/documentation?pullRequest=987) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redpanda-data/documentation?pullRequest=987) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redpanda-data/documentation?pullRequest=987) it.</sub>

2023-01-13 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redpanda-data/documentation?pullRequest=987) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redpanda-data/documentation?pullRequest=987) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redpanda-data/documentation?pullRequest=987) it.</sub>

2023-01-13 15:50 UTC, micheleRP commented on docs/platform/introduction/intro-to-events.mdx
> +| Events are sent from the producer to an event processing system (Redpanda) that acknowledges receipt and guarantees delivery to multiple consumers. The system tracks communication between producers
Thanks, @jrkinley. I simplified this table. We can remove it altogether if it's more confusing than helpful.

2023-01-13 17:03 UTC, jrkinley approved these changes

2023-01-13 17:47 UTC, merged